[appendix]
:appendix-caption: Annex
[[glossary]]
= Glossary

*conformance test class* +
set of conformance test modules that must be applied to receive a single certificate of
conformance +
{blank}[OGC 08-131r3, definition 4.4]

*feature* +
abstraction of real world phenomena +
{blank}[ISO 19101-1:2014, definition 4.1.11]

*feature attribute* +
characteristic of a feature +
{blank}[ISO 19101-1:2014, definition 4.1.12]

[[FeatureType-section]]
*feature type* +
class of features having common characteristics +
{blank}[ISO 19156:2011, definition 4.7]

*measurement* +
set of operations having the object of determining the value of a quantity +
{blank}[ISO 19101-2:2018, definition 3.21] / [VIM:1993, 2.1]

*model* +
abstraction of some aspects of reality +
{blank}[ISO 19109:2015, definition 4.15]

*observation* +
act of measuring or otherwise determining the value of a property +
{blank}[ISO 19156:2011, definition 4.11]

*observation procedure* +
method, algorithm or instrument, or system of these, which may be used in making an
observation +
{blank}[ISO 19156:2011, 4.12]

*observation result* +
estimate of the value of a property determined through a known observation procedure +
{blank}[ISO 19156:2011, 4.14]

*property* +
facet or attribute of an object referenced by a name. +
{blank}[ISO 19143:2010, definition 4.21]

*requirements class* +
aggregate of all requirement modules that must all be satisfied to satisfy a conformance
test class +
{blank}[OGC 08-131r3, definition 4.19]

*schema* +
formal description of a model +
{blank}[ISO 19101-1:2014, definition 4.1.34]

*sensor* +
type of observation procedure that provides the estimated value of an observed
property at its output +
{blank}[OGC 08-094r1, definition 4.5]

[[standardization-target-definition]]
*Standardization Target* +
TBD

*timeseries* +
sequence of data values which are ordered in time +
{blank}[OGC 15-043r3]

*universe of discourse* +
view of the real or hypothetical world that includes everything of interest +
{blank}[ISO 19101-1:2014, definition 4.1.38]

*version* +
Particular variation of a spatial object +
{blank}[INSPIRE Glossary]

=== Abbreviated Terms

* 2D {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Two Dimensional
* 3D {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Three Dimensional
* AEC {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Architecture, Engineering, Construction
* ALKIS {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} German National Standard for Cadastral Information
* ATKIS {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} German National Standard for Topographic and Cartographic Information
* BIM {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Building Information Modeling
* B-Rep {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Boundary Representation
* bSI {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} buildingSMART International
* CAD {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Computer Aided Design
* COLLADA {nbsp} Collaborative Design Activity
* CSG {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Constructive Solid Geometry
* DTM {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Digital Terrain Model
* DXF {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Drawing Exchange Format
* EuroSDR {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} European Spatial Data Research Organisation
* ESRI {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Environmental Systems Research Institute
* FM {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Facility Management
* GDF {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Geographic Data Files
* GDI-DE {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Spatial Data Infrastructure Germany (Geodateninfrastruktur Deutschland)
* GDI {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} NRW Geodata Infrastructure North-Rhine Westphalia
* GML {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Geography Markup Language
* IAI {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} International Alliance for Interoperability (now buildingSMART International (bSI))
* IETF {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Internet Engineering Task Force
* IFC {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Industry Foundation Classes
* ISO {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} International Organization for Standardisation
* ISO/TC211 {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} ISO Technical Committee 211
* LOD {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Levels of Detail
* NBIMS {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} National Building Information Model Standard
* OASIS {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Organisation for the Advancement of Structured Information Standards
* OGC {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Open Geospatial Consortium
* OSCRE {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Open Standards Consortium for Real Estate
* SIG 3D {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Special Interest Group 3D of the GDI-DE
* TIC {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Terrain Intersection Curve
* TIN {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Triangulated Irregular Network
* UML {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Unified Modeling Language
* URI {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Uniform Resource Identifier
* VRML {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Virtual Reality Modeling Language
* W3C {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} World Wide Web Consortium
* W3DS {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} OGC Web 3D Service
* WFS {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} OGC Web Feature Service
* X3D {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Open Standards XML-enabled 3D file format of the Web 3D Consortium
* XML {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Extensible Markup Language
* xAL {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} OASIS extensible Address Language

=== ISO Concepts

The following concepts are referenced from the ISO classes detailed above. They are provided here to support a more complete definition of those classes.

[[CV_DiscreteCoverage-section]]
*CVF_DiscreteCoverage*

[[CV_GridPointValuePair-section]]
*CV_GridPointValuePair*

[[CV_GridValuesMatrix-section]]
*CV_GridValuesMatrix*

[[CRS-section]]
*CRS*

[[Geometry-section]]
*Geometry*

[[CV_DomainObject-section]]
*CV_DomainObject*

[[Length-section]]
*Length*

[[GM_MultiPrimitive-section]]
*GM_MultiPrimitive*

[[Area-section]]
*Area*

[[GM_Primitive-section]]
*GM_Primitive*

[[Point-section]]
*Point*

[[GM_CompositePoint-section]]
*GM_CompositePoint*

[[GM_CompositeSolid-section]]
*GM_CompositeSolid*

[[Solid-section]]
*Solid*

[[GM_OrientableSurface-section]]
*GM_OrientableSurface*

[[GM_GenericSurface-section]]
*GM_GenericSurface*

[[GM_PolyhedralSurface-section]]
*GM_PolyhedralSurface*

[[GM_LineString-section]]
*GM_LineString*

[[GM_Position-section]]
*GM_Position*

[[Distance-section]]
*Distance*

[[TM_TemporalPosition-section]]
*TM_TemporalPosition*

[[Date-section]]
*Date*

[[Time-section]]
*Time*

[[DateTime-section]]
*DateTime*

[[CharacterString-section]]
*CharacterString*

[[CV_ReferenceableGrid-section]]
*CV_ReferenceableGrid*

[[CC_CoordinateOperation-section]]
*CC_CoordinateOperation*

[[IO_IdentifiedObjectBase-section]]
*IO_IdentifiedObjectBase*

[[RS_ReferenceSystem-section]]
*RS_ReferenceSystem*

[[integer-section]]
*Integer*

[[number-section]]
*Number*

