== Terms and Definitions
This document uses the terms defined in Sub-clause 5.3 of [OGC 06-121r8], which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this Standard.

For the purposes of this document, the following additional terms and definitions apply.

*2D data* +
geometry of features is represented in a two-dimensional space +
NOTE In other words, the geometry of 2D data is given using (X,Y) coordinates. +
{blank}[INSPIRE D2.8.III.2, definition 1]

*2.5D data* +
geometry of features is represented in a three-dimensional space with the constraint that, for each (X,Y) position, there is only one Z +
{blank}[INSPIRE D2.8.III.2, definition 2]

*3D data* +
Geometry of features is represented in a three-dimensional space. +
NOTE In other words, the geometry of 2D data is given using (X,Y,Z) coordinates without any constraints. +
{blank}[INSPIRE D2.8.III.2, definition 3]

*conceptual model* +
model that defines concepts of a universe of discourse +
{blank}[ISO 19101-1:2014, 4.1.5]

*conceptual schema* +
formal description of a conceptual model +
{blank}[ISO 19101-1:2014, 4.1.6]

*level of detail* +
quantity of information that portrays the real world +
NOTE The concept comprises data capturing rules of spatial object types, the accuracy and the types of geometries, and other aspects of a data specification. In particular, it is related to the notions of scale and resolution. +
{blank}[INSPIRE Glossary]

*life-cycle information* +
set of properties of a spatial object that describe the temporal characteristics of a version of a spatial object or the changes between versions +
{blank}[INSPIRE Glossary]
