== Scope

This document is an OGC Conceptual Model (CM) Standard for specifying the representation of virtual 3D city and landscape models. The CityGML 3.0 Conceptual Model is expected to be the basis for a number of future Encoding Standards in which subsets of the Conceptual Model can be implemented. These Encoding Standards will enable both storage and exchange of data. At a minimum, support for a Geography Markup Language (GML) encoding is expected. Additional encodings in formats such as JSON and database schemas will be highly desirable.

In contrast to CityGML 2.0, the 3.0 Conceptual Model is NOT implemented as an application schema of GML. However, a preliminary encoding in GML version 3.2 is available as an informative resource separately from this standard to allow implementation and testing of the CityGML Conceptual Model.

The target of the conformance classes specified in this document are

* CityGML Implementation Specifications that provide encodings for the UML conceptual model specified in this document, and
* Additional UML models that can be created by users to extend this conceptual model as Application Domain Extensions (ADEs).

CityGML models are comprised of georeferenced 3D vector data along with the semantics associated with the data. In contrast to other 3D vector formats, CityGML is based on a rich, general purpose information model in addition to geometry and appearance information that allows for the integration of a variety of source data to come together in a City Model. To enable the use of CityGML in specific domain areas, CityGML has historically provided an extension mechanism to enrich the data with identifiable features and properties, preserving semantic interoperability. Recognizing that an implementable expansion mechanism might have dependencies based on the encoding language, the CityGML 3.0 Conceptual Model specifies high level requirements rather than a full extension model.

Targeted application areas explicitly include:

* Urban and landscape planning; 
* Architectural design; 
* Tourist and leisure activities; 
* Environmental, 
* Energy and mobility simulations; 
* Mobile telecommunications; 
* Disaster management; 
* Homeland security; 
* Vehicle and pedestrian navigation; 
* Training simulators and mobile robotics.

The future CityGML 3.0 Implementation Specifications will be implementable source formats for 3D portraying or transformation into dedicated portayal formats such as the OGC I3S or the OGC 3D Tiles Community Standards, OGC KML, COLLADA or glTF. The OGC 3D Portrayal Service (3DPS) may be used for content delivery.

Features of the CityGML 3.0 Conceptual Model:

* Geospatial Information Model (ontology) for urban landscapes based on the ISO 19100 family.
* Representation of 3D geometries, based on the ISO 19107 model, independent of data encodings, as well as of 3D point clouds.
* Grouping into space hierarchies, including concepts like stories/floors within buildings.
* Representation of object surface characteristics (e.g. textures, materials).
* Representation of dynamic, i.e. time-dependent, properties of city models.
* Taxonomies and aggregations including:
** Digital Terrain Models as a combination of triangulated irregular networks (TINs), regular grids, break and skeleton lines, mass points.
** Sites (currently buildings, other constructions, bridges, and tunnels).
** Vegetation (areas, volumes, and solitary objects with vegetation classification).
** Water bodies (volumes, surfaces).
** Transportation facilities (graph structures, 3D space, and 3D surface data).
** Land use (representation of areas of the earth’s surface dedicated to a specific land use).
** City furniture.
** Generic city objects and attributes.
** User-definable (recursive) grouping.
* Multiscale model with 4 well-defined consecutive Levels of Detail (LOD), applicable to both interior and exterior:
** LOD0 – Highly generalized model.
** LOD1 – Block model / extrusion objects.
** LOD2 – Realistic, but still generalized model.
** LOD3 – Highly detailed model.
* Multiple representations in different LODs simultaneously and generalization relations between objects in different LODs.
* Ability to combine different interior and exterior LoDs, including representation of floor plans.
* Optional topological connections between feature (sub)geometries.
* Enables a variety of different encoding specifications, including GML and JSON.
* Extension of the conceptual model through code lists, generic objects and Application Domain Extensions (ADEs).
* With CityGML 3.0, ADEs become platform-independent models on a conceptual level that can be mapped to multiple and different target encodings. ADEs are implemented as UML models that extend the conceptual model in this standard. This includes a mechanism that favors the insertion of additional feature properties into any defined feature class through 'hooks' over subtyping of features. This means that the existing feature classes can be used and additional properties from one or more ADEs can easily be supported in different encodings.
* Ability to specify an ADE that can be further extended.