[[conformance-section]]

== Conformance

This standard defines a Conceptual Model which is independent of any encoding or formatting techniques. The Standardization Targets for this standard are Implementation Specifications. Each Implementation Specification defines how the Conceptual Model shall be implemented using a specific technology. Conformant Implementation Specifications provide evidence that they are an accurate representation of the Conceptual Model. This evidence shall include implementations of the abstract tests specified in Annex A (normative) of this document. 

Since this standard is agnostic to the implementing technologies, the specific techniques to be used for conformance testing cannot be specified. It is the responsibility of the Implementation Specifications to provide evidence of conformance which is appropriate for the implementing technologies. This evidence should be provided as an annex to the Implementation Specification document. 

This standard identifies seventeen (17) conformance classes. One conformance class is defined for each Package in the UML model. Each conformance class is defined by one requirements class. The tests in Annex A are organized by Requirements Class. So an implementation of the _Core_ conformance class must pass all tests specified in Annex A for the _Core_ requirements class.

Of these seventeen conformance classes, Implementation Specifications are only required to implement the _Core_ conformance class. All other conformance classes are optional. In the case where an implemented conformance class has a dependency on another conformance class, that conformance class shall also be implemented. 

The CityGML Conceptual Model is defined by the CityGML UML model. This specification is a representation of that UML model in document form. In the case of a discrepancy between the UML model and this document, the UML model is authoritative. 






