NOTE: Explanatory text edit 04 for 01.04.2020 release starts here

== Terms and Definitions
This document uses the terms defined in Sub-clause 5.3 of [OGC 06-121r8], which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this Best Practice.

For the purposes of this document, the following additional terms and definitions apply.

=== *term name*
text of the definition

=== Abbreviated Terms
The following abbreviated terms are used in this document:

* 2D {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Two Dimensional
* 3D {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Three Dimensional
* AEC {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Architecture, Engineering, Construction
* ALKIS {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} German National Standard for Cadastral Information
* ATKIS {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} German National Standard for Topographic and Cartographic Information
* B-Rep {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Boundary Representation
* bSI {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} buildingSMART International
* CAD {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Computer Aided Design
* COLLADA {nbsp} Collaborative Design Activity
* CSG {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Constructive Solid Geometry
* DTM {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Digital Terrain Model
* DXF {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Drawing Exchange Format
* EuroSDR {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} European Spatial Data Research Organisation
* ESRI {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Environmental Systems Research Institute
* FM {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Facility Management
* GDF {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Geographic Data Files
* GDI-DE {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Spatial Data Infrastructure Germany (Geodateninfrastruktur Deutschland)
* GDI {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} NRW Geodata Infrastructure North-Rhine Westphalia
* GML {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Geography Markup Language
* IAI {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} International Alliance for Interoperability (now buildingSMART International (bSI))
* IETF {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Internet Engineering Task Force
* IFC {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Industry Foundation Classes
* ISO {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} International Organization for Standardisation
* LOD {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Level of Detail
* NBIMS {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} National Building Information Model Standard
* OASIS {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Organisation for the Advancement of Structured Information Standards
* OGC {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Open Geospatial Consortium
* OSCRE {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Open Standards Consortium for Real Estate
* SIG 3D {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Special Interest Group 3D of the GDI-DE
* TC211 {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} ISO Technical Committee 211
* TIC {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Terrain Intersection Curve
* TIN {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Triangulated Irregular Network
* UML {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Unified Modeling Language
* URI {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Uniform Resource Identifier
* VRML {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Virtual Reality Modeling Language
* W3C {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} World Wide Web Consortium
* W3DS {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} OGC Web 3D Service
* WFS {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} OGC Web Feature Service
* X3D {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Open Standards XML-enabled 3D file format of the Web 3D Consortium
* XML {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Extensible Markup Language
* xAL {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} OASIS extensible Address Language

NOTE: Explanatory text edit 04 for 01.04.2020 release ends here
