== Scope

This document is an OGC Conceptual Data Model Standard to specify the representation of virtual 3D city and landscape models. The CityGML v3.0 Conceptual Model is expected to be the basis for a number of future Encoding Standards in which subsets of the Conceptual Model can be implemented. These Encoding Standards will enable both storage and exchange of data. Support for GML encoding is expected as a minimum, though additonal encodings in formats such as JSON and database schemas will be highly desirable. 

In contrast to the previous CityGML v2.0, the v3.0 Conceptual Model is NOT implemented as an application schema of the Geography Markup Language version 3.3, though a preliminary encoding in GML version 3.2.1 is available as an informative resource separately from this specification to allow implementation and testing.

The target of the conformance classes specified in this document are

* CityGML encoding specifications that provide encodings for the UML data model specified in this document, and 
* Additional UML models that can be created by users to extend this data model as Application Domain Extensions. 

CityGML models comprise of georeferenced 3D vector data along with the semantics associated with the data. In contrast to other 3D vector formats, CityGML is based on a rich, general purpose information model in addition to geometry and appearance information that allows for the integration of a variety of source data to come together in a City Model. To enable the use of CityGML in specific  domain areas CityGML has historically provided an extension mechanism to enrich the data with identifiable features and properties, preserving semantic interoperability. As it is recognised that an implementable expension mechanism might have dependencies on the encoding language, the CityGML v3.0 Conceptual Model specifies high level requirements rather than an full extension model. 

Targeted application areas explicitly include urban and landscape planning; architectural design; tourist and leisure activities; environmental, energy and mobility simulations; mobile telecommunications; disaster management; homeland security; vehicle and pedestrian navigation; training simulators and mobile robotics.

The future CityGML v3.0 Encoding Standards will be implementable source formats for 3D portraying or transformation into dedicated potrayal formats such as the OGC i3S or the OGC 3D tiles community standards, KML/COLLADA or glTF. The OGC Portrayal 3D Portrayal Service may be used for content delivery.

Features of the CityGML v3.0 Conceptual Model:

* Geospatial Information Model (ontology) for urban landscapes based on the ISO 191xx family
* Representation of 3D geometries, based on the ISO 19107 model, independent of data encodings
* Grouping into space hierarchies, including concepts like stories/floors within buildings
* Representation of object surface characteristics (e.g. textures, materials)
* Taxonomies and aggregations
** Digital Terrain Models as a combination of triangulated irregular networks (TINs), regular rasters, break and skeleton lines, mass points
** Sites (currently buildings, other constructions, bridges, and tunnels)
** Vegetation (areas, volumes, and solitary objects with vegetation classification)
** Water bodies (volumes, surfaces)
** Transportation facilities (both graph structures and 3D surface data)
** Land use (representation of areas of the earth’s surface dedicated to a specific land use)
** City furniture
** Generic city objects and attributes
** User-definable (recursive) grouping
* Multiscale model with 4 well-defined consecutive Levels of Detail (LOD), applicable to both interior and exterior:
** LOD0 – regional, landscape
** LOD1 – city, region
** LOD2 – city districts, projects
** LOD3 – architectural models, landmarks
* Multiple representations in different LODs simultaneously; generalisation relations between objects in different LODs
* Ability to combine different interior and exterior LoDs. including representation of floor plans
* Optional topological connections between feature (sub)geometries
* Enables a variety of different encoding specifications, including GML and JSON
* Extension of data model through code lists, generic objects and Application Domain Extensions (ADEs)
* With CityGML 3.0, ADEs become platform-independent models on a conceptual level that can be mapped to multiple and different target encodings. ADEs are implemented as UML models that extend the data model in this specification. This includes a mechanism that favours the insertion of additional feature properties into any defined feature class through 'hooks' over subtyping of features. This means that the existing feature classes can be used and additional properties from one or more ADEs can easily be supported in different encodings
* Ability to specify an ADE that can be further extended 
