NOTE: Explanatory text edit 03 for 01.04.2020 release starts here

== References
The following normative documents contain provisions that, through reference in this text, constitute provisions of OGC 20-010. For dated references, subsequent amendments to, or revisions of, any of these publications do not apply. However, parties to agreements based on this part of OGC 12-019 are encouraged to investigate the possibility of applying the most recent editions of the normative documents indicated below. For undated references, the latest edition of the normative document referred to applies.

* ISO: ISO 8601:2004, Data elements and interchange formats – Information interchange – Representation of dates and times
* ISO: ISO 19103:2015, Geographic Information – Conceptual Schema Language
* ISO: ISO 19105:2000, Geographic information – Conformance and testing
* ISO: ISO 19107:2003, Geographic Information – Spatial Schema
* ISO: ISO 19109:2015, Geographic Information – Rules for Application Schemas
* ISO: ISO 19111:2019, Geographic information – Referencing by coordinates
* ISO: ISO 19115-1:2014, Geographic information — Metadata — Part 1: Fundamentals
* ISO: ISO 19123:2005, Geographic information — Schema for coverage geometry and functions
* ISO: ISO 19156:2011, Geographic information – Observations and measurements
* ISO: ISO/IEC 19505-2:2012, Information technology — Object Management Group Unified Modeling Language (OMG UML) — Part 2: Superstructure
* ISO/IEC 19507:2012, Information technology — Object Management Group Object Constraint Language (OCL)
* ISO: ISO/IEC 19775-1:2013 Information technology — Computer graphics, image processing and environmental data representation — Extensible 3D (X3D) — Part 1: Architecture and base components
* OGC: The OpenGIS® Abstract Specification Topic 5: Features, OGC document 08-126
* OGC: The OpenGIS™ Abstract Specification Topic 8: Relationships Between Features, OGC document 99-108r2
* OGC: The OpenGIS™ Abstract Specification Topic 10: Feature Collections, OGC document 99-110
* IETF: RFC 2045 & 2046, Multipurpose Internet Mail Extensions (MIME). (November 1996)
* IETF: RFC 3986, Uniform Resource Identifier (URI): Generic Syntax. (January 2005)
* OASIS: extensible Address Language (xAL v2.0)
* Khronos Group Inc.: COLLADA – Digital Asset Schema Release 1.5.0

[yellow-background]*+++<color rgb="#ff0000">The following references were listed in the CityGML 2.0 specification. For CityGML 3.0, these references should either be moved to the GML Encoding specification and be updated there or be removed completely:</color>+++*

* OGC: OpenGIS® Abstract Specification Topic 0, Overview, OGC document 04-084
* ISO / TC211: ISO/TS 19139:2007, Geographic Information – Metadata – XML schema implementation
* OGC: OpenGIS® Geography Markup Language Implementation Specification, Version 3.1.1, OGC document 03-105r1
* OGC: OpenGIS® GML 3.1.1 Simple Dictionary Profile, Version 1.0.0, OGC document 05-099r2
* W3C: W3C XLink, XML Linking Language (XLink) Version 1.0. W3C Recommendation (27 June 2001)
* W3C: W3C XMLName, Namespaces in XML. W3C Recommendation (14 January 1999)
* W3C: W3C XMLSchema-1, XML Schema Part 1: Structures. W3C Recommendation (2 May 2001)
* W3C: W3C XMLSchema-2, XML Schema Part 2: Datatypes. W3C Recommendation (2 May 2001)
* W3C: W3C XPointer, XML Pointer Language (XPointer) Version 1.0. W3C Working Draft (16 August 2002)
* W3C: W3C XML Base, XML Base, W3C Recommendation (27 June 2001)
* W3C: W3C XML, Extensible Markup Language (XML) 1.0 (Second Edition), W3C Recommendation (6 October 2000)
* Jelliffe, R: The Schematron Assertion Language 1.5. (2002-10-01)


NOTE: Explanatory text edit 03  for 01.04.2020 release ends here
