== References
The following normative documents contain provisions that, through reference in this text, constitute provisions of OGC 20-010. For dated references, subsequent amendments to, or revisions of, any of these publications do not apply. However, parties to agreements based on this part of OGC 12-019 are encouraged to investigate the possibility of applying the most recent editions of the normative documents indicated below. For undated references, the latest edition of the normative document referred to applies.

The following documents are indispensable for the application of the CityGML standard. The geometry model of GML 3.1.1 is used except for some added concepts like implicit geometries (cf. chapter 8.2). The appearance model (cf. chapter 9) draws concepts from both _X3D_ and _COLLADA_. Addresses are represented using the OASIS extensible Address Language _xAL_.

* ISO / TC154: ISO 8601:2004, Data elements and interchange formats – Information interchange – Representation of dates and times
* ISO / TC211: ISO/TS 19103:2005, Geographic Information – Conceptual Schema Language
* ISO / TC211: ISO 19105:2000, Geographic information – Conformance and testing
* ISO / TC211: ISO 19107:2003, Geographic Information – Spatial Schema
* ISO / TC211: ISO 19109:2005, Geographic Information – Rules for Application Schemas
* ISO / TC211: ISO 19111:2003, Geographic information – Spatial referencing by coordinates
* ISO / TC211: ISO 19115:2003, Geographic Information – Metadata
* ISO / TC211: ISO 19123:2005, Geographic Information – Coverages
* ISO / TC211: ISO/TS 19139:2007, Geographic Information – Metadata – XML schema implementation
* ISO / TC211: ISO/IEC 19775:2004, X3D Abstract Specification
* OGC: OpenGIS® Abstract Specification Topic 0, Overview, OGC document 04-084
* OGC: OpenGIS® Abstract Specification Topic 5, The OpenGIS Feature, OGC document 99-105r2
* OGC: OpenGIS® Abstract Specification Topic 8, Relations between Features, OGC document 99-108r2
* OGC: OpenGIS® Abstract Specification Topic 10, Feature Collections, OGC document 99-110
* OGC: OpenGIS® Geography Markup Language Implementation Specification, Version 3.1.1, OGC document 03-105r1
* OGC: OpenGIS® GML 3.1.1 Simple Dictionary Profile, Version 1.0.0, OGC document 05-099r2
* IETF: IETF RFC 2045 & 2046, Multipurpose Internet Mail Extensions (MIME). (November 1996)
* IETF: IETF RFC 2396, Uniform Resource Identifiers (URI): Generic Syntax. (August 1998)
* W3C: W3C XLink, XML Linking Language (XLink) Version 1.0. W3C Recommendation (27 June 2001)
* W3C: W3C XMLName, Namespaces in XML. W3C Recommendation (14 January 1999)
* W3C: W3C XMLSchema-1, XML Schema Part 1: Structures. W3C Recommendation (2 May 2001)
* W3C: W3C XMLSchema-2, XML Schema Part 2: Datatypes. W3C Recommendation (2 May 2001)
* W3C: W3C XPointer, XML Pointer Language (XPointer) Version 1.0. W3C Working Draft (16 August 2002)
* W3C: W3C XML Base, XML Base, W3C Recommendation (27 June 2001)
* W3C: W3C XML, Extensible Markup Language (XML) 1.0 (Second Edition), W3C Recommendation (6 October 2000)
* OASIS (Organization for the Advancement of Structured Information Standards): extensible Address Language (xAL v2.0).
* Khronos Group Inc.: COLLADA – Digital Asset Schema Release 1.4.1
* Jelliffe, R: The Schematron Assertion Language 1.5. (2002-10-01)
