[[Bridge-package]]
==== *Bridge Package*

|====
|*Package Bridge*
|Description:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}The Bridge module supports representation of thematic and spatial aspects of bridges, bridge parts, bridge installations, and interior bridge structures. +
Stereotype:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}«ApplicationSchema» +
Parent Package: {nbsp}{nbsp}CityGML
|====

[[AbstractBridge-section]]
==== *Class AbstractBridge*

include::../requirements/Bridge/REQ_Bridge_AbstractBridge.adoc[]

|====
|*Class AbstractBridge* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} AbstractBridge is an abstract superclass representing the common attributes and associations of the classes Bridge and BridgePart. +
Subclass Of: {nbsp}{nbsp} <<AbstractConstruction-section,AbstractConstruction>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «FeatureType»
|*Relations* 
|Relation Name: {nbsp}{nbsp} bridgeRoom +
Cardinality:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  * +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} <<BridgeRoom-section,BridgeRoom>>  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Relates the rooms to the Bridge or BridgePart. +
|Relation Name: {nbsp}{nbsp} address +
Cardinality:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  * +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} <<Address-section,Address>>  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Relates the addresses to the Bridge or BridgePart. +
|Relation Name: {nbsp}{nbsp} bridgeConstructiveElement +
Cardinality:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  * +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} <<BridgeConstructiveElement-section,BridgeConstructiveElement>>  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Relates the constructive elements to the Bridge or BridgePart. +
|Relation Name: {nbsp}{nbsp} bridgeInstallation +
Cardinality:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  * +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} <<BridgeInstallation-section,BridgeInstallation>>  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Relates the installation objects to the Bridge or BridgePart. +
|Relation Name: {nbsp}{nbsp} bridgeFurniture +
Cardinality:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  * +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} <<BridgeFurniture-section,BridgeFurniture>>  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Relates the furniture objects to the Bridge or BridgePart. +
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}class +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} BridgeClassValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Indicates the specific type of the Bridge or BridgePart.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}function +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} BridgeFunctionValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Specifies the intended purposes of the Bridge or BridgePart.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}isMovable +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Boolean +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Indicates whether the Bridge or BridgePart can be moved to allow for watercraft to pass.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}usage +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} BridgeUsageValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Specifies the actual uses of the Bridge or BridgePart.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|
|==== 

[[Bridge-section]]
==== *Class Bridge*

include::../requirements/Bridge/REQ_Bridge_Bridge.adoc[]

|====
|*Class Bridge* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} A Bridge represents a structure that affords the passage of pedestrians, animals, vehicles, and service(s) above obstacles or between two points at a height above ground. [cf. ISO 6707-1] +
Subclass Of: {nbsp}{nbsp} <<AbstractBridge-section,AbstractBridge>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «TopLevelFeatureType»
|*Relations* 
|Relation Name: {nbsp}{nbsp} bridgePart +
Cardinality:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  * +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} <<BridgePart-section,BridgePart>>  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Relates to the bridge parts. +
|*Attributes*
|
|==== 

[[BridgeClassValue-section]]
==== *Class BridgeClassValue*

include::../requirements/Bridge/REQ_Bridge_BridgeClassValue.adoc[]

|====
|*Class BridgeClassValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} BridgeClassValue is a code list used to further classify a Bridge. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[BridgeConstructiveElement-section]]
==== *Class BridgeConstructiveElement*

include::../requirements/Bridge/REQ_Bridge_BridgeConstructiveElement.adoc[]

|====
|*Class BridgeConstructiveElement* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} A BridgeConstructiveElement is an element of a bridge which is essential from a structural point of view. Examples are pylons, anchorages, slabs, beams. +
Subclass Of: {nbsp}{nbsp} <<AbstractConstructiveElement-section,AbstractConstructiveElement>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «FeatureType»
|*Relations* 
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}class +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} BridgeConstructiveElementClassValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Indicates the specific type of the BridgeConstructiveElement.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}function +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} BridgeConstructiveElementFunctionValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Specifies the intended purposes of the BridgeConstructiveElement.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}usage +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} BridgeConstructiveElementUsageValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Specifies the actual uses of the BridgeConstructiveElement.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|
|==== 

[[BridgeConstructiveElementClassValue-section]]
==== *Class BridgeConstructiveElementClassValue*

include::../requirements/Bridge/REQ_Bridge_BridgeConstructiveElementClassValue.adoc[]

|====
|*Class BridgeConstructiveElementClassValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} BridgeConstructiveElementClassValue is a code list used to further classify a BridgeConstructiveElement. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[BridgeConstructiveElementFunctionValue-section]]
==== *Class BridgeConstructiveElementFunctionValue*

include::../requirements/Bridge/REQ_Bridge_BridgeConstructiveElementFunctionValue.adoc[]

|====
|*Class BridgeConstructiveElementFunctionValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} BridgeConstructiveElementFunctionValue is a code list that enumerates the different purposes of a BridgeConstructiveElement. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[BridgeConstructiveElementUsageValue-section]]
==== *Class BridgeConstructiveElementUsageValue*

include::../requirements/Bridge/REQ_Bridge_BridgeConstructiveElementUsageValue.adoc[]

|====
|*Class BridgeConstructiveElementUsageValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} BridgeConstructiveElementUsageValue is a code list that enumerates the different uses of a BridgeConstructiveElement. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[BridgeFunctionValue-section]]
==== *Class BridgeFunctionValue*

include::../requirements/Bridge/REQ_Bridge_BridgeFunctionValue.adoc[]

|====
|*Class BridgeFunctionValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} BridgeFunctionValue is a code list that enumerates the different purposes of a Bridge. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[BridgeFurniture-section]]
==== *Class BridgeFurniture*

include::../requirements/Bridge/REQ_Bridge_BridgeFurniture.adoc[]

|====
|*Class BridgeFurniture* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} A BridgeFurniture is an equipment for occupant use, usually not fixed to the bridge. [cf. ISO 6707-1] +
Subclass Of: {nbsp}{nbsp} <<AbstractFurniture-section,AbstractFurniture>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «FeatureType»
|*Relations* 
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}class +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} BridgeFurnitureClassValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Indicates the specific type of the BridgeFurniture.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}function +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} BridgeFurnitureFunctionValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Specifies the intended purposes of the BridgeFurniture.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}usage +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} BridgeFurnitureUsageValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Specifies the actual uses of the BridgeFurniture.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|
|==== 

[[BridgeFurnitureClassValue-section]]
==== *Class BridgeFurnitureClassValue*

include::../requirements/Bridge/REQ_Bridge_BridgeFurnitureClassValue.adoc[]

|====
|*Class BridgeFurnitureClassValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} BridgeFurnitureClassValue is a code list used to further classify a BridgeFurniture. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[BridgeFurnitureFunctionValue-section]]
==== *Class BridgeFurnitureFunctionValue*

include::../requirements/Bridge/REQ_Bridge_BridgeFurnitureFunctionValue.adoc[]

|====
|*Class BridgeFurnitureFunctionValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} BridgeFurnitureFunctionValue is a code list that enumerates the different purposes of a BridgeFurniture. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[BridgeFurnitureUsageValue-section]]
==== *Class BridgeFurnitureUsageValue*

include::../requirements/Bridge/REQ_Bridge_BridgeFurnitureUsageValue.adoc[]

|====
|*Class BridgeFurnitureUsageValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} BridgeFurnitureUsageValue is a code list that enumerates the different uses of a BridgeFurniture. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[BridgeInstallation-section]]
==== *Class BridgeInstallation*

include::../requirements/Bridge/REQ_Bridge_BridgeInstallation.adoc[]

|====
|*Class BridgeInstallation* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} A BridgeInstallation is a permanent part of a Bridge (inside and/or outside) which does not have the significance of a BridgePart. In contrast to BridgeConstructiveElements, a BridgeInstallation is not essential from a structural point of view. Examples are stairs, antennas or railways. +
Subclass Of: {nbsp}{nbsp} <<AbstractInstallation-section,AbstractInstallation>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «FeatureType»
|*Relations* 
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}class +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} BridgeInstallationClassValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Indicates the specific type of the BridgeInstallation.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}function +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} BridgeInstallationFunctionValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Specifies the intended purposes of the BridgeInstallation.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}usage +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} BridgeInstallationUsageValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Specifies the actual uses of the BridgeInstallation.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|
|==== 

[[BridgeInstallationClassValue-section]]
==== *Class BridgeInstallationClassValue*

include::../requirements/Bridge/REQ_Bridge_BridgeInstallationClassValue.adoc[]

|====
|*Class BridgeInstallationClassValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} BridgeInstallationClassValue is a code list used to further classify a BridgeInstallation. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[BridgeInstallationFunctionValue-section]]
==== *Class BridgeInstallationFunctionValue*

include::../requirements/Bridge/REQ_Bridge_BridgeInstallationFunctionValue.adoc[]

|====
|*Class BridgeInstallationFunctionValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} BridgeInstallationFunctionValue is a code list that enumerates the different purposes of a BridgeInstallation. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[BridgeInstallationUsageValue-section]]
==== *Class BridgeInstallationUsageValue*

include::../requirements/Bridge/REQ_Bridge_BridgeInstallationUsageValue.adoc[]

|====
|*Class BridgeInstallationUsageValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} BridgeInstallationUsageValue is a code list that enumerates the different uses of a BridgeInstallation. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[BridgePart-section]]
==== *Class BridgePart*

include::../requirements/Bridge/REQ_Bridge_BridgePart.adoc[]

|====
|*Class BridgePart* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} A BridgePart is a physical or functional subdivision of a Bridge. It would be considered a Bridge, if it were not part of a collection of other BridgeParts. +
Subclass Of: {nbsp}{nbsp} <<AbstractBridge-section,AbstractBridge>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «FeatureType»
|*Relations* 
|*Attributes*
|
|==== 

[[BridgeRoom-section]]
==== *Class BridgeRoom*

include::../requirements/Bridge/REQ_Bridge_BridgeRoom.adoc[]

|====
|*Class BridgeRoom* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} A BridgeRoom is a space within a Bridge or BridgePart intended for human occupancy (e.g. a place of work or recreation) and/or containment (storage) of animals or things. A BridgeRoom is bounded physically and/or virtually (e.g. by ClosureSurfaces or GenericSurfaces). +
Subclass Of: {nbsp}{nbsp} <<AbstractUnoccupiedSpace-section,AbstractUnoccupiedSpace>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «FeatureType»
|*Relations* 
|Relation Name: {nbsp}{nbsp} bridgeInstallation +
Cardinality:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  * +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} <<BridgeInstallation-section,BridgeInstallation>>  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Relates to the installation objects. +
|Relation Name: {nbsp}{nbsp} boundary +
Cardinality:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  * +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} <<AbstractThematicSurface-section,AbstractThematicSurface>>  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
|Relation Name: {nbsp}{nbsp} bridgeFurniture +
Cardinality:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  * +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} <<BridgeFurniture-section,BridgeFurniture>>  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Relates to the furniture objects. +
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}class +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} BridgeRoomClassValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Indicates the specific type of the BridgeRoom.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}function +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} BridgeRoomFunctionValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Specifies the intended purposes of the BridgeRoom.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}usage +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} BridgeRoomUsageValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Specifies the actual uses of the BridgeRoom.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|
|==== 

[[BridgeRoomClassValue-section]]
==== *Class BridgeRoomClassValue*

include::../requirements/Bridge/REQ_Bridge_BridgeRoomClassValue.adoc[]

|====
|*Class BridgeRoomClassValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} BridgeRoomClassValue is a code list used to further classify a BridgeRoom. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[BridgeRoomFunctionValue-section]]
==== *Class BridgeRoomFunctionValue*

include::../requirements/Bridge/REQ_Bridge_BridgeRoomFunctionValue.adoc[]

|====
|*Class BridgeRoomFunctionValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} BridgeRoomFunctionValue is a code list that enumerates the different purposes of a BridgeRoom. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[BridgeRoomUsageValue-section]]
==== *Class BridgeRoomUsageValue*

include::../requirements/Bridge/REQ_Bridge_BridgeRoomUsageValue.adoc[]

|====
|*Class BridgeRoomUsageValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} BridgeRoomUsageValue is a code list that enumerates the different uses of a BridgeRoom. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[BridgeUsageValue-section]]
==== *Class BridgeUsageValue*

include::../requirements/Bridge/REQ_Bridge_BridgeUsageValue.adoc[]

|====
|*Class BridgeUsageValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} BridgeUsageValue is a code list that enumerates the different uses of a Bridge. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 
  


