[[Bridge-package]]
==== *Bridge Package*

|====
|*Package Bridge*
|Description:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} +
Stereotype:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}«ApplicationSchema» +
Parent Package: {nbsp}{nbsp}CityGML
|====

[[AbstractBridge-section]]
==== *Class AbstractBridge*

include::../requirements/Bridge/REQ_Bridge_AbstractBridge.adoc[]

|====
|*Class AbstractBridge*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subclass Of: {nbsp}{nbsp} <<AbstractConstruction-section,AbstractConstruction>> +
StereoType:{nbsp}{nbsp} «FeatureType»
|*Roles* 
|Role Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} bridgeRoom +
Cardinality:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  * +
Target Class: {nbsp}{nbsp}{nbsp} <<BridgeRoom-section,BridgeRoom>>  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} SIG3D: Relation between Bridge or BridgePart and BridgeRoom +
|Role Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} address +
Cardinality:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  * +
Target Class: {nbsp}{nbsp}{nbsp} <<Address-section,Address>>  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} SIG3D: Relation between Bridge or BridgePart and Address +
|Role Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} bridgeConstructiveElement +
Cardinality:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  * +
Target Class: {nbsp}{nbsp}{nbsp} <<BridgeConstructiveElement-section,BridgeConstructiveElement>>  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} SIG3D: Relation between Bridge or BridgePart and BridgeConstructionElement +
|Role Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} bridgeInstallation +
Cardinality:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  * +
Target Class: {nbsp}{nbsp}{nbsp} <<BridgeInstallation-section,BridgeInstallation>>  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} SIG3D: Relation between Bridge or BridgePart and BridgeInstallation +
|Role Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} bridgeFurniture +
Cardinality:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  * +
Target Class: {nbsp}{nbsp}{nbsp} <<BridgeFurniture-section,BridgeFurniture>>  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}class +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} BridgeClassValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} SIG3D: Classification of the actual usage of Bridge or BridgePart as given by the relevant national regulations, information communities, or specific applications.   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}function +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} BridgeFunctionValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} SIG3D: Specified function of Bridge or BridgePart as given by the relevant national regulations, information communities, or specific applications.   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}isMovable +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Boolean +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} SIG3D: Indicates wether a bridge is movable to allow passages for ships (e.g. turnable bridge, liftable bridge)  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}usage +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} BridgeUsageValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} SIG3D: Actual usage of Bridge or BridgePart as given by the relevant national regulations, information communities, or specific applications.   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|
|==== 

[[Bridge-section]]
==== *Class Bridge*

include::../requirements/Bridge/REQ_Bridge_Bridge.adoc[]

|====
|*Class Bridge*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subclass Of: {nbsp}{nbsp} <<AbstractBridge-section,AbstractBridge>> +
StereoType:{nbsp}{nbsp} «TopLevelFeatureType»
|*Roles* 
|Role Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} bridgePart +
Cardinality:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  * +
Target Class: {nbsp}{nbsp}{nbsp} <<BridgePart-section,BridgePart>>  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Relation between Bridge and BridgePart. +
|*Attributes*
|
|==== 

[[BridgeClassValue-section]]
==== *Class BridgeClassValue*

include::../requirements/Bridge/REQ_Bridge_BridgeClassValue.adoc[]

|====
|*Class BridgeClassValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|*Roles* 
|*Attributes*
|
|==== 

[[BridgeConstructiveElement-section]]
==== *Class BridgeConstructiveElement*

include::../requirements/Bridge/REQ_Bridge_BridgeConstructiveElement.adoc[]

|====
|*Class BridgeConstructiveElement*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subclass Of: {nbsp}{nbsp} <<AbstractConstructiveElement-section,AbstractConstructiveElement>> +
StereoType:{nbsp}{nbsp} «FeatureType»
|*Roles* 
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}class +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} BridgeConstructiveElementClassValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} SIG3D: Classification of BridgeConstructionElement as given by the relevant national regulations, information communities, or specific applications.   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}function +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} BridgeConstructiveElementFunctionValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} SIG3D: Specified function of BridgeConstructionElement as given by the relevant national regulations, information communities, or specific applications.   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}usage +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} BridgeConstructiveElementUsageValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} SIG3D: Actual usage of BridgeConstructionElement as given by the relevant national regulations, information communities, or specific applications.   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|
|==== 

[[BridgeConstructiveElementClassValue-section]]
==== *Class BridgeConstructiveElementClassValue*

include::../requirements/Bridge/REQ_Bridge_BridgeConstructiveElementClassValue.adoc[]

|====
|*Class BridgeConstructiveElementClassValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|*Roles* 
|*Attributes*
|
|==== 

[[BridgeConstructiveElementFunctionValue-section]]
==== *Class BridgeConstructiveElementFunctionValue*

include::../requirements/Bridge/REQ_Bridge_BridgeConstructiveElementFunctionValue.adoc[]

|====
|*Class BridgeConstructiveElementFunctionValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|*Roles* 
|*Attributes*
|
|==== 

[[BridgeConstructiveElementUsageValue-section]]
==== *Class BridgeConstructiveElementUsageValue*

include::../requirements/Bridge/REQ_Bridge_BridgeConstructiveElementUsageValue.adoc[]

|====
|*Class BridgeConstructiveElementUsageValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|*Roles* 
|*Attributes*
|
|==== 

[[BridgeFunctionValue-section]]
==== *Class BridgeFunctionValue*

include::../requirements/Bridge/REQ_Bridge_BridgeFunctionValue.adoc[]

|====
|*Class BridgeFunctionValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|*Roles* 
|*Attributes*
|
|==== 

[[BridgeFurniture-section]]
==== *Class BridgeFurniture*

include::../requirements/Bridge/REQ_Bridge_BridgeFurniture.adoc[]

|====
|*Class BridgeFurniture*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subclass Of: {nbsp}{nbsp} <<AbstractFurniture-section,AbstractFurniture>> +
StereoType:{nbsp}{nbsp} «FeatureType»
|*Roles* 
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}class +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} BridgeFurnitureClassValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} SIG3D: Classification of BridgeFurniture as given by the relevant national regulations, information communities, or specific applications.   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}function +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} BridgeFurnitureFunctionValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} SIG3D: Specified function of BridgeFurniture as given by the relevant national regulations, information communities, or specific applications.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}usage +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} BridgeFurnitureUsageValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} SIG3D: Actual usage of BridgeFurniture as given by the relevant national regulations, information communities, or specific applications.   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|
|==== 

[[BridgeFurnitureClassValue-section]]
==== *Class BridgeFurnitureClassValue*

include::../requirements/Bridge/REQ_Bridge_BridgeFurnitureClassValue.adoc[]

|====
|*Class BridgeFurnitureClassValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|*Roles* 
|*Attributes*
|
|==== 

[[BridgeFurnitureFunctionValue-section]]
==== *Class BridgeFurnitureFunctionValue*

include::../requirements/Bridge/REQ_Bridge_BridgeFurnitureFunctionValue.adoc[]

|====
|*Class BridgeFurnitureFunctionValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|*Roles* 
|*Attributes*
|
|==== 

[[BridgeFurnitureUsageValue-section]]
==== *Class BridgeFurnitureUsageValue*

include::../requirements/Bridge/REQ_Bridge_BridgeFurnitureUsageValue.adoc[]

|====
|*Class BridgeFurnitureUsageValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|*Roles* 
|*Attributes*
|
|==== 

[[BridgeInstallation-section]]
==== *Class BridgeInstallation*

include::../requirements/Bridge/REQ_Bridge_BridgeInstallation.adoc[]

|====
|*Class BridgeInstallation*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subclass Of: {nbsp}{nbsp} <<AbstractInstallation-section,AbstractInstallation>> +
StereoType:{nbsp}{nbsp} «FeatureType»
|*Roles* 
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}class +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} BridgeInstallationClassValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} SIG3D: Classification of BridgeInstallation as given by the relevant national regulations, information communities, or specific applications.   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}function +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} BridgeInstallationFunctionValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} SIG3D: Specified function of BridgeInstallation as given by the relevant national regulations, information communities, or specific applications.   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}usage +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} BridgeInstallationUsageValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} SIG3D: Actual usage of BridgeInstallation as given by the relevant national regulations, information communities, or specific applications.   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|
|==== 

[[BridgeInstallationClassValue-section]]
==== *Class BridgeInstallationClassValue*

include::../requirements/Bridge/REQ_Bridge_BridgeInstallationClassValue.adoc[]

|====
|*Class BridgeInstallationClassValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|*Roles* 
|*Attributes*
|
|==== 

[[BridgeInstallationFunctionValue-section]]
==== *Class BridgeInstallationFunctionValue*

include::../requirements/Bridge/REQ_Bridge_BridgeInstallationFunctionValue.adoc[]

|====
|*Class BridgeInstallationFunctionValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|*Roles* 
|*Attributes*
|
|==== 

[[BridgeInstallationUsageValue-section]]
==== *Class BridgeInstallationUsageValue*

include::../requirements/Bridge/REQ_Bridge_BridgeInstallationUsageValue.adoc[]

|====
|*Class BridgeInstallationUsageValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|*Roles* 
|*Attributes*
|
|==== 

[[BridgePart-section]]
==== *Class BridgePart*

include::../requirements/Bridge/REQ_Bridge_BridgePart.adoc[]

|====
|*Class BridgePart*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subclass Of: {nbsp}{nbsp} <<AbstractBridge-section,AbstractBridge>> +
StereoType:{nbsp}{nbsp} «FeatureType»
|*Roles* 
|*Attributes*
|
|==== 

[[BridgeRoom-section]]
==== *Class BridgeRoom*

include::../requirements/Bridge/REQ_Bridge_BridgeRoom.adoc[]

|====
|*Class BridgeRoom*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subclass Of: {nbsp}{nbsp} <<AbstractUnoccupiedSpace-section,AbstractUnoccupiedSpace>> +
StereoType:{nbsp}{nbsp} «FeatureType»
|*Roles* 
|Role Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} bridgeInstallation +
Cardinality:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  * +
Target Class: {nbsp}{nbsp}{nbsp} <<BridgeInstallation-section,BridgeInstallation>>  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} SIG3D: Relation between BridgeRoom and BridgegInstallation +
|Role Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} boundary +
Cardinality:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  * +
Target Class: {nbsp}{nbsp}{nbsp} <<AbstractThematicSurface-section,AbstractThematicSurface>>  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
|Role Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} bridgeFurniture +
Cardinality:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  * +
Target Class: {nbsp}{nbsp}{nbsp} <<BridgeFurniture-section,BridgeFurniture>>  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} SIG3D: Relation between BridgeRoom and BridgeFurniture +
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}class +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} BridgeRoomClassValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} SIG3D: Classification of BridgeRoom as given by the relevant national regulations, information communities, or specific applications.   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}function +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} BridgeRoomFunctionValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} SIG3D: Specified function of BridgeRoom as given by the relevant national regulations, information communities, or specific applications.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}usage +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} BridgeRoomUsageValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} SIG3D: Actual usage of BridgeRoom as given by the relevant national regulations, information communities, or specific applications.   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|
|==== 

[[BridgeRoomClassValue-section]]
==== *Class BridgeRoomClassValue*

include::../requirements/Bridge/REQ_Bridge_BridgeRoomClassValue.adoc[]

|====
|*Class BridgeRoomClassValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|*Roles* 
|*Attributes*
|
|==== 

[[BridgeRoomFunctionValue-section]]
==== *Class BridgeRoomFunctionValue*

include::../requirements/Bridge/REQ_Bridge_BridgeRoomFunctionValue.adoc[]

|====
|*Class BridgeRoomFunctionValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|*Roles* 
|*Attributes*
|
|==== 

[[BridgeRoomUsageValue-section]]
==== *Class BridgeRoomUsageValue*

include::../requirements/Bridge/REQ_Bridge_BridgeRoomUsageValue.adoc[]

|====
|*Class BridgeRoomUsageValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|*Roles* 
|*Attributes*
|
|==== 

[[BridgeUsageValue-section]]
==== *Class BridgeUsageValue*

include::../requirements/Bridge/REQ_Bridge_BridgeUsageValue.adoc[]

|====
|*Class BridgeUsageValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|*Roles* 
|*Attributes*
|
|==== 
  


