[[Building-package-dd]]
==== *Package*

[cols="1a"]
|===
|{set:cellbgcolor:#FFFFFF} *Package Building*
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Description: ! The Building module supports representation of thematic and spatial aspects of buildings, building parts, building installations, building subdivisions, and interior building structures. 
!{nbsp}{nbsp}{nbsp}{nbsp}Parent Package: ! CityGML
!{nbsp}{nbsp}{nbsp}{nbsp}Stereotype: ! «ApplicationSchema»
!===
|===

==== *Classes*

[[AbstractBuilding-section]]
===== *Class AbstractBuilding*

[cols="1a"]
|===
|*AbstractBuilding* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! AbstractBuilding is an abstract superclass representing the common attributes and associations of the classes Building and BuildingPart. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractConstruction-section,AbstractConstruction>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!{set:cellbgcolor:#FFFFFF} buildingConstructiveElement 
!<<BuildingConstructiveElement-section,BuildingConstructiveElement>> 
 [*]
!
!{set:cellbgcolor:#FFFFFF} address 
!<<Address-section,Address>> 
 [*]
!
!{set:cellbgcolor:#FFFFFF} buildingSubdivision 
!<<AbstractBuildingSubdivision-section,AbstractBuildingSubdivision>> 
 [*]
!
!{set:cellbgcolor:#FFFFFF} buildingFurniture 
!<<BuildingFurniture-section,BuildingFurniture>> 
 [*]
!
!{set:cellbgcolor:#FFFFFF} buildingRoom 
!<<BuildingRoom-section,BuildingRoom>> 
 [*]
!
!{set:cellbgcolor:#FFFFFF} buildingInstallation 
!<<BuildingInstallation-section,BuildingInstallation>> 
 [*]
!
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} class  !<<BuildingClassValue-section,BuildingClassValue>>  [0..1] !Indicates the specific type of the Building or BuildingPart.
 
!{set:cellbgcolor:#FFFFFF} function  !<<BuildingFunctionValue-section,BuildingFunctionValue>>  [0..*] !Specifies the intended purposes of the Building or BuildingPart.
 
!{set:cellbgcolor:#FFFFFF} roofType  !<<RoofTypeValue-section,RoofTypeValue>>  [0..1] !Indicates the shape of the roof of the Building or BuildingPart.
 
!{set:cellbgcolor:#FFFFFF} storeyHeightsAboveGround  !<<MeasureOrNilReasonList-section,MeasureOrNilReasonList>>  [0..1] !Lists the heights of each storey above ground. The first value in the list denotes the height of the storey closest to the ground level, the last value denotes the height furthest away.
 
!{set:cellbgcolor:#FFFFFF} storeyHeightsBelowGround  !<<MeasureOrNilReasonList-section,MeasureOrNilReasonList>>  [0..1] !Lists the height of each storey below ground. The first value in the list denotes the height of the storey closest to the ground level, the last value denotes the height furthest away.
 
!{set:cellbgcolor:#FFFFFF} storeysAboveGround  !<<Integer-section,Integer>>  [0..1] !Indicates the number of storeys positioned above ground level.
 
!{set:cellbgcolor:#FFFFFF} storeysBelowGround  !<<Integer-section,Integer>>  [0..1] !Indicates the number of storeys positioned below ground level.
 
!{set:cellbgcolor:#FFFFFF} usage  !<<BuildingUsageValue-section,BuildingUsageValue>>  [0..*] !Specifies the actual uses of the Building or BuildingPart.
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[AbstractBuildingSubdivision-section]]
===== *Class AbstractBuildingSubdivision*

[cols="1a"]
|===
|*AbstractBuildingSubdivision* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! AbstractBuildingSubdivision is the abstract superclass for different kinds of logical building subdivisions. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractLogicalSpace-section,AbstractLogicalSpace>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!{set:cellbgcolor:#FFFFFF} buildingInstallation 
!<<BuildingInstallation-section,BuildingInstallation>> 
 [*]
!
!{set:cellbgcolor:#FFFFFF} buildingFurniture 
!<<BuildingFurniture-section,BuildingFurniture>> 
 [*]
!
!{set:cellbgcolor:#FFFFFF} buildingRoom 
!<<BuildingRoom-section,BuildingRoom>> 
 [*]
!
!{set:cellbgcolor:#FFFFFF} buildingConstructiveElement 
!<<BuildingConstructiveElement-section,BuildingConstructiveElement>> 
 [*]
!
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} class  !<<BuildingSubdivisionClassValue-section,BuildingSubdivisionClassValue>>  [0..1] !Indicates the specific type of the building subdivision.
 
!{set:cellbgcolor:#FFFFFF} elevation  !<<Elevation-section,Elevation>>  [0..*] !Specifies qualified elevations of the building subdivision in relation to a well-defined surface which is commonly taken as origin (e.g. geoid or water level). [cf. INSPIRE]
 
!{set:cellbgcolor:#FFFFFF} function  !<<BuildingSubdivisionFunctionValue-section,BuildingSubdivisionFunctionValue>>  [0..*] !Specifies the intended purposes of the building subdivision.
 
!{set:cellbgcolor:#FFFFFF} sortKey  !<<Real-section,Real>>  [0..1] !Defines an order among the objects that belong to the building subdivision. An example is the sorting of storeys.
 
!{set:cellbgcolor:#FFFFFF} usage  !<<BuildingSubdivisionUsageValue-section,BuildingSubdivisionUsageValue>>  [0..*] !Specifies the actual uses of the building subdivision.
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[Building-section]]
===== *Class Building*

[cols="1a"]
|===
|*Building* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A Building is a free-standing, self-supporting construction that is roofed, usually walled, and can be entered by humans and is normally designed to stand permanently in one place. It is intended for human occupancy (e.g. a place of work or recreation), habitation and/or shelter of humans, animals or things. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractBuilding-section,AbstractBuilding>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «TopLevelFeatureType»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!{set:cellbgcolor:#FFFFFF} buildingPart 
!<<BuildingPart-section,BuildingPart>> 
 [*]
!
!===
|=== 

[[BuildingClassValue-section]]
===== *Class BuildingClassValue*

[cols="1a"]
|===
|*BuildingClassValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! BuildingClassValue is a code list used to further classify a Building. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[BuildingConstructiveElement-section]]
===== *Class BuildingConstructiveElement*

[cols="1a"]
|===
|*BuildingConstructiveElement* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A BuildingConstructiveElement is an element of a Building which is essential from a structural point of view. Examples are walls, slabs, staircases, beams. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractConstructiveElement-section,AbstractConstructiveElement>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} class  !<<BuildingConstructiveElementClassValue-section,BuildingConstructiveElementClassValue>>  [0..1] !Indicates the specific type of the BuildingConstructiveElement.
 
!{set:cellbgcolor:#FFFFFF} function  !<<BuildingConstructiveElementFunctionValue-section,BuildingConstructiveElementFunctionValue>>  [0..*] !Specifies the intended purposes of the BuildingConstructiveElement.
 
!{set:cellbgcolor:#FFFFFF} usage  !<<BuildingConstructiveElementUsageValue-section,BuildingConstructiveElementUsageValue>>  [0..*] !Specifies the actual uses of the BuildingConstructiveElement.
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[BuildingConstructiveElementClassValue-section]]
===== *Class BuildingConstructiveElementClassValue*

[cols="1a"]
|===
|*BuildingConstructiveElementClassValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! BuildingConstructiveElementClassValue is a code list used to further classify a BuildingConstructiveElement. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[BuildingConstructiveElementFunctionValue-section]]
===== *Class BuildingConstructiveElementFunctionValue*

[cols="1a"]
|===
|*BuildingConstructiveElementFunctionValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! BuildingConstructiveElementFunctionValue is a code list that enumerates the different purposes of a BuildingConstructiveElement. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[BuildingConstructiveElementUsageValue-section]]
===== *Class BuildingConstructiveElementUsageValue*

[cols="1a"]
|===
|*BuildingConstructiveElementUsageValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! BuildingConstructiveElementUsageValue is a code list that enumerates the different uses of a BuildingConstructiveElement. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[BuildingFunctionValue-section]]
===== *Class BuildingFunctionValue*

[cols="1a"]
|===
|*BuildingFunctionValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! BuildingFunctionValue is a code list that enumerates the different purposes of a Building. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[BuildingFurniture-section]]
===== *Class BuildingFurniture*

[cols="1a"]
|===
|*BuildingFurniture* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A BuildingFurniture is an equipment for occupant use, usually not fixed to the building. [cf. ISO 6707-1] 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractFurniture-section,AbstractFurniture>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} class  !<<BuildingFurnitureClassValue-section,BuildingFurnitureClassValue>>  [0..1] !Indicates the specific type of the BuildingFurniture.
 
!{set:cellbgcolor:#FFFFFF} function  !<<BuildingFurnitureFunctionValue-section,BuildingFurnitureFunctionValue>>  [0..*] !Specifies the intended purposes of the BuildingFurniture.
 
!{set:cellbgcolor:#FFFFFF} usage  !<<BuildingFurnitureUsageValue-section,BuildingFurnitureUsageValue>>  [0..*] !Specifies the actual uses of the BuildingFurniture.
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[BuildingFurnitureClassValue-section]]
===== *Class BuildingFurnitureClassValue*

[cols="1a"]
|===
|*BuildingFurnitureClassValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! BuildingFurnitureClassValue is a code list used to further classify a BuildingFurniture. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
!===
|=== 

[[BuildingFurnitureFunctionValue-section]]
===== *Class BuildingFurnitureFunctionValue*

[cols="1a"]
|===
|*BuildingFurnitureFunctionValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! BuildingFurnitureFunctionValue is a code list that enumerates the different purposes of a BuildingFurniture. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[BuildingFurnitureUsageValue-section]]
===== *Class BuildingFurnitureUsageValue*

[cols="1a"]
|===
|*BuildingFurnitureUsageValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! BuildingFurnitureUsageValue is a code list that enumerates the different uses of a BuildingFurniture. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[BuildingInstallation-section]]
===== *Class BuildingInstallation*

[cols="1a"]
|===
|*BuildingInstallation* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A BuildingInstallation is a permanent part of a Building (inside and/or outside) which has not the significance of a BuildingPart. Examples are stairs, antennas, balconies or small roofs. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractInstallation-section,AbstractInstallation>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} class  !<<BuildingInstallationClassValue-section,BuildingInstallationClassValue>>  [0..1] !Indicates the specific type of the BuildingInstallation.
 
!{set:cellbgcolor:#FFFFFF} function  !<<BuildingInstallationFunctionValue-section,BuildingInstallationFunctionValue>>  [0..*] !Specifies the intended purposes of the BuildingInstallation.
 
!{set:cellbgcolor:#FFFFFF} usage  !<<BuildingInstallationUsageValue-section,BuildingInstallationUsageValue>>  [0..*] !Specifies the actual uses of the BuildingInstallation.
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[BuildingInstallationClassValue-section]]
===== *Class BuildingInstallationClassValue*

[cols="1a"]
|===
|*BuildingInstallationClassValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! BuildingInstallationClassValue is a code list used to further classify a BuildingInstallation. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[BuildingInstallationFunctionValue-section]]
===== *Class BuildingInstallationFunctionValue*

[cols="1a"]
|===
|*BuildingInstallationFunctionValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! BuildingInstallationFunctionValue is a code list that enumerates the different purposes of a BuildingInstallation. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[BuildingInstallationUsageValue-section]]
===== *Class BuildingInstallationUsageValue*

[cols="1a"]
|===
|*BuildingInstallationUsageValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! BuildingInstallationUsageValue is a code list that enumerates the different uses of a BuildingInstallation. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[BuildingPart-section]]
===== *Class BuildingPart*

[cols="1a"]
|===
|*BuildingPart* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A BuildingPart is a physical or functional subdivision of a Building. It would be considered a Building, if it were not part of a collection of other BuildingParts. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractBuilding-section,AbstractBuilding>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
|=== 

[[BuildingRoom-section]]
===== *Class BuildingRoom*

[cols="1a"]
|===
|*BuildingRoom* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A BuildingRoom is a space within a Building or BuildingPart intended for human occupancy (e.g. a place of work or recreation) and/or containment of animals or things. A BuildingRoom is bounded physically and/or virtually (e.g. by ClosureSurfaces or GenericSurfaces). 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractUnoccupiedSpace-section,AbstractUnoccupiedSpace>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!{set:cellbgcolor:#FFFFFF} buildingFurniture 
!<<BuildingFurniture-section,BuildingFurniture>> 
 [*]
!
!{set:cellbgcolor:#FFFFFF} boundary 
!<<AbstractThematicSurface-section,AbstractThematicSurface>> 
 [*]
!
!{set:cellbgcolor:#FFFFFF} buildingInstallation 
!<<BuildingInstallation-section,BuildingInstallation>> 
 [*]
!
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} class  !<<BuildingRoomClassValue-section,BuildingRoomClassValue>>  [0..1] !Indicates the specific type of the BuildingRoom.
 
!{set:cellbgcolor:#FFFFFF} function  !<<BuildingRoomFunctionValue-section,BuildingRoomFunctionValue>>  [0..*] !Specifies the intended purposes of the BuildingRoom.
 
!{set:cellbgcolor:#FFFFFF} roomHeight  !<<RoomHeight-section,RoomHeight>>  [0..*] !Specifies qualified heights of the BuildingRoom.
 
!{set:cellbgcolor:#FFFFFF} usage  !<<BuildingRoomUsageValue-section,BuildingRoomUsageValue>>  [0..*] !Specifies the actual uses of the BuildingRoom.
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[BuildingRoomClassValue-section]]
===== *Class BuildingRoomClassValue*

[cols="1a"]
|===
|*BuildingRoomClassValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! BuildingRoomClassValue is a code list used to further classify a BuildingRoom. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[BuildingRoomFunctionValue-section]]
===== *Class BuildingRoomFunctionValue*

[cols="1a"]
|===
|*BuildingRoomFunctionValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! BuildingRoomFunctionValue is a code list that enumerates the different purposes of a BuildingRoom. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[BuildingRoomUsageValue-section]]
===== *Class BuildingRoomUsageValue*

[cols="1a"]
|===
|*BuildingRoomUsageValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! BuildingRoomUsageValue is a code list that enumerates the different uses of a BuildingRoom. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[BuildingSubdivisionClassValue-section]]
===== *Class BuildingSubdivisionClassValue*

[cols="1a"]
|===
|*BuildingSubdivisionClassValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! BuildingSubdivisionClassValue is a code list used to further classify a BuildingSubdivision. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[BuildingSubdivisionFunctionValue-section]]
===== *Class BuildingSubdivisionFunctionValue*

[cols="1a"]
|===
|*BuildingSubdivisionFunctionValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! BuildingSubdivisionFunctionValue is a code list that enumerates the different purposes of a BuildingSubdivision. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[BuildingSubdivisionUsageValue-section]]
===== *Class BuildingSubdivisionUsageValue*

[cols="1a"]
|===
|*BuildingSubdivisionUsageValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! BuildingSubdivisionUsageValue is a code list that enumerates the different uses of a BuildingSubdivision. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[BuildingUnit-section]]
===== *Class BuildingUnit*

[cols="1a"]
|===
|*BuildingUnit* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A BuildingUnit is a logical subdivision of a Building. BuildingUnits are formed according to some homogeneous property like function, ownership, management, or accessability. They may be separately sold, rented out, inherited, managed, etc. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractBuildingSubdivision-section,AbstractBuildingSubdivision>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!{set:cellbgcolor:#FFFFFF} address 
!<<Address-section,Address>> 
 [*]
!
!===
|=== 

[[BuildingUsageValue-section]]
===== *Class BuildingUsageValue*

[cols="1a"]
|===
|*BuildingUsageValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! BuildingUsageValue is a code list that enumerates the different uses of a Building. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[RoofTypeValue-section]]
===== *Class RoofTypeValue*

[cols="1a"]
|===
|*RoofTypeValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! RoofTypeValue is a code list that enumerates different roof types. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[RoomElevationReferenceValue-section]]
===== *Class RoomElevationReferenceValue*

[cols="1a"]
|===
|*RoomElevationReferenceValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! RoomElevationReferenceValue is a code list that enumerates the different elevation reference levels used to measure room heights. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[Storey-section]]
===== *Class Storey*

[cols="1a"]
|===
|*Storey* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A Storey is a horizontal section of a Building. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractBuildingSubdivision-section,AbstractBuildingSubdivision>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!{set:cellbgcolor:#FFFFFF} buildingUnit 
!<<BuildingUnit-section,BuildingUnit>> 
 [*]
!
!{set:cellbgcolor:#FFFFFF} boundary 
!<<AbstractThematicSurface-section,AbstractThematicSurface>> 
 [*]
!
!===
|=== 

[[RoomHeight-section]]
===== *Class RoomHeight*

[cols="1a"]
|===
|*RoomHeight* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! The RoomHeight represents a vertical distance (measured or estimated) between a low reference and a high reference. [cf. INSPIRE] 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «DataType»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} highReference  !<<RoomElevationReferenceValue-section,RoomElevationReferenceValue>>  !Indicates the high point used to calculate the value of the room height.
 
!{set:cellbgcolor:#FFFFFF} lowReference  !<<RoomElevationReferenceValue-section,RoomElevationReferenceValue>>  !Indicates the low point used to calculate the value of the room height.
 
!{set:cellbgcolor:#FFFFFF} status  !<<HeightStatusValue-section,HeightStatusValue>>  !Indicates the way the room height has been captured.
 
!{set:cellbgcolor:#FFFFFF} value  !<<Length-section,Length>>  !Specifies the value of the room height.
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 
  


