[[CityFurniture-package]]
==== *Package*

[cols="1a"]
|===
|{set:cellbgcolor:#FFFFFF} *Package CityFurniture*
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Description: ! The CityFurniture module supports representation of city furniture objects. City furniture objects are immovable objects like lanterns, traffic signs, advertising columns, benches, or bus stops that can be found in traffic areas, residential areas, on squares, or in built-up areas. ! {nbsp}{nbsp}{nbsp}{nbsp}Parent Package: ! CityGML
! {nbsp}{nbsp}{nbsp}{nbsp}Stereotype: ! «ApplicationSchema» 
!===
|===

[[CityFurniture-section]]
==== *Classes*

===== *Class CityFurniture*

[cols="1a"]
|===
|*CityFurniture* 
|[cols="1,4",frame=none,grid=none]
!===
! {nbsp}{nbsp}{nbsp}{nbsp}Definition: ! CityFurniture is an object or piece of equipment installed in the outdoor environment for various purposes. Examples include street signs, traffic signals, street lamps, benches, fountains.
! {nbsp}{nbsp}{nbsp}{nbsp}Subclass of: ! <<AbstractOccupiedSpace-section,AbstractOccupiedSpace>> 
! {nbsp}{nbsp}{nbsp}{nbsp}StereoType: ! «TopLevelFeatureType»
!===
|*Relations*
|*Attributes* (Unless otherwise specified, all attributes have the stereotype «Property».)
|[cols="1,4",frame=none,grid=none]
!===
2+! [blue]*+++<color rgb="#0000ff">Attribute: class</color>+++*
! {nbsp}{nbsp}{nbsp}{nbsp}Name: ! class
! {nbsp}{nbsp}{nbsp}{nbsp}Value Type: ! <<CityFurnitureClassValue-section,CityFurnitureClassValue>>
! {nbsp}{nbsp}{nbsp}{nbsp}Definition: ! Indicates the specific type of the CityFurniture.
! {nbsp}{nbsp}{nbsp}{nbsp}Multiplicity: ! [0..1]
! {nbsp}{nbsp}{nbsp}{nbsp}Stereotype: ! «Property»
!===
|[cols="1,4",frame=none,grid=none]
!===
2+! [blue]*+++<color rgb="#0000ff">Attribute: function</color>+++*
! {nbsp}{nbsp}{nbsp}{nbsp}Name: ! function
! {nbsp}{nbsp}{nbsp}{nbsp}Value Type: ! <<CityFurnitureFunctionValue-section,CityFurnitureFunctionValue>>
! {nbsp}{nbsp}{nbsp}{nbsp}Definition: ! Specifies the intended purposes of the CityFurniture.
! {nbsp}{nbsp}{nbsp}{nbsp}Multiplicity: ! [0..*]
! {nbsp}{nbsp}{nbsp}{nbsp}Stereotype: ! «Property»
!===
|[cols="1,4",frame=none,grid=none]
!===
2+! [blue]*+++<color rgb="#0000ff">Attribute: usage</color>+++*
! {nbsp}{nbsp}{nbsp}{nbsp}Name: ! usage
! {nbsp}{nbsp}{nbsp}{nbsp}Value Type: ! <<CityFurnitureUsageValue-section,CityFurnitureUsageValue>>
! {nbsp}{nbsp}{nbsp}{nbsp}Definition: ! Specifies the actual uses of the CityFurniture.
! {nbsp}{nbsp}{nbsp}{nbsp}Multiplicity: ! [0..*]
! {nbsp}{nbsp}{nbsp}{nbsp}Stereotype: ! «Property»
!===
|=== 

==== *Code Lists*

[[CityFurnitureClassValue-section]]
===== *Code List CityFurnitureClassValue*

[cols="1a"]
|===
|*Code List CityFurnitureClassValue* 
|[cols="1,4",frame=none,grid=none]
!===
! {nbsp}{nbsp}{nbsp}{nbsp}Definition: ! CityFurnitureClassValue is a code list used to further classify a CityFurniture. 
! {nbsp}{nbsp}{nbsp}{nbsp}Subclass of: ! <<-section,>> 
! {nbsp}{nbsp}{nbsp}{nbsp}StereoType: ! «CodeList»
!===
|*Relations* 
|*Attributes*
|=== 

[[CityFurnitureFunctionValue-section]]
===== *Code List CityFurnitureFunctionValue*

[cols="1a"]
|===
|*Code List CityFurnitureFunctionValue* 
|[cols="1,4",frame=none,grid=none]
!===
! {nbsp}{nbsp}{nbsp}{nbsp}Definition: ! CityFurnitureFunctionValue is a code list that enumerates the different purposes of a CityFurniture. 
! {nbsp}{nbsp}{nbsp}{nbsp}Subclass of: ! <<-section,>> 
! {nbsp}{nbsp}{nbsp}{nbsp}StereoType: ! «CodeList»
!===
|*Relations* 
|*Attributes*
|=== 

[[CityFurnitureUsageValue-section]]
==== *Code List CityFurnitureUsageValue*

[cols="1a"]
|===
|*Code List CityFurnitureUsageValue* 
|[cols="1,4",frame=none,grid=none]
!===
! {nbsp}{nbsp}{nbsp}{nbsp}Definition: ! CityFurnitureUsageValue is a code list that enumerates the different uses of a CityFurniture.
! {nbsp}{nbsp}{nbsp}{nbsp}Subclass of: ! <<-section,>> 
! {nbsp}{nbsp}{nbsp}{nbsp}StereoType: ! «CodeList»
!===
|*Relations* 
|*Attributes*
|=== 
  



