[[CityObjectGroup-package]]
==== *Package*

[cols="1a"]
|===
|{set:cellbgcolor:#FFFFFF} *Package CityObjectGroup*
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Description: ! The CityObjectGroup module supports grouping of city objects. Arbitrary city objects may be aggregated in groups according to user-defined criteria. A group may be further classified by application-specific attributes. 
!{nbsp}{nbsp}{nbsp}{nbsp}Parent Package: ! CityGML
!{nbsp}{nbsp}{nbsp}{nbsp}Stereotype: ! «ApplicationSchema»
!===
|===

|===
|Editing instructions:
| 1) For all classes
| {nbsp}{nbsp}{nbsp}a) If a stereotype value is "<<←section,>>", change it to "none"
| {nbsp}{nbsp}{nbsp}b) If a subclass value is not provided, set it to "none"
| {nbsp}{nbsp}{nbsp}c) If a multiplicity value is not provided, set it to "1" 
| {nbsp}{nbsp}{nbsp}d) If the Role Name of a relation is not provided, delete the Role Name row
| {nbsp}{nbsp}{nbsp}e) If the stereotype of an attribute is not provided, set it to <<Property>>
| 2) For all classes with the "CodeList" stereotype 
| {nbsp}{nbsp}{nbsp}a) Copy the name and description into the table in the Code List section
| {nbsp}{nbsp}{nbsp}b) Delete the class
| 3) If there are no code lists, then delete the Code List section
| 4) Delete these instructions when done
|===

==== *Classes*

[[CityObjectGroup-section]]
===== *Class CityObjectGroup*

[cols="1a"]
|===
|*CityObjectGroup* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A CityObjectGroup represents an application-specific aggregation of city objects according to some user-defined criteria. Examples for groups are the buildings in a specific region, the result of a query, or objects put together for visualization purposes. Each member of a group may be qualified by a role name, reflecting the role each city object plays in the context of the group. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractLogicalSpace-section,AbstractLogicalSpace>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «TopLevelFeatureType»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|{set:cellbgcolor:#FFFFFF} 
|<<AbstractCityObject-section,AbstractCityObject>> 
|
|{set:cellbgcolor:#FFFFFF} 
|<<AbstractCityObject-section,AbstractCityObject>> 
|
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
 
|{set:cellbgcolor:#FFFFFF} class  |<<CityObjectGroupClassValue-section,CityObjectGroupClassValue>>  [0..1] |Indicates the specific type of the CityObjectGroup.
 
|{set:cellbgcolor:#FFFFFF} function  |<<CityObjectGroupFunctionValue-section,CityObjectGroupFunctionValue>>  [0..*] |Specifies the intended purposes of the CityObjectGroup.
 
|{set:cellbgcolor:#FFFFFF} usage  |<<CityObjectGroupUsageValue-section,CityObjectGroupUsageValue>>  [0..*] |Specifies the actual usages of the CityObjectGroup.
|===
[[CityObjectGroupClassValue-section]]
===== *Class CityObjectGroupClassValue*

[cols="1a"]
|===
|*CityObjectGroupClassValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! CityObjectGroupClassValue is a code list used to further classify a CityObjectGroup. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
|===
[[CityObjectGroupFunctionValue-section]]
===== *Class CityObjectGroupFunctionValue*

[cols="1a"]
|===
|*CityObjectGroupFunctionValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! CityObjectGroupFunctionValue is a code list that enumerates the different purposes of a CityObjectGroup. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
|===
[[CityObjectGroupUsageValue-section]]
===== *Class CityObjectGroupUsageValue*

[cols="1a"]
|===
|*CityObjectGroupUsageValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! CityObjectGroupUsageValue is a code list that enumerates the different uses of a CityObjectGroup. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
|===
[[Role-section]]
===== *Class Role*

[cols="1a"]
|===
|*Role* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! Role qualifies the function of a city object within the CityObjectGroup. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «ObjectType»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
 
|{set:cellbgcolor:#FFFFFF} role  |<<CharacterString-section,CharacterString>>  |Describes the role the city object plays within the CityObjectGroup.
|===

==== *Code Lists*

[cols="1,4"]  
|===
^|*Code List* ^|*Definition*
| |
| |
|===
  


