[[CityObjectGroup-data-dictionary]]
=== *CityObjectGroup Model Data Dictionary*

Description:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} +
Stereotype:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}«ApplicationSchema» +
Parent Package:{nbsp}CityGML

[[CityObjectGroup-section]]
==== *Class CityObjectGroup*
Subclass of <<AbstractLogicalSpace-section,AbstractLogicalSpace>>

|====
|*Class CityObjectGroup*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<AbstractLogicalSpace-section,AbstractLogicalSpace>> +
StereoType:{nbsp}{nbsp} «TopLevelFeatureType»
|
|*Associations*
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Association +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<CityObjectGroup-section,CityObjectGroup>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} parent +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<AbstractCityObject-section,AbstractCityObject>> +
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} AssociationClass +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<CityObjectGroup-section,CityObjectGroup>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} groupMember +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<AbstractCityObject-section,AbstractCityObject>> +
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Generalization +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<CityObjectGroup-section,CityObjectGroup>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<AbstractLogicalSpace-section,AbstractLogicalSpace>> +
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}class +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} CityObjectGroupClassValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} SIG3D: General semantical meaning of the aggregation. Classification of the aggregation as given by the relevant national regulations, information communities, or specific applications.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}function +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} CityObjectGroupFunctionValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} SIG3D: Specific semantic meaning of the aggregation. Function of the aggregation as given by the relevant national regulations, information communities, or specific applications.   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}usage +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} CityObjectGroupUsageValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} SIG3D: Usage of the aggregation as given by the relevant national regulations, information communities, or specific applications.   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|
|==== 

[[CityObjectGroupClassValue-section]]
==== *Class CityObjectGroupClassValue*
Subclass of <<-section,>>

|====
|*Class CityObjectGroupClassValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|
|*Associations*
|*Attributes*
|
|==== 

[[CityObjectGroupFunctionValue-section]]
==== *Class CityObjectGroupFunctionValue*
Subclass of <<-section,>>

|====
|*Class CityObjectGroupFunctionValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|
|*Associations*
|*Attributes*
|
|==== 

[[CityObjectGroupUsageValue-section]]
==== *Class CityObjectGroupUsageValue*
Subclass of <<-section,>>

|====
|*Class CityObjectGroupUsageValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|
|*Associations*
|*Attributes*
|
|==== 

[[Role-section]]
==== *Class Role*
Subclass of <<-section,>>

|====
|*Class Role*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<-section,>> +
StereoType:{nbsp}{nbsp} «ObjectType»
|
|*Associations*
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}role +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} CharacterString +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} SIG3D: Description of the role.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|
|==== 
  


