[[Core-package]]
==== *Package*

[cols="1a"]
|===
|{set:cellbgcolor:#FFFFFF} *Package Core*
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Description: ! The Core module defines the basic components of the CityGML data model. The Core module defines abstract base classes that define the core properties of more specialized thematic classes defined in other modules. The Core module also defines concrete classes that are common to other modules, for example basic data types.  
!{nbsp}{nbsp}{nbsp}{nbsp}Parent Package: ! CityGML
!{nbsp}{nbsp}{nbsp}{nbsp}Stereotype: ! «ApplicationSchema»
!===
|===

|===
|Editing instructions:
| 1) For all classes
| {nbsp}{nbsp}{nbsp}a) If a stereotype value is "<<←section,>>", change it to "none"
| {nbsp}{nbsp}{nbsp}b) If a subclass value is not provided, set it to "none"
| {nbsp}{nbsp}{nbsp}c) If a multiplicity value is not provided, set it to "1" 
| {nbsp}{nbsp}{nbsp}d) If the Role Name of a relation is not provided, delete the Role Name row
| {nbsp}{nbsp}{nbsp}e) If the stereotype of an attribute is not provided, set it to <<Property>>
| 2) For all classes with the "CodeList" stereotype 
| {nbsp}{nbsp}{nbsp}a) Copy the name and description into the table in the Code List section
| {nbsp}{nbsp}{nbsp}b) Delete the class
| 3) If there are no code lists, then delete the Code List section
| 4) Delete these instructions when done
|===

==== *Classes*

[[AbstractAppearance-section]]
===== *Class AbstractAppearance*

[cols="1a"]
|===
|*AbstractAppearance* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! AbstractAppearance is the abstract superclass to represent any kind of appearance objects. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractFeatureWithLifespan-section,AbstractFeatureWithLifespan>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
|=== 

[[AbstractCityObject-section]]
===== *Class AbstractCityObject*

[cols="1a"]
|===
|*AbstractCityObject* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! AbstractCityObject is the abstract superclass of all thematic classes within the CityGML data model. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractFeatureWithLifespan-section,AbstractFeatureWithLifespan>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
[cols="15,20,25,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Relation name* !*Target class* !*Role name and multiplicity*  !*Definition*
!{set:cellbgcolor:#FFFFFF}  
!<<AbstractAppearance-section,AbstractAppearance>> 
!appearance [*]
!
!{set:cellbgcolor:#FFFFFF}  
!<<AbstractDynamizer-section,AbstractDynamizer>> 
!dynamizer [*]
!
!{set:cellbgcolor:#FFFFFF}  
!<<AbstractCityObject-section,AbstractCityObject>> 
!generalizesTo [*]
!
!{set:cellbgcolor:#FFFFFF}  
!<<AbstractCityObject-section,AbstractCityObject>> 
!relatedTo [*]
!
!{set:cellbgcolor:#FFFFFF}  
!<<AbstractGenericAttribute-section,AbstractGenericAttribute>> 
!genericAttribute [*]
!
!{set:cellbgcolor:#FFFFFF}  
!<<ExternalReference-section,ExternalReference>> 
!externalReference [*]
!
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} relativeToTerrain  !<<RelativeToTerrain-section,RelativeToTerrain>>  [0..1] !Describes the vertical position of the city object relative to the surrounding terrain.
 
!{set:cellbgcolor:#FFFFFF} relativeToWater  !<<RelativeToWater-section,RelativeToWater>>  [0..1] !Describes the vertical position of the city object relative to the surrounding water surface.
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[AbstractDynamizer-section]]
===== *Class AbstractDynamizer*

[cols="1a"]
|===
|*AbstractDynamizer* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! AbstractDynamizer is the abstract superclass to represent Dynamizer objects. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractFeatureWithLifespan-section,AbstractFeatureWithLifespan>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
|=== 

[[AbstractFeature-section]]
===== *Class AbstractFeature*

[cols="1a"]
|===
|*AbstractFeature* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! AbstractFeature is the abstract superclass of all feature types within the CityGML data model. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AnyFeature-section,AnyFeature>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} description  !<<CharacterString-section,CharacterString>>  [0..1] !Provides further information on the feature.
 
!{set:cellbgcolor:#FFFFFF} featureID  !<<ID-section,ID>>  !Specifies the unique identifier of the feature that is valid in the instance document within which it occurs.
 
!{set:cellbgcolor:#FFFFFF} identifier  !<<ScopedName-section,ScopedName>>  [0..1] !Specifies the unique identifier of the feature that is valid globally.
 
!{set:cellbgcolor:#FFFFFF} name  !<<GenericName-section,GenericName>>  [0..*] !Specifies the name of the feature.
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[AbstractFeatureWithLifespan-section]]
===== *Class AbstractFeatureWithLifespan*

[cols="1a"]
|===
|*AbstractFeatureWithLifespan* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! AbstractFeatureWithLifespan is the base class for all CityGML features. It allows the optional specification of the real-world and database times for the existence of each feature. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractFeature-section,AbstractFeature>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} creationDate  !<<DateTime-section,DateTime>>  [0..1] !Indicates the date at which a CityGML feature was added to the CityModel.
 
!{set:cellbgcolor:#FFFFFF} terminationDate  !<<DateTime-section,DateTime>>  [0..1] !Indicates the date at which a CityGML feature was removed from the CityModel.
 
!{set:cellbgcolor:#FFFFFF} validFrom  !<<DateTime-section,DateTime>>  [0..1] !Indicates the date at wich a CityGML feature started to exist in the real world.
 
!{set:cellbgcolor:#FFFFFF} validTo  !<<DateTime-section,DateTime>>  [0..1] !Indicates the date at wich a CityGML feature ended to exist in the real world.
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[AbstractLogicalSpace-section]]
===== *Class AbstractLogicalSpace*

[cols="1a"]
|===
|*AbstractLogicalSpace* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! AbstractLogicalSpace is the abstract superclass for all types of logical spaces. Logical space refers to spaces that are not bounded by physical surfaces but are defined according to thematic considerations. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractSpace-section,AbstractSpace>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
|=== 

[[AbstractOccupiedSpace-section]]
===== *Class AbstractOccupiedSpace*

[cols="1a"]
|===
|*AbstractOccupiedSpace* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! AbstractOccupiedSpace is the abstract superclass for all types of physically occupied spaces. Occupied space refers to spaces that are partially or entirely filled with matter. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractPhysicalSpace-section,AbstractPhysicalSpace>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
[cols="15,20,25,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Relation name* !*Target class* !*Role name and multiplicity*  !*Definition*
!{set:cellbgcolor:#FFFFFF}  
!<<ImplicitGeometry-section,ImplicitGeometry>> 
!lod1ImplicitRepresentation [0..1]
!
!{set:cellbgcolor:#FFFFFF}  
!<<ImplicitGeometry-section,ImplicitGeometry>> 
!lod2ImplicitRepresentation [0..1]
!
!{set:cellbgcolor:#FFFFFF}  
!<<ImplicitGeometry-section,ImplicitGeometry>> 
!lod3ImplicitRepresentation [0..1]
!
!===
|=== 

[[AbstractPhysicalSpace-section]]
===== *Class AbstractPhysicalSpace*

[cols="1a"]
|===
|*AbstractPhysicalSpace* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! AbstractPhysicalSpace is the abstract superclass for all types of physical spaces. Physical space refers to spaces that are fully or partially bounded by physical objects. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractSpace-section,AbstractSpace>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
[cols="15,20,25,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Relation name* !*Target class* !*Role name and multiplicity*  !*Definition*
!{set:cellbgcolor:#FFFFFF}  
!<<GM_MultiCurve-section,GM_MultiCurve>> 
!lod3TerrainIntersectionCurve [0..1]
!
!{set:cellbgcolor:#FFFFFF}  
!<<AbstractPointCloud-section,AbstractPointCloud>> 
!pointCloud [0..1]
!
!{set:cellbgcolor:#FFFFFF}  
!<<GM_MultiCurve-section,GM_MultiCurve>> 
!lod1TerrainIntersectionCurve [0..1]
!
!{set:cellbgcolor:#FFFFFF}  
!<<GM_MultiCurve-section,GM_MultiCurve>> 
!lod2TerrainIntersectionCurve [0..1]
!
!===
|=== 

[[AbstractPointCloud-section]]
===== *Class AbstractPointCloud*

[cols="1a"]
|===
|*AbstractPointCloud* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! AbstractPointCloud is the abstract superclass to represent PointCloud objects. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractFeature-section,AbstractFeature>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
|=== 

[[AbstractSpace-section]]
===== *Class AbstractSpace*

[cols="1a"]
|===
|*AbstractSpace* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! AbstractSpace is the abstract superclass for all types of spaces. A space is an entity of volumetric extent in the real world. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractCityObject-section,AbstractCityObject>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
[cols="15,20,25,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Relation name* !*Target class* !*Role name and multiplicity*  !*Definition*
!{set:cellbgcolor:#FFFFFF}  
!<<GM_Solid-section,GM_Solid>> 
!lod2Solid [0..1]
!
!{set:cellbgcolor:#FFFFFF}  
!<<AbstractSpaceBoundary-section,AbstractSpaceBoundary>> 
!boundary [*]
!
!{set:cellbgcolor:#FFFFFF}  
!<<GM_MultiCurve-section,GM_MultiCurve>> 
!lod3MultiCurve [0..1]
!
!{set:cellbgcolor:#FFFFFF}  
!<<GM_Solid-section,GM_Solid>> 
!lod1Solid [0..1]
!
!{set:cellbgcolor:#FFFFFF}  
!<<GM_MultiSurface-section,GM_MultiSurface>> 
!lod0MultiSurface [0..1]
!
!{set:cellbgcolor:#FFFFFF}  
!<<GM_MultiCurve-section,GM_MultiCurve>> 
!lod0MultiCurve [0..1]
!
!{set:cellbgcolor:#FFFFFF}  
!<<GM_Point-section,GM_Point>> 
!lod0Point [0..1]
!
!{set:cellbgcolor:#FFFFFF}  
!<<GM_Solid-section,GM_Solid>> 
!lod3Solid [0..1]
!
!{set:cellbgcolor:#FFFFFF}  
!<<GM_MultiSurface-section,GM_MultiSurface>> 
!lod3MultiSurface [0..1]
!
!{set:cellbgcolor:#FFFFFF}  
!<<GM_MultiSurface-section,GM_MultiSurface>> 
!lod2MultiSurface [0..1]
!
!{set:cellbgcolor:#FFFFFF}  
!<<GM_MultiCurve-section,GM_MultiCurve>> 
!lod2MultiCurve [0..1]
!
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} area  !<<QualifiedArea-section,QualifiedArea>>  [0..*] !Specifies qualified areas related to the space.
 
!{set:cellbgcolor:#FFFFFF} spaceType  !<<SpaceType-section,SpaceType>>  [0..1] !Specifies the degree of openness of a space.
 
!{set:cellbgcolor:#FFFFFF} volume  !<<QualifiedVolume-section,QualifiedVolume>>  [0..*] !Specifies qualified volumes related to the space.
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[AbstractSpaceBoundary-section]]
===== *Class AbstractSpaceBoundary*

[cols="1a"]
|===
|*AbstractSpaceBoundary* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! AbstractSpaceBoundary is the abstract superclass for all types of space boundaries. A space boundary is an entity with areal extent in the real world. Space boundaries are objects that bound a Space. They also realize the contact between adjacent spaces. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractCityObject-section,AbstractCityObject>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
|=== 

[[AbstractThematicSurface-section]]
===== *Class AbstractThematicSurface*

[cols="1a"]
|===
|*AbstractThematicSurface* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! AbstractThematicSurface is the abstract superclass for all types of thematic surfaces. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractSpaceBoundary-section,AbstractSpaceBoundary>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
[cols="15,20,25,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Relation name* !*Target class* !*Role name and multiplicity*  !*Definition*
!{set:cellbgcolor:#FFFFFF}  
!<<GM_MultiCurve-section,GM_MultiCurve>> 
!lod0MultiCurve [0..1]
!
!{set:cellbgcolor:#FFFFFF}  
!<<GM_MultiSurface-section,GM_MultiSurface>> 
!lod0MultiSurface [0..1]
!
!{set:cellbgcolor:#FFFFFF}  
!<<GM_MultiSurface-section,GM_MultiSurface>> 
!lod3MultiSurface [0..1]
!
!{set:cellbgcolor:#FFFFFF}  
!<<GM_MultiSurface-section,GM_MultiSurface>> 
!lod1MultiSurface [0..1]
!
!{set:cellbgcolor:#FFFFFF}  
!<<AbstractPointCloud-section,AbstractPointCloud>> 
!pointCloud [0..1]
!
!{set:cellbgcolor:#FFFFFF}  
!<<GM_MultiSurface-section,GM_MultiSurface>> 
!lod2MultiSurface [0..1]
!
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} area  !<<QualifiedArea-section,QualifiedArea>>  [0..*] !Specifies qualified areas related to the thematic surface.
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[AbstractUnoccupiedSpace-section]]
===== *Class AbstractUnoccupiedSpace*

[cols="1a"]
|===
|*AbstractUnoccupiedSpace* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! AbstractUnoccupiedSpace is the abstract superclass for all types of physically unoccupied spaces. Unoccupied space refers to spaces that are entirely or mostly free of matter. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractPhysicalSpace-section,AbstractPhysicalSpace>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
|=== 

[[AbstractVersion-section]]
===== *Class AbstractVersion*

[cols="1a"]
|===
|*AbstractVersion* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! AbstractVersion is the abstract superclass to represent Version objects. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractFeatureWithLifespan-section,AbstractFeatureWithLifespan>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
|=== 

[[AbstractVersionTransition-section]]
===== *Class AbstractVersionTransition*

[cols="1a"]
|===
|*AbstractVersionTransition* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! AbstractVersionTransition is the abstract superclass to represent VersionTransition objects. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractFeatureWithLifespan-section,AbstractFeatureWithLifespan>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
|=== 

[[Address-section]]
===== *Class Address*

[cols="1a"]
|===
|*Address* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! Address represents an address of a city object. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractFeature-section,AbstractFeature>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
[cols="15,20,25,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Relation name* !*Target class* !*Role name and multiplicity*  !*Definition*
!{set:cellbgcolor:#FFFFFF}  
!<<GM_MultiPoint-section,GM_MultiPoint>> 
!multiPoint [0..1]
!
!{set:cellbgcolor:#FFFFFF}  
!<<XALAddressDetails-section,XALAddressDetails>> 
!xalAddress [1]
!
!===
|=== 

[[CityModel-section]]
===== *Class CityModel*

[cols="1a"]
|===
|*CityModel* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! CityModel is the container for all objects belonging to a city model. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractFeatureWithLifespan-section,AbstractFeatureWithLifespan>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
[cols="15,20,25,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Relation name* !*Target class* !*Role name and multiplicity*  !*Definition*
!{set:cellbgcolor:#FFFFFF}  
!<<CityModelMember-section,CityModelMember>> 
!cityModelMember [*]
!
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} engineeringCRS  !<<EngineeringCRS-section,EngineeringCRS>>  [0..1] !Specifies the local coordinate reference system of the CityModel.
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[CityObjectRelation-section]]
===== *Class CityObjectRelation*

[cols="1a"]
|===
|*CityObjectRelation* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! CityObjectRelation represents a specific relation from the city object in which it is included to another city object. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «ObjectType»
!===
[cols="15,20,25,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Relation name* !*Target class* !*Role name and multiplicity*  !*Definition*
!{set:cellbgcolor:#FFFFFF}  
!<<AbstractGenericAttribute-section,AbstractGenericAttribute>> 
!genericAttribute [*]
!
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} relationType  !<<RelationTypeValue-section,RelationTypeValue>>  !Indicates the specific type of the CityObjectRelation.
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[ClosureSurface-section]]
===== *Class ClosureSurface*

[cols="1a"]
|===
|*ClosureSurface* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! ClosureSurface is a special type of thematic surface used to close holes in volumetric objects. Closure surfaces are virtual (non-physical) surfaces. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractThematicSurface-section,AbstractThematicSurface>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
|=== 

[[DoubleBetween0and1-section]]
===== *Class DoubleBetween0and1*

[cols="1a"]
|===
|*DoubleBetween0and1* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! DoubleBetween0and1 is a basic type for values, which are greater or equal than 0 and less or equal than 1. The type is used for color encoding, for example. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «BasicType»
!{nbsp}{nbsp}{nbsp}{nbsp}Constraint: ! valueBetween0and1 (OCL): inv:
DoubleBetween0and1.allInstances()->forAll( p \| p >=0 and p <= 1 )    
!===
|=== 

[[DoubleBetween0and1List-section]]
===== *Class DoubleBetween0and1List*

[cols="1a"]
|===
|*DoubleBetween0and1List* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! DoubleBetween0and1List is a basic type that represents a list of double values greater or equal than 0 and less or equal than 1. The type is used for color encoding, for example. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «BasicType»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} list  !<<DoubleBetween0and1-section,DoubleBetween0and1>>  !Specifies the list of double values.
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[DoubleList-section]]
===== *Class DoubleList*

[cols="1a"]
|===
|*DoubleList* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! DoubleList is an ordered sequence of double values. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «BasicType»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} list  !<<Real-section,Real>>  !Specifies the list of double values.
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[DoubleOrNilReasonList-section]]
===== *Class DoubleOrNilReasonList*

[cols="1a"]
|===
|*DoubleOrNilReasonList* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! DoubleOrNilReasonList is a basic type that represents a list of double values and/or nil reasons. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «BasicType»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} list  !<<DoubleOrNilReason-section,DoubleOrNilReason>>  !Specifies the list of double values and/or nil reasons.
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[ID-section]]
===== *Class ID*

[cols="1a"]
|===
|*ID* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! ID is a basic type that represents a unique identifier. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «BasicType»
!===
|=== 

[[ImplicitGeometry-section]]
===== *Class ImplicitGeometry*

[cols="1a"]
|===
|*ImplicitGeometry* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! ImplicitGeometry is a geometry representation where the shape is stored only once as a prototypical geometry, for example a tree or other vegetation object, a traffic light or a traffic sign. This prototypic geometry object can be re-used or referenced many times, wherever the corresponding feature occurs in the 3D city model. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «ObjectType»
!===
[cols="15,20,25,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Relation name* !*Target class* !*Role name and multiplicity*  !*Definition*
!{set:cellbgcolor:#FFFFFF}  
!<<AbstractAppearance-section,AbstractAppearance>> 
!appearance [*]
!
!{set:cellbgcolor:#FFFFFF}  
!<<GM_Object-section,GM_Object>> 
!relativeGeometry [0..1]
!
!{set:cellbgcolor:#FFFFFF}  
!<<GM_Point-section,GM_Point>> 
!referencePoint [1]
!
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} libraryObject  !<<URI-section,URI>>  [0..1] !Specifies the URI that points to the prototypical geometry stored in an external file.
 
!{set:cellbgcolor:#FFFFFF} mimeType  !<<MimeTypeValue-section,MimeTypeValue>>  [0..1] !Specifies the MIME type of the external file that stores the prototypical geometry.
 
!{set:cellbgcolor:#FFFFFF} objectID  !<<ID-section,ID>>  !Specifies the unique identifier of the ImplicitGeometry.
 
!{set:cellbgcolor:#FFFFFF} transformationMatrix  !<<TransformationMatrix4x4-section,TransformationMatrix4x4>>  !Specifies the mathematical transformation (translation, rotation, and scaling) between the prototypical geometry and the actual spatial position of the object.
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[IntegerBetween0and3-section]]
===== *Class IntegerBetween0and3*

[cols="1a"]
|===
|*IntegerBetween0and3* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! IntegerBetween0and3 is a basic type for integer values, which are greater or equal than 0 and less or equal than 3. The type is used for encoding the LOD number. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «BasicType»
!{nbsp}{nbsp}{nbsp}{nbsp}Constraint: ! valueBetween0and4 (OCL): inv: 
IntegerBetween0and4.allInstances()->forAll( p \| p >= 0 and p <= 4)    
!===
|=== 

[[IntervalValue-section]]
===== *Class IntervalValue*

[cols="1a"]
|===
|*IntervalValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! IntervalValue is a code list used to specify a time period. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[MeasureOrNilReasonList-section]]
===== *Class MeasureOrNilReasonList*

[cols="1a"]
|===
|*MeasureOrNilReasonList* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! MeasureOrNilReasonList is a basic type that represents a list of double values and/or nil reasons together with a unit of measurement. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<DoubleOrNilReasonList-section,DoubleOrNilReasonList>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «BasicType»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} uom  !<<UnitOfMeasure-section,UnitOfMeasure>>  !Specifies the unit of measurement of the double values.
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[MimeTypeValue-section]]
===== *Class MimeTypeValue*

[cols="1a"]
|===
|*MimeTypeValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! MimeTypeValue is a code list used to specify the MIME type of a referenced resource. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[NilReasonEnumeration-section]]
===== *Class NilReasonEnumeration*

[cols="1a"]
|===
|*NilReasonEnumeration* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! NilReasonEnumeration is a code list that enumerates the different nil reasons. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[OccupantTypeValue-section]]
===== *Class OccupantTypeValue*

[cols="1a"]
|===
|*OccupantTypeValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! OccupantTypeValue is a code list used to classify occupants. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[OtherRelationTypeValue-section]]
===== *Class OtherRelationTypeValue*

[cols="1a"]
|===
|*OtherRelationTypeValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! OtherRelationTypeValue is a code list used to classify other types of city object relations. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<RelationTypeValue-section,RelationTypeValue>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[QualifiedAreaTypeValue-section]]
===== *Class QualifiedAreaTypeValue*

[cols="1a"]
|===
|*QualifiedAreaTypeValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! QualifiedAreaTypeValue is a code list used to specify area types. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[QualifiedVolumeTypeValue-section]]
===== *Class QualifiedVolumeTypeValue*

[cols="1a"]
|===
|*QualifiedVolumeTypeValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! QualifiedVolumeTypeValue is a code list used to specify volume types. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[RelationTypeValue-section]]
===== *Class RelationTypeValue*

[cols="1a"]
|===
|*RelationTypeValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! RelationTypeValue is a code list used to classify city object relations. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[TemporalRelationTypeValue-section]]
===== *Class TemporalRelationTypeValue*

[cols="1a"]
|===
|*TemporalRelationTypeValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! TemporalRelationTypeValue is a code list used to classify temporal city object relations. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<RelationTypeValue-section,RelationTypeValue>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[TopologicRelationTypeValue-section]]
===== *Class TopologicRelationTypeValue*

[cols="1a"]
|===
|*TopologicRelationTypeValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! TopologicRelationTypeValue is a code list used to classify topological city object relations. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<RelationTypeValue-section,RelationTypeValue>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[TransformationMatrix2x2-section]]
===== *Class TransformationMatrix2x2*

[cols="1a"]
|===
|*TransformationMatrix2x2* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! TransformationMatrix2x2 is a 2 by 2 matrix represented as a list of four double values in row major order. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<DoubleList-section,DoubleList>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «BasicType»
!{nbsp}{nbsp}{nbsp}{nbsp}Constraint: ! lengthOfList (OCL): inv: self.list->size() = 4    
!===
|=== 

[[TransformationMatrix3x4-section]]
===== *Class TransformationMatrix3x4*

[cols="1a"]
|===
|*TransformationMatrix3x4* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! TransformationMatrix3x4 is a 3 by 4 matrix represented as a list of twelve double values in row major order. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<DoubleList-section,DoubleList>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «BasicType»
!{nbsp}{nbsp}{nbsp}{nbsp}Constraint: ! lengthOfList (OCL): inv: self.list->size() = 12    
!===
|=== 

[[TransformationMatrix4x4-section]]
===== *Class TransformationMatrix4x4*

[cols="1a"]
|===
|*TransformationMatrix4x4* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! TransformationMatrix4x4 is a 4 by 4 matrix represented as a list of sixteen double values in row major order. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<DoubleList-section,DoubleList>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «BasicType»
!{nbsp}{nbsp}{nbsp}{nbsp}Constraint: ! lengthOfList (OCL): inv: self.list->size() = 16    
!===
|=== 

[[AbstractGenericAttribute-section]]
===== *Class AbstractGenericAttribute*

[cols="1a"]
|===
|*AbstractGenericAttribute* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! AbstractGenericAttribute is the abstract superclass for all types of generic attributes. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «DataType»
!===
|=== 

[[CityModelMember-section]]
===== *Class CityModelMember*

[cols="1a"]
|===
|*CityModelMember* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! CityModelMember is a union type that enumerates the different types of objects that can occur as members of a city model. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «Union»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} appearanceMember  !<<AbstractAppearance-section,AbstractAppearance>>  !Specifies the appearances of the CityModel.
 
!{set:cellbgcolor:#FFFFFF} cityObjectMember  !<<AbstractCityObject-section,AbstractCityObject>>  !Specifies the city objects that are part of the CityModel.
 
!{set:cellbgcolor:#FFFFFF} featureMember  !<<AbstractFeature-section,AbstractFeature>>  !Specifies the feature objects that are part of the CityModel. It allows to include objects that are not derived from a class defined in the CityGML data model, but from the ISO 19109 class AnyFeature.
 
!{set:cellbgcolor:#FFFFFF} versionMember  !<<AbstractVersion-section,AbstractVersion>>  !Specifies the different versions of the CityModel.
 
!{set:cellbgcolor:#FFFFFF} versionTransitionMember  !<<AbstractVersionTransition-section,AbstractVersionTransition>>  !Specifies the transitions between the different versions of the CityModel.
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[DoubleOrNilReason-section]]
===== *Class DoubleOrNilReason*

[cols="1a"]
|===
|*DoubleOrNilReason* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! DoubleOrNilReason is a union type that allows for choosing between a double value and a nil reason. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «Union»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} nilReason  !<<NilReason-section,NilReason>>  !Specifies the nil reason.
 
!{set:cellbgcolor:#FFFFFF} value  !<<Real-section,Real>>  !Specifies the double value.
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[ExternalReference-section]]
===== *Class ExternalReference*

[cols="1a"]
|===
|*ExternalReference* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! ExternalReference is a reference to a corresponding object in another information system, for example in the German cadastre (ALKIS), the German topographic information system (ATKIS), or the OS UK MasterMap®. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «DataType»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} informationSystem  !<<URI-section,URI>>  [0..1] !Specifies the URI that points to the external information system.
 
!{set:cellbgcolor:#FFFFFF} relationType  !<<URI-section,URI>>  [0..1] !Specifies an URI that additionally qualifies the ExternalReference. The URI can point to a definition from an external ontology (e.g. the sameAs relation from OWL) and allows for mapping the ExternalReference to RDF triples.
 
!{set:cellbgcolor:#FFFFFF} targetResource  !<<URI-section,URI>>  !Specifies the URI that points to the object in the external information system.
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[NilReason-section]]
===== *Class NilReason*

[cols="1a"]
|===
|*NilReason* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! NilReason is a union type that allows for choosing between two different types of nil reason. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «Union»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} nilReasonEnumeration  !<<NilReasonEnumeration-section,NilReasonEnumeration>>  !Indicates a nil reason that is provided in a code list.
 
!{set:cellbgcolor:#FFFFFF} URI  !<<URI-section,URI>>  !Specifies a URI that points to a resource that describes the nil reason.
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[Occupancy-section]]
===== *Class Occupancy*

[cols="1a"]
|===
|*Occupancy* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! Occupancy is an application-dependent indication of what is contained by a feature. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «DataType»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} interval  !<<IntervalValue-section,IntervalValue>>  [0..1] !Indicates the time period the occupants are contained by a feature.
 
!{set:cellbgcolor:#FFFFFF} numberOfOccupants  !<<Integer-section,Integer>>  !Indicates the number of occupants contained by a feature.
 
!{set:cellbgcolor:#FFFFFF} occupantType  !<<OccupantTypeValue-section,OccupantTypeValue>>  [0..1] !Indicates the specific type of the occupants that are contained by a feature.
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[QualifiedArea-section]]
===== *Class QualifiedArea*

[cols="1a"]
|===
|*QualifiedArea* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! QualifiedArea is an application-dependent measure of the area of a space or of a thematic surface. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «DataType»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} area  !<<Area-section,Area>>  !Specifies the value of the QualifiedArea.
 
!{set:cellbgcolor:#FFFFFF} typeOfArea  !<<QualifiedAreaTypeValue-section,QualifiedAreaTypeValue>>  !Indicates the specific type of the QualifiedArea.
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[QualifiedVolume-section]]
===== *Class QualifiedVolume*

[cols="1a"]
|===
|*QualifiedVolume* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! QualifiedVolume is an application-dependent measure of the volume of a space. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «DataType»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} typeOfVolume  !<<QualifiedVolumeTypeValue-section,QualifiedVolumeTypeValue>>  !Indicates the specific type of the QualifiedVolume.
 
!{set:cellbgcolor:#FFFFFF} volume  !<<Volume-section,Volume>>  !Specifies the value of the QualifiedVolume.
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[RelativeToTerrain-section]]
===== *Class RelativeToTerrain*

[cols="1a"]
|===
|*RelativeToTerrain* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! RelativeToTerrain enumerates the spatial relations of a city object relative to terrain in a qualitative way. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} entirelyAboveTerrain  !<<-section,>>  !Indicates that the city object is located entirely above the terrain.
 
!{set:cellbgcolor:#FFFFFF} substantiallyAboveTerrain  !<<-section,>>  !Indicates that the city object is for the most part located above the terrain.
 
!{set:cellbgcolor:#FFFFFF} substantiallyAboveAndBelowTerrain  !<<-section,>>  !Indicates that the city object is located half above the terrain and half below the terrain.
 
!{set:cellbgcolor:#FFFFFF} substantiallyBelowTerrain  !<<-section,>>  !Indicates that the city object is for the most part located below the terrain.
 
!{set:cellbgcolor:#FFFFFF} entirelyBelowTerrain  !<<-section,>>  !Indicates that the city object is located entirely below the terrain.
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[RelativeToWater-section]]
===== *Class RelativeToWater*

[cols="1a"]
|===
|*RelativeToWater* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! RelativeToWater enumerates the spatial relations of a city object relative to the water surface in a qualitative way. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} entirelyAboveWaterSurface  !<<-section,>>  !Indicates that the city object is located entirely above the water surface.
 
!{set:cellbgcolor:#FFFFFF} substantiallyAboveWaterSurface  !<<-section,>>  !Indicates that the city object is for the most part located above the water surface.
 
!{set:cellbgcolor:#FFFFFF} substantiallyAboveAndBelowWaterSurface  !<<-section,>>  !Indicates that the city object is located half above the water surface and half below the water surface.
 
!{set:cellbgcolor:#FFFFFF} substantiallyBelowWaterSurface  !<<-section,>>  !Indicates that the city object is for the most part located below the water surface.
 
!{set:cellbgcolor:#FFFFFF} entirelyBelowWaterSurface  !<<-section,>>  !Indicates that the city object is located entirely below the water surface.
 
!{set:cellbgcolor:#FFFFFF} temporarilyAboveAndBelowWaterSurface  !<<-section,>>  !Indicates that city object is temporarily located above or below the water level, because the height of the water surface is varying.
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[SpaceType-section]]
===== *Class SpaceType*

[cols="1a"]
|===
|*SpaceType* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! SpaceType is an enumeration that characterises a space according to its closure properties. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} closed  !<<-section,>>  !Indicates that the space has boundaries at the bottom, at the top, and on all sides.
 
!{set:cellbgcolor:#FFFFFF} open  !<<-section,>>  !Indicates that the space has at maximum a boundary at the bottom.
 
!{set:cellbgcolor:#FFFFFF} semiOpen  !<<-section,>>  !Indicates that the space has a boundary at the bottom and on at least one side.
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[XALAddressDetails-section]]
===== *Class XALAddressDetails*

[cols="1a"]
|===
|*XALAddressDetails* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! XALAddressDetails represents address details according to the OASIS xAL standard. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! None 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «DataType»
!===
|=== 
  


