[[Generics-package-dd]]
=== *Generics Data Dictionary*

[cols="1a"]
|===
|{set:cellbgcolor:#FFFFFF} *Package Generics*
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Description: ! The Generics module supports application-specific extensions to the CityGML data model. These extensions may be used to model and exchange additional attributes and features not covered by the predefined thematic classes of CityGML. Generic extensions shall only be used if appropriate thematic classes or attributes are not provided by any other CityGML module. 
!{nbsp}{nbsp}{nbsp}{nbsp}Parent Package: ! CityGML
!{nbsp}{nbsp}{nbsp}{nbsp}Stereotype: ! «ApplicationSchema»
!===
|===

|===
|Editing instructions:
| 1) Delete all tables for CodeLists 
| 2) If a subclass value is "<<←section,>>", change it to "none"
| 3) If a multiplicity value is not provided, set it to "1" 
| 4) If there are no entries in the role subtable, delete that subtable
| 5) If there are no entries in the attrubute subtable, delete that subtable
| 6) Delete these instructions when done
|===

==== *Classes*

[[GenericLogicalSpace-section]]
===== *Class GenericLogicalSpace*

[cols="1a"]
|===
|*GenericLogicalSpace* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A GenericLogicalSpace is a space that is not represented by any explicitly modelled AbstractLogicalSpace subclass within CityGML. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractLogicalSpace-section,AbstractLogicalSpace>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «TopLevelFeatureType»
!===
[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} class  !<<GenericLogicalSpaceClassValue-section,GenericLogicalSpaceClassValue>>  [0..1] !Indicates the specific type of the GenericLogicalSpace.
 
!{set:cellbgcolor:#FFFFFF} function  !<<GenericLogicalSpaceFunctionValue-section,GenericLogicalSpaceFunctionValue>>  [0..*] !Specifies the intended purposes of the GenericLogicalSpace.
 
!{set:cellbgcolor:#FFFFFF} usage  !<<GenericLogicalSpaceUsageValue-section,GenericLogicalSpaceUsageValue>>  [0..*] !Specifies the actual uses of the GenericLogicalSpace.
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[GenericLogicalSpaceClassValue-section]]
===== *Class GenericLogicalSpaceClassValue*

[cols="1a"]
|===
|*GenericLogicalSpaceClassValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! GenericLogicalSpaceClassValue is a code list used to further classify a GenericLogicalSpace. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[GenericLogicalSpaceFunctionValue-section]]
===== *Class GenericLogicalSpaceFunctionValue*

[cols="1a"]
|===
|*GenericLogicalSpaceFunctionValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! GenericLogicalSpaceFunctionValue is a code list that enumerates the different purposes of a GenericLogicalSpace. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[GenericLogicalSpaceUsageValue-section]]
===== *Class GenericLogicalSpaceUsageValue*

[cols="1a"]
|===
|*GenericLogicalSpaceUsageValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! GenericLogicalSpaceUsageValue is a code list that enumerates the different uses of a GenericLogicalSpace. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[GenericOccupiedSpace-section]]
===== *Class GenericOccupiedSpace*

[cols="1a"]
|===
|*GenericOccupiedSpace* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A GenericOccupiedSpace is a space that is not represented by any explicitly modelled AbstractOccupiedSpace subclass within CityGML. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractOccupiedSpace-section,AbstractOccupiedSpace>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «TopLevelFeatureType»
!===
[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} class  !<<GenericOccupiedSpaceClassValue-section,GenericOccupiedSpaceClassValue>>  [0..1] !Indicates the specific type of the GenericOccupiedSpace.
 
!{set:cellbgcolor:#FFFFFF} function  !<<GenericOccupiedSpaceFunctionValue-section,GenericOccupiedSpaceFunctionValue>>  [0..*] !Specifies the intended purposes of the GenericOccupiedSpace.
 
!{set:cellbgcolor:#FFFFFF} usage  !<<GenericOccupiedSpaceUsageValue-section,GenericOccupiedSpaceUsageValue>>  [0..*] !Specifies the actual uses of the GenericOccupiedSpace.
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[GenericOccupiedSpaceClassValue-section]]
===== *Class GenericOccupiedSpaceClassValue*

[cols="1a"]
|===
|*GenericOccupiedSpaceClassValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! GenericOccupiedSpaceClassValue is a code list used to further classify a GenericOccupiedSpace. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[GenericOccupiedSpaceFunctionValue-section]]
===== *Class GenericOccupiedSpaceFunctionValue*

[cols="1a"]
|===
|*GenericOccupiedSpaceFunctionValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! GenericOccupiedSpaceFunctionValue is a code list that enumerates the different purposes of a GenericOccupiedSpace. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[GenericOccupiedSpaceUsageValue-section]]
===== *Class GenericOccupiedSpaceUsageValue*

[cols="1a"]
|===
|*GenericOccupiedSpaceUsageValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! GenericOccupiedSpaceUsageValue is a code list that enumerates the different uses of a GenericOccupiedSpace. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[GenericThematicSurface-section]]
===== *Class GenericThematicSurface*

[cols="1a"]
|===
|*GenericThematicSurface* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A GenericThematicSurface is a surface that is not represented by any explicitly modelled AbstractThematicSurface subclass within CityGML. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractThematicSurface-section,AbstractThematicSurface>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «TopLevelFeatureType»
!===
[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} class  !<<GenericThematicSurfaceClassValue-section,GenericThematicSurfaceClassValue>>  [0..1] !Indicates the specific type of the GenericThematicSurface.
 
!{set:cellbgcolor:#FFFFFF} function  !<<GenericThematicSurfaceFunctionValue-section,GenericThematicSurfaceFunctionValue>>  [0..*] !Specifies the intended purposes of the GenericThematicSurface.
 
!{set:cellbgcolor:#FFFFFF} usage  !<<GenericThematicSurfaceUsageValue-section,GenericThematicSurfaceUsageValue>>  [0..*] !Specifies the actual uses of the GenericThematicSurface.
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[GenericThematicSurfaceClassValue-section]]
===== *Class GenericThematicSurfaceClassValue*

[cols="1a"]
|===
|*GenericThematicSurfaceClassValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! GenericThematicSurfaceClassValue is a code list used to further classify a GenericThematicSurface. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[GenericThematicSurfaceFunctionValue-section]]
===== *Class GenericThematicSurfaceFunctionValue*

[cols="1a"]
|===
|*GenericThematicSurfaceFunctionValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! GenericThematicSurfaceFunctionValue is a code list that enumerates the different purposes of a GenericThematicSurface. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[GenericThematicSurfaceUsageValue-section]]
===== *Class GenericThematicSurfaceUsageValue*

[cols="1a"]
|===
|*GenericThematicSurfaceUsageValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! GenericThematicSurfaceUsageValue is a code list that enumerates the different uses of a GenericThematicSurface. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[GenericUnoccupiedSpace-section]]
===== *Class GenericUnoccupiedSpace*

[cols="1a"]
|===
|*GenericUnoccupiedSpace* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A GenericUnoccupiedSpace is a space that is not represented by any explicitly modelled AbstractUnoccupiedSpace subclass within CityGML. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractUnoccupiedSpace-section,AbstractUnoccupiedSpace>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «TopLevelFeatureType»
!===
[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} class  !<<GenericUnoccupiedSpaceClassValue-section,GenericUnoccupiedSpaceClassValue>>  [0..1] !Indicates the specific type of the GenericUnoccupiedSpace.
 
!{set:cellbgcolor:#FFFFFF} function  !<<GenericUnoccupiedSpaceFunctionValue-section,GenericUnoccupiedSpaceFunctionValue>>  [0..*] !Specifies the intended purposes of the GenericUnoccupiedSpace.
 
!{set:cellbgcolor:#FFFFFF} usage  !<<GenericUnoccupiedSpaceUsageValue-section,GenericUnoccupiedSpaceUsageValue>>  [0..*] !Specifies the actual uses of the GenericUnoccupiedSpace.
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[GenericUnoccupiedSpaceClassValue-section]]
===== *Class GenericUnoccupiedSpaceClassValue*

[cols="1a"]
|===
|*GenericUnoccupiedSpaceClassValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! GenericUnoccupiedSpaceClassValue is a code list used to further classify a GenericUnoccupiedSpace. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[GenericUnoccupiedSpaceFunctionValue-section]]
===== *Class GenericUnoccupiedSpaceFunctionValue*

[cols="1a"]
|===
|*GenericUnoccupiedSpaceFunctionValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! GenericUnoccupiedSpaceFunctionValue is a code list that enumerates the different purposes of a GenericUnoccupiedSpace. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[GenericUnoccupiedSpaceUsageValue-section]]
===== *Class GenericUnoccupiedSpaceUsageValue*

[cols="1a"]
|===
|*GenericUnoccupiedSpaceUsageValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! GenericUnoccupiedSpaceUsageValue is a code list that enumerates the different uses of a GenericUnoccupiedSpace. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[DateAttribute-section]]
===== *Class DateAttribute*

[cols="1a"]
|===
|*DateAttribute* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! DateAttribute is a data type used to define generic attributes of type "Date". 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «DataType»
!===
[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} name  !<<CharacterString-section,CharacterString>>  !Specifies the name of the DateAttribute.
 
!{set:cellbgcolor:#FFFFFF} value  !<<Date-section,Date>>  !Specifies the "Date" value.
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[DoubleAttribute-section]]
===== *Class DoubleAttribute*

[cols="1a"]
|===
|*DoubleAttribute* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! DoubleAttribute is a data type used to define generic attributes of type "Double". 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «DataType»
!===
[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} name  !<<CharacterString-section,CharacterString>>  !Specifies the name of the DoubleAttribute.
 
!{set:cellbgcolor:#FFFFFF} value  !<<Real-section,Real>>  !Specifies the "Double" value.
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[GenericAttributeSet-section]]
===== *Class GenericAttributeSet*

[cols="1a"]
|===
|*GenericAttributeSet* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A GenericAttributeSet is a named collection of generic attributes. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «DataType»
!===
[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!{set:cellbgcolor:#FFFFFF} genericAttribute 
!<<AbstractGenericAttribute-section,AbstractGenericAttribute>> 
 [1..*]
!
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} codeSpace  !<<URI-section,URI>>  [0..1] !Associates the GenericAttributeSet with an authority that maintains the collection of generic attributes.
 
!{set:cellbgcolor:#FFFFFF} name  !<<CharacterString-section,CharacterString>>  !Specifies the name of the GenericAttributeSet.
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[IntAttribute-section]]
===== *Class IntAttribute*

[cols="1a"]
|===
|*IntAttribute* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! IntAttribute is a data type used to define generic attributes of type "Integer". 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «DataType»
!===
[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} name  !<<CharacterString-section,CharacterString>>  !Specifies the name of the IntAttribute.
 
!{set:cellbgcolor:#FFFFFF} value  !<<Integer-section,Integer>>  !Specifies the "Integer" value.
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[MeasureAttribute-section]]
===== *Class MeasureAttribute*

[cols="1a"]
|===
|*MeasureAttribute* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! MeasureAttribute is a data type used to define generic attributes of type "Measure". 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «DataType»
!===
[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} name  !<<CharacterString-section,CharacterString>>  !Specifies the name of the MeasureAttribute.
 
!{set:cellbgcolor:#FFFFFF} value  !<<Measure-section,Measure>>  !Specifies the value of the MeasureAttribute. The value is of type "Measure", which can additionally provide the units of measure. [cf. ISO 19103]
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[StringAttribute-section]]
===== *Class StringAttribute*

[cols="1a"]
|===
|*StringAttribute* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! StringAttribute is a data type used to define generic attributes of type "String". 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «DataType»
!===
[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} name  !<<CharacterString-section,CharacterString>>  !Specifies the name of the StringAttribute.
 
!{set:cellbgcolor:#FFFFFF} value  !<<CharacterString-section,CharacterString>>  !Specifies the "String" value.
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[UriAttribute-section]]
===== *Class UriAttribute*

[cols="1a"]
|===
|*UriAttribute* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! UriAttribute is a data type used to define generic attributes of type "URI". 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «DataType»
!===
[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} name  !<<CharacterString-section,CharacterString>>  !Specifies the name of the UriAttribute.
 
!{set:cellbgcolor:#FFFFFF} value  !<<URI-section,URI>>  !Specifies the "URI" value.
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 
  



