[[PointCloud-package]]
==== *PointCloud Package*

|====
|*Package PointCloud*
|Description:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}The PointCloud module supports representation of CityGML features by a collection of points. +
Stereotype:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}«ApplicationSchema» +
Parent Package: {nbsp}{nbsp}CityGML
|====

[[PointCloud-section]]
==== *Class PointCloud*

include::../requirements/PointCloud/REQ_PointCloud_PointCloud.adoc[]

|====
|*Class PointCloud* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} A PointCloud is an unordered collection of points that is a sampling of the geometry of a space or space boundary. +
Subclass Of: {nbsp}{nbsp} <<AbstractPointCloud-section,AbstractPointCloud>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «FeatureType»
|*Relations* 
|Relation Name: {nbsp}{nbsp} points +
Cardinality:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  0..1 +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} <<GM_MultiPoint-section,GM_MultiPoint>>  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Relates to the 3D MultiPoint geometry of the PointCloud stored inline with the city model. +
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}mimeType +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} MimeTypeValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Specifies the MIME type of the external point cloud file.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}pointFile +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} URI +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Specifies the URI that points to the external point cloud file.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}pointFileSrsName +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} CharacterString +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Indicates the coordinate reference system used by the external point cloud file.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|
|==== 
  


