[[Relief-package]]
==== *Package*

[cols="1a"]
|===
|{set:cellbgcolor:#FFFFFF} *Package Relief*
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Description: ! The Relief module supports representation of the terrain. CityGML supports terrain representations at different levels of detail, reflecting different accuracies or resolutions. Terrain may be specified as a regular raster or grid, as a TIN, by break lines, and/or by mass points. 
!{nbsp}{nbsp}{nbsp}{nbsp}Parent Package: ! CityGML
!{nbsp}{nbsp}{nbsp}{nbsp}Stereotype: ! «ApplicationSchema»
!===
|===

|===
|Editing instructions:
| 1) For all classes
| {nbsp}{nbsp}{nbsp}a) If a stereotype value is "<<←section,>>", change it to "none"
| {nbsp}{nbsp}{nbsp}b) If a subclass value is not provided, set it to "none"
| {nbsp}{nbsp}{nbsp}c) If a multiplicity value is not provided, set it to "1" 
| {nbsp}{nbsp}{nbsp}d) If the Role Name of a relation is not provided, delete the Role Name row
| {nbsp}{nbsp}{nbsp}e) If the stereotype of an attribute is not provided, set it to <<Property>>
| 2) For all classes with the "CodeList" stereotype 
| {nbsp}{nbsp}{nbsp}a) Copy the name and description into the table in the Code List section
| {nbsp}{nbsp}{nbsp}b) Delete the class
| 3) If there are no code lists, then delete the Code List section
| 4) Delete these instructions when done
|===

==== *Classes*

[[AbstractReliefComponent-section]]
===== *Class AbstractReliefComponent*

[cols="1a"]
|===
|*AbstractReliefComponent* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! An AbstractReliefComponent represents an element of the terrain surface - either a TIN, a Grid, mass points or break lines. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractSpaceBoundary-section,AbstractSpaceBoundary>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!{nbsp}{nbsp}{nbsp}{nbsp}Constraint: ! polygonGeometry (OCL): inv:
self.extent.patch->size()=1 and 
self.extent.patch->forAll(oclIsKindOf(GM_Polygon))    
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|{set:cellbgcolor:#FFFFFF} 
|<<GM_Surface-section,GM_Surface>> 
|
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
 
|{set:cellbgcolor:#FFFFFF} lod  |<<IntegerBetween0and3-section,IntegerBetween0and3>>  |Indicates the Level of Detail of the terrain component.
|===
[[BreaklineRelief-section]]
===== *Class BreaklineRelief*

[cols="1a"]
|===
|*BreaklineRelief* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A BreaklineRelief represents a terrain component with 3D lines. These lines denote break lines or ridge/valley lines. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractReliefComponent-section,AbstractReliefComponent>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|{set:cellbgcolor:#FFFFFF} 
|<<GM_MultiCurve-section,GM_MultiCurve>> 
|
|{set:cellbgcolor:#FFFFFF} 
|<<GM_MultiCurve-section,GM_MultiCurve>> 
|
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
|===
[[MassPointRelief-section]]
===== *Class MassPointRelief*

[cols="1a"]
|===
|*MassPointRelief* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A MassPointRelief represents a terrain component as a collection of 3D points. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractReliefComponent-section,AbstractReliefComponent>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|{set:cellbgcolor:#FFFFFF} 
|<<GM_MultiPoint-section,GM_MultiPoint>> 
|
|{set:cellbgcolor:#FFFFFF} 
|<<AbstractPointCloud-section,AbstractPointCloud>> 
|
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
|===
[[RasterRelief-section]]
===== *Class RasterRelief*

[cols="1a"]
|===
|*RasterRelief* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A RasterRelief represents a terrain component as a regular raster or grid. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractReliefComponent-section,AbstractReliefComponent>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|{set:cellbgcolor:#FFFFFF} 
|<<CV_DiscreteGridPointCoverage-section,CV_DiscreteGridPointCoverage>> 
|
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
|===
[[ReliefFeature-section]]
===== *Class ReliefFeature*

[cols="1a"]
|===
|*ReliefFeature* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A ReliefFeature is a collection of terrain components representing the Earth's surface, a.k.a. the Digital Terrain Model. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractSpaceBoundary-section,AbstractSpaceBoundary>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «TopLevelFeatureType»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|{set:cellbgcolor:#FFFFFF} 
|<<AbstractReliefComponent-section,AbstractReliefComponent>> 
|
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
 
|{set:cellbgcolor:#FFFFFF} lod  |<<IntegerBetween0and3-section,IntegerBetween0and3>>  |Indicates the Level of Detail of the ReliefFeature.
|===
[[TINRelief-section]]
===== *Class TINRelief*

[cols="1a"]
|===
|*TINRelief* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A TINRelief represents a terrain component as a triangulated irregular network. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractReliefComponent-section,AbstractReliefComponent>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|{set:cellbgcolor:#FFFFFF} 
|<<GM_TriangulatedSurface-section,GM_TriangulatedSurface>> 
|
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
|===

==== *Code Lists*

[cols="1,4"]  
|===
^|*Code List* ^|*Definition*
| |
| |
|===
  



