[[Transportation-data-dictionary]]
=== *Transportation Model Data Dictionary*

Description:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} +
Stereotype:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}«ApplicationSchema» +
Parent Package:{nbsp}CityGML

[[AbstractTransportationSpace-section]]
==== *Class AbstractTransportationSpace*
Subclass of <<AbstractUnoccupiedSpace-section,AbstractUnoccupiedSpace>>

include::../requirements/Transportation/REQ_Transportation_AbstractTransportationSpace.adoc[]

|====
|*Class AbstractTransportationSpace*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<AbstractUnoccupiedSpace-section,AbstractUnoccupiedSpace>> +
StereoType:{nbsp}{nbsp} «FeatureType»
|
|*Associations*
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Association +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<AbstractTransportationSpace-section,AbstractTransportationSpace>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} trafficSpace +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<TrafficSpace-section,TrafficSpace>> +
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Association +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<AbstractTransportationSpace-section,AbstractTransportationSpace>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} hole +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<Hole-section,Hole>> +
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Association +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<AbstractTransportationSpace-section,AbstractTransportationSpace>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} auxiliaryTrafficSpace +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<AuxiliaryTrafficSpace-section,AuxiliaryTrafficSpace>> +
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Generalization +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<AbstractTransportationSpace-section,AbstractTransportationSpace>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<AbstractUnoccupiedSpace-section,AbstractUnoccupiedSpace>> +
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Association +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<AbstractTransportationSpace-section,AbstractTransportationSpace>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} marking +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<Marking-section,Marking>> +
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Generalization +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<Intersection-section,Intersection>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<AbstractTransportationSpace-section,AbstractTransportationSpace>> +
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Generalization +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<Waterway-section,Waterway>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<AbstractTransportationSpace-section,AbstractTransportationSpace>> +
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Generalization +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<Track-section,Track>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<AbstractTransportationSpace-section,AbstractTransportationSpace>> +
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Generalization +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<Section-section,Section>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<AbstractTransportationSpace-section,AbstractTransportationSpace>> +
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Generalization +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<Road-section,Road>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<AbstractTransportationSpace-section,AbstractTransportationSpace>> +
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Generalization +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<Railway-section,Railway>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<AbstractTransportationSpace-section,AbstractTransportationSpace>> +
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Generalization +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<Square-section,Square>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<AbstractTransportationSpace-section,AbstractTransportationSpace>> +
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}occupancy +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Occupancy +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}trafficDirection +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TrafficDirectionValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|
|==== 

[[AuxiliaryTrafficArea-section]]
==== *Class AuxiliaryTrafficArea*
Subclass of <<AbstractThematicSurface-section,AbstractThematicSurface>>

include::../requirements/Transportation/REQ_Transportation_AuxiliaryTrafficArea.adoc[]

|====
|*Class AuxiliaryTrafficArea*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<AbstractThematicSurface-section,AbstractThematicSurface>> +
StereoType:{nbsp}{nbsp} «FeatureType»
|
|*Associations*
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Generalization +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<AuxiliaryTrafficArea-section,AuxiliaryTrafficArea>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<AbstractThematicSurface-section,AbstractThematicSurface>> +
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Association +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<AuxiliaryTrafficSpace-section,AuxiliaryTrafficSpace>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} boundary +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<AuxiliaryTrafficArea-section,AuxiliaryTrafficArea>> +
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}class +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} AuxiliaryTrafficAreaClassValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}function +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} AuxiliaryTrafficAreaFunctionValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}surfaceMaterial +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} SurfaceMaterialValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}usage +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} AuxiliaryTrafficAreaUsageValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|
|==== 

[[AuxiliaryTrafficAreaClassValue-section]]
==== *Class AuxiliaryTrafficAreaClassValue*
Subclass of <<-section,>>

include::../requirements/Transportation/REQ_Transportation_AuxiliaryTrafficAreaClassValue.adoc[]

|====
|*Class AuxiliaryTrafficAreaClassValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|
|*Associations*
|*Attributes*
|
|==== 

[[AuxiliaryTrafficAreaFunctionValue-section]]
==== *Class AuxiliaryTrafficAreaFunctionValue*
Subclass of <<-section,>>

include::../requirements/Transportation/REQ_Transportation_AuxiliaryTrafficAreaFunctionValue.adoc[]

|====
|*Class AuxiliaryTrafficAreaFunctionValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|
|*Associations*
|*Attributes*
|
|==== 

[[AuxiliaryTrafficAreaUsageValue-section]]
==== *Class AuxiliaryTrafficAreaUsageValue*
Subclass of <<-section,>>

include::../requirements/Transportation/REQ_Transportation_AuxiliaryTrafficAreaUsageValue.adoc[]

|====
|*Class AuxiliaryTrafficAreaUsageValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|
|*Associations*
|*Attributes*
|
|==== 

[[AuxiliaryTrafficSpace-section]]
==== *Class AuxiliaryTrafficSpace*
Subclass of <<AbstractUnoccupiedSpace-section,AbstractUnoccupiedSpace>>

include::../requirements/Transportation/REQ_Transportation_AuxiliaryTrafficSpace.adoc[]

|====
|*Class AuxiliaryTrafficSpace*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<AbstractUnoccupiedSpace-section,AbstractUnoccupiedSpace>> +
StereoType:{nbsp}{nbsp} «FeatureType»
|
|*Associations*
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Generalization +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<AuxiliaryTrafficSpace-section,AuxiliaryTrafficSpace>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<AbstractUnoccupiedSpace-section,AbstractUnoccupiedSpace>> +
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Association +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<AuxiliaryTrafficSpace-section,AuxiliaryTrafficSpace>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} boundary +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<AuxiliaryTrafficArea-section,AuxiliaryTrafficArea>> +
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Association +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<AbstractTransportationSpace-section,AbstractTransportationSpace>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} auxiliaryTrafficSpace +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<AuxiliaryTrafficSpace-section,AuxiliaryTrafficSpace>> +
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}class +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} AuxiliaryTrafficSpaceClassValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} SIG3D: Classification of AuxiliaryTrafficSpace as given by the relevant national regulations, information communities, or specific applications.   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}function +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} AuxiliaryTrafficSpaceFunctionValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} SIG3D: Specified function of AuxiliaryTrafficSpace given by the relevant national regulations, information communities, or specific applications.   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}granularity +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} GranularityValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}usage +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} AuxiliaryTrafficSpaceUsageValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} SIG3D: Actual usage of AuxiliaryTrafficSpace as given by the relevant national regulations, information communities, or specific applications.   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|
|==== 

[[AuxiliaryTrafficSpaceClassValue-section]]
==== *Class AuxiliaryTrafficSpaceClassValue*
Subclass of <<-section,>>

include::../requirements/Transportation/REQ_Transportation_AuxiliaryTrafficSpaceClassValue.adoc[]

|====
|*Class AuxiliaryTrafficSpaceClassValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|
|*Associations*
|*Attributes*
|
|==== 

[[AuxiliaryTrafficSpaceFunctionValue-section]]
==== *Class AuxiliaryTrafficSpaceFunctionValue*
Subclass of <<-section,>>

include::../requirements/Transportation/REQ_Transportation_AuxiliaryTrafficSpaceFunctionValue.adoc[]

|====
|*Class AuxiliaryTrafficSpaceFunctionValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|
|*Associations*
|*Attributes*
|
|==== 

[[AuxiliaryTrafficSpaceUsageValue-section]]
==== *Class AuxiliaryTrafficSpaceUsageValue*
Subclass of <<-section,>>

include::../requirements/Transportation/REQ_Transportation_AuxiliaryTrafficSpaceUsageValue.adoc[]

|====
|*Class AuxiliaryTrafficSpaceUsageValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|
|*Associations*
|*Attributes*
|
|==== 

[[ClearanceSpace-section]]
==== *Class ClearanceSpace*
Subclass of <<AbstractUnoccupiedSpace-section,AbstractUnoccupiedSpace>>

include::../requirements/Transportation/REQ_Transportation_ClearanceSpace.adoc[]

|====
|*Class ClearanceSpace*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<AbstractUnoccupiedSpace-section,AbstractUnoccupiedSpace>> +
StereoType:{nbsp}{nbsp} «FeatureType»
|
|*Associations*
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Generalization +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<ClearanceSpace-section,ClearanceSpace>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<AbstractUnoccupiedSpace-section,AbstractUnoccupiedSpace>> +
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Association +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<TrafficSpace-section,TrafficSpace>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} clearanceSpace +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<ClearanceSpace-section,ClearanceSpace>> +
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}class +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} ClearanceSpaceClassValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|
|==== 

[[ClearanceSpaceClassValue-section]]
==== *Class ClearanceSpaceClassValue*
Subclass of <<-section,>>

include::../requirements/Transportation/REQ_Transportation_ClearanceSpaceClassValue.adoc[]

|====
|*Class ClearanceSpaceClassValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|
|*Associations*
|*Attributes*
|
|==== 

[[Hole-section]]
==== *Class Hole*
Subclass of <<AbstractUnoccupiedSpace-section,AbstractUnoccupiedSpace>>

include::../requirements/Transportation/REQ_Transportation_Hole.adoc[]

|====
|*Class Hole*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<AbstractUnoccupiedSpace-section,AbstractUnoccupiedSpace>> +
StereoType:{nbsp}{nbsp} «FeatureType»
|
|*Associations*
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Generalization +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<Hole-section,Hole>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<AbstractUnoccupiedSpace-section,AbstractUnoccupiedSpace>> +
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Association +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<Hole-section,Hole>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} boundary +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<AbstractThematicSurface-section,AbstractThematicSurface>> +
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Association +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<AbstractTransportationSpace-section,AbstractTransportationSpace>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} hole +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<Hole-section,Hole>> +
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}class +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} HoleClassValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|
|==== 

[[HoleClassValue-section]]
==== *Class HoleClassValue*
Subclass of <<-section,>>

include::../requirements/Transportation/REQ_Transportation_HoleClassValue.adoc[]

|====
|*Class HoleClassValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|
|*Associations*
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} NoteLink +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<Note-section,Note>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<HoleClassValue-section,HoleClassValue>> +
|*Attributes*
|
|==== 

[[HoleSurface-section]]
==== *Class HoleSurface*
Subclass of <<AbstractThematicSurface-section,AbstractThematicSurface>>

include::../requirements/Transportation/REQ_Transportation_HoleSurface.adoc[]

|====
|*Class HoleSurface*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<AbstractThematicSurface-section,AbstractThematicSurface>> +
StereoType:{nbsp}{nbsp} «FeatureType»
|
|*Associations*
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Generalization +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<HoleSurface-section,HoleSurface>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<AbstractThematicSurface-section,AbstractThematicSurface>> +
|*Attributes*
|
|==== 

[[Intersection-section]]
==== *Class Intersection*
Subclass of <<AbstractTransportationSpace-section,AbstractTransportationSpace>>

include::../requirements/Transportation/REQ_Transportation_Intersection.adoc[]

|====
|*Class Intersection*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<AbstractTransportationSpace-section,AbstractTransportationSpace>> +
StereoType:{nbsp}{nbsp} «FeatureType»
|
|*Associations*
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Generalization +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<Intersection-section,Intersection>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<AbstractTransportationSpace-section,AbstractTransportationSpace>> +
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Association +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<Waterway-section,Waterway>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} intersection +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<Intersection-section,Intersection>> +
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Association +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<Road-section,Road>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} intersection +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<Intersection-section,Intersection>> +
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Association +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<Railway-section,Railway>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} intersection +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<Intersection-section,Intersection>> +
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Association +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<Track-section,Track>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} intersection +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<Intersection-section,Intersection>> +
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}class +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} IntersectionClassValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|
|==== 

[[IntersectionClassValue-section]]
==== *Class IntersectionClassValue*
Subclass of <<-section,>>

include::../requirements/Transportation/REQ_Transportation_IntersectionClassValue.adoc[]

|====
|*Class IntersectionClassValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|
|*Associations*
|*Attributes*
|
|==== 

[[Marking-section]]
==== *Class Marking*
Subclass of <<AbstractThematicSurface-section,AbstractThematicSurface>>

include::../requirements/Transportation/REQ_Transportation_Marking.adoc[]

|====
|*Class Marking*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<AbstractThematicSurface-section,AbstractThematicSurface>> +
StereoType:{nbsp}{nbsp} «FeatureType»
|
|*Associations*
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Generalization +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<Marking-section,Marking>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<AbstractThematicSurface-section,AbstractThematicSurface>> +
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Association +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<AbstractTransportationSpace-section,AbstractTransportationSpace>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} marking +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<Marking-section,Marking>> +
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}class +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} MarkingClassValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|
|==== 

[[MarkingClassValue-section]]
==== *Class MarkingClassValue*
Subclass of <<-section,>>

include::../requirements/Transportation/REQ_Transportation_MarkingClassValue.adoc[]

|====
|*Class MarkingClassValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|
|*Associations*
|*Attributes*
|
|==== 

[[Railway-section]]
==== *Class Railway*
Subclass of <<AbstractTransportationSpace-section,AbstractTransportationSpace>>

include::../requirements/Transportation/REQ_Transportation_Railway.adoc[]

|====
|*Class Railway*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<AbstractTransportationSpace-section,AbstractTransportationSpace>> +
StereoType:{nbsp}{nbsp} «TopLevelFeatureType»
|
|*Associations*
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Association +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<Railway-section,Railway>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} section +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<Section-section,Section>> +
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Association +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<Railway-section,Railway>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} intersection +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<Intersection-section,Intersection>> +
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Generalization +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<Railway-section,Railway>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<AbstractTransportationSpace-section,AbstractTransportationSpace>> +
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}class +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} RailwayClassValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}function +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} RailwayFunctionValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}usage +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} RailwayUsageValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|
|==== 

[[RailwayClassValue-section]]
==== *Class RailwayClassValue*
Subclass of <<-section,>>

include::../requirements/Transportation/REQ_Transportation_RailwayClassValue.adoc[]

|====
|*Class RailwayClassValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|
|*Associations*
|*Attributes*
|
|==== 

[[RailwayFunctionValue-section]]
==== *Class RailwayFunctionValue*
Subclass of <<-section,>>

include::../requirements/Transportation/REQ_Transportation_RailwayFunctionValue.adoc[]

|====
|*Class RailwayFunctionValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|
|*Associations*
|*Attributes*
|
|==== 

[[RailwayUsageValue-section]]
==== *Class RailwayUsageValue*
Subclass of <<-section,>>

include::../requirements/Transportation/REQ_Transportation_RailwayUsageValue.adoc[]

|====
|*Class RailwayUsageValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|
|*Associations*
|*Attributes*
|
|==== 

[[Road-section]]
==== *Class Road*
Subclass of <<AbstractTransportationSpace-section,AbstractTransportationSpace>>

include::../requirements/Transportation/REQ_Transportation_Road.adoc[]

|====
|*Class Road*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<AbstractTransportationSpace-section,AbstractTransportationSpace>> +
StereoType:{nbsp}{nbsp} «TopLevelFeatureType»
|
|*Associations*
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Association +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<Road-section,Road>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} intersection +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<Intersection-section,Intersection>> +
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Association +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<Road-section,Road>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} section +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<Section-section,Section>> +
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Generalization +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<Road-section,Road>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<AbstractTransportationSpace-section,AbstractTransportationSpace>> +
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}class +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} RoadClassValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}function +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} RoadFunctionValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}usage +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} RoadUsageValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|
|==== 

[[RoadClassValue-section]]
==== *Class RoadClassValue*
Subclass of <<-section,>>

include::../requirements/Transportation/REQ_Transportation_RoadClassValue.adoc[]

|====
|*Class RoadClassValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|
|*Associations*
|*Attributes*
|
|==== 

[[RoadFunctionValue-section]]
==== *Class RoadFunctionValue*
Subclass of <<-section,>>

include::../requirements/Transportation/REQ_Transportation_RoadFunctionValue.adoc[]

|====
|*Class RoadFunctionValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|
|*Associations*
|*Attributes*
|
|==== 

[[RoadUsageValue-section]]
==== *Class RoadUsageValue*
Subclass of <<-section,>>

include::../requirements/Transportation/REQ_Transportation_RoadUsageValue.adoc[]

|====
|*Class RoadUsageValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|
|*Associations*
|*Attributes*
|
|==== 

[[Section-section]]
==== *Class Section*
Subclass of <<AbstractTransportationSpace-section,AbstractTransportationSpace>>

include::../requirements/Transportation/REQ_Transportation_Section.adoc[]

|====
|*Class Section*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<AbstractTransportationSpace-section,AbstractTransportationSpace>> +
StereoType:{nbsp}{nbsp} «FeatureType»
|
|*Associations*
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Generalization +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<Section-section,Section>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<AbstractTransportationSpace-section,AbstractTransportationSpace>> +
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Association +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<Waterway-section,Waterway>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} section +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<Section-section,Section>> +
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Association +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<Railway-section,Railway>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} section +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<Section-section,Section>> +
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Association +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<Road-section,Road>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} section +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<Section-section,Section>> +
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Association +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<Track-section,Track>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} section +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<Section-section,Section>> +
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}class +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} SectionClassValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|
|==== 

[[SectionClassValue-section]]
==== *Class SectionClassValue*
Subclass of <<-section,>>

include::../requirements/Transportation/REQ_Transportation_SectionClassValue.adoc[]

|====
|*Class SectionClassValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|
|*Associations*
|*Attributes*
|
|==== 

[[Square-section]]
==== *Class Square*
Subclass of <<AbstractTransportationSpace-section,AbstractTransportationSpace>>

include::../requirements/Transportation/REQ_Transportation_Square.adoc[]

|====
|*Class Square*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<AbstractTransportationSpace-section,AbstractTransportationSpace>> +
StereoType:{nbsp}{nbsp} «TopLevelFeatureType»
|
|*Associations*
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Generalization +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<Square-section,Square>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<AbstractTransportationSpace-section,AbstractTransportationSpace>> +
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}class +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} SquareClassValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}function +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} SquareFunctionValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}usage +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} SquareUsageValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|
|==== 

[[SquareClassValue-section]]
==== *Class SquareClassValue*
Subclass of <<-section,>>

include::../requirements/Transportation/REQ_Transportation_SquareClassValue.adoc[]

|====
|*Class SquareClassValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|
|*Associations*
|*Attributes*
|
|==== 

[[SquareFunctionValue-section]]
==== *Class SquareFunctionValue*
Subclass of <<-section,>>

include::../requirements/Transportation/REQ_Transportation_SquareFunctionValue.adoc[]

|====
|*Class SquareFunctionValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|
|*Associations*
|*Attributes*
|
|==== 

[[SquareUsageValue-section]]
==== *Class SquareUsageValue*
Subclass of <<-section,>>

include::../requirements/Transportation/REQ_Transportation_SquareUsageValue.adoc[]

|====
|*Class SquareUsageValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|
|*Associations*
|*Attributes*
|
|==== 

[[SurfaceMaterialValue-section]]
==== *Class SurfaceMaterialValue*
Subclass of <<-section,>>

include::../requirements/Transportation/REQ_Transportation_SurfaceMaterialValue.adoc[]

|====
|*Class SurfaceMaterialValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|
|*Associations*
|*Attributes*
|
|==== 

[[Track-section]]
==== *Class Track*
Subclass of <<AbstractTransportationSpace-section,AbstractTransportationSpace>>

include::../requirements/Transportation/REQ_Transportation_Track.adoc[]

|====
|*Class Track*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<AbstractTransportationSpace-section,AbstractTransportationSpace>> +
StereoType:{nbsp}{nbsp} «TopLevelFeatureType»
|
|*Associations*
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Generalization +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<Track-section,Track>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<AbstractTransportationSpace-section,AbstractTransportationSpace>> +
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Association +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<Track-section,Track>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} section +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<Section-section,Section>> +
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Association +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<Track-section,Track>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} intersection +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<Intersection-section,Intersection>> +
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}class +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TrackClassValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}function +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TrackFunctionValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}usage +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TrackUsageValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|
|==== 

[[TrackClassValue-section]]
==== *Class TrackClassValue*
Subclass of <<-section,>>

include::../requirements/Transportation/REQ_Transportation_TrackClassValue.adoc[]

|====
|*Class TrackClassValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|
|*Associations*
|*Attributes*
|
|==== 

[[TrackFunctionValue-section]]
==== *Class TrackFunctionValue*
Subclass of <<-section,>>

include::../requirements/Transportation/REQ_Transportation_TrackFunctionValue.adoc[]

|====
|*Class TrackFunctionValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|
|*Associations*
|*Attributes*
|
|==== 

[[TrackUsageValue-section]]
==== *Class TrackUsageValue*
Subclass of <<-section,>>

include::../requirements/Transportation/REQ_Transportation_TrackUsageValue.adoc[]

|====
|*Class TrackUsageValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|
|*Associations*
|*Attributes*
|
|==== 

[[TrafficArea-section]]
==== *Class TrafficArea*
Subclass of <<AbstractThematicSurface-section,AbstractThematicSurface>>

include::../requirements/Transportation/REQ_Transportation_TrafficArea.adoc[]

|====
|*Class TrafficArea*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<AbstractThematicSurface-section,AbstractThematicSurface>> +
StereoType:{nbsp}{nbsp} «FeatureType»
|
|*Associations*
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Generalization +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<TrafficArea-section,TrafficArea>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<AbstractThematicSurface-section,AbstractThematicSurface>> +
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Association +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<TrafficSpace-section,TrafficSpace>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} boundary +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<TrafficArea-section,TrafficArea>> +
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}class +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TrafficAreaClassValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}function +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TrafficAreaFunctionValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}surfaceMaterial +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} SurfaceMaterialValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}usage +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TrafficAreaUsageValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|
|==== 

[[TrafficAreaClassValue-section]]
==== *Class TrafficAreaClassValue*
Subclass of <<-section,>>

include::../requirements/Transportation/REQ_Transportation_TrafficAreaClassValue.adoc[]

|====
|*Class TrafficAreaClassValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|
|*Associations*
|*Attributes*
|
|==== 

[[TrafficAreaFunctionValue-section]]
==== *Class TrafficAreaFunctionValue*
Subclass of <<-section,>>

include::../requirements/Transportation/REQ_Transportation_TrafficAreaFunctionValue.adoc[]

|====
|*Class TrafficAreaFunctionValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|
|*Associations*
|*Attributes*
|
|==== 

[[TrafficAreaUsageValue-section]]
==== *Class TrafficAreaUsageValue*
Subclass of <<-section,>>

include::../requirements/Transportation/REQ_Transportation_TrafficAreaUsageValue.adoc[]

|====
|*Class TrafficAreaUsageValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|
|*Associations*
|*Attributes*
|
|==== 

[[TrafficSpace-section]]
==== *Class TrafficSpace*
Subclass of <<AbstractUnoccupiedSpace-section,AbstractUnoccupiedSpace>>

include::../requirements/Transportation/REQ_Transportation_TrafficSpace.adoc[]

|====
|*Class TrafficSpace*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<AbstractUnoccupiedSpace-section,AbstractUnoccupiedSpace>> +
StereoType:{nbsp}{nbsp} «FeatureType»
|
|*Associations*
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Association +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<TrafficSpace-section,TrafficSpace>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} clearanceSpace +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<ClearanceSpace-section,ClearanceSpace>> +
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Association +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<TrafficSpace-section,TrafficSpace>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} successor +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<TrafficSpace-section,TrafficSpace>> +
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Association +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<TrafficSpace-section,TrafficSpace>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} boundary +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<TrafficArea-section,TrafficArea>> +
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Association +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<TrafficSpace-section,TrafficSpace>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} predecessor +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<TrafficSpace-section,TrafficSpace>> +
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Generalization +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<TrafficSpace-section,TrafficSpace>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<AbstractUnoccupiedSpace-section,AbstractUnoccupiedSpace>> +
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Association +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<AbstractTransportationSpace-section,AbstractTransportationSpace>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} trafficSpace +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<TrafficSpace-section,TrafficSpace>> +
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Association +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<TrafficSpace-section,TrafficSpace>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} successor +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<TrafficSpace-section,TrafficSpace>> +
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Association +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<TrafficSpace-section,TrafficSpace>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} predecessor +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<TrafficSpace-section,TrafficSpace>> +
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}class +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TrafficSpaceClassValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} SIG3D: Classification of TrafficSpace as given by the relevant national regulations, information communities, or specific applications.   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}function +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TrafficSpaceFunctionValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} SIG3D: Specified function of TrafficSpace given by the relevant national regulations, information communities, or specific applications.   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}granularity +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} GranularityValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}occupancy +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Occupancy +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}trafficDirection +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TrafficDirectionValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}usage +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TrafficSpaceUsageValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} SIG3D: Actual usage of TrafficSpace as given by the relevant national regulations, information communities, or specific applications.   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|
|==== 

[[TrafficSpaceClassValue-section]]
==== *Class TrafficSpaceClassValue*
Subclass of <<-section,>>

include::../requirements/Transportation/REQ_Transportation_TrafficSpaceClassValue.adoc[]

|====
|*Class TrafficSpaceClassValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|
|*Associations*
|*Attributes*
|
|==== 

[[TrafficSpaceFunctionValue-section]]
==== *Class TrafficSpaceFunctionValue*
Subclass of <<-section,>>

include::../requirements/Transportation/REQ_Transportation_TrafficSpaceFunctionValue.adoc[]

|====
|*Class TrafficSpaceFunctionValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|
|*Associations*
|*Attributes*
|
|==== 

[[TrafficSpaceUsageValue-section]]
==== *Class TrafficSpaceUsageValue*
Subclass of <<-section,>>

include::../requirements/Transportation/REQ_Transportation_TrafficSpaceUsageValue.adoc[]

|====
|*Class TrafficSpaceUsageValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|
|*Associations*
|*Attributes*
|
|==== 

[[TransportationSpaceClassValue-section]]
==== *Class TransportationSpaceClassValue*
Subclass of <<-section,>>

include::../requirements/Transportation/REQ_Transportation_TransportationSpaceClassValue.adoc[]

|====
|*Class TransportationSpaceClassValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|
|*Associations*
|*Attributes*
|
|==== 

[[TransportationSpaceFunctionValue-section]]
==== *Class TransportationSpaceFunctionValue*
Subclass of <<-section,>>

include::../requirements/Transportation/REQ_Transportation_TransportationSpaceFunctionValue.adoc[]

|====
|*Class TransportationSpaceFunctionValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|
|*Associations*
|*Attributes*
|
|==== 

[[TransportationSpaceUsageValue-section]]
==== *Class TransportationSpaceUsageValue*
Subclass of <<-section,>>

include::../requirements/Transportation/REQ_Transportation_TransportationSpaceUsageValue.adoc[]

|====
|*Class TransportationSpaceUsageValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|
|*Associations*
|*Attributes*
|
|==== 

[[Waterway-section]]
==== *Class Waterway*
Subclass of <<AbstractTransportationSpace-section,AbstractTransportationSpace>>

include::../requirements/Transportation/REQ_Transportation_Waterway.adoc[]

|====
|*Class Waterway*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<AbstractTransportationSpace-section,AbstractTransportationSpace>> +
StereoType:{nbsp}{nbsp} «TopLevelFeatureType»
|
|*Associations*
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Association +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<Waterway-section,Waterway>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} section +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<Section-section,Section>> +
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Association +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<Waterway-section,Waterway>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} intersection +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<Intersection-section,Intersection>> +
|Name: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Generalization +
Direction: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Source -> Destination +
Source Role: {nbsp}{nbsp}{nbsp}{nbsp}  +
Source Class: {nbsp}{nbsp}{nbsp} <<Waterway-section,Waterway>> +
Target Role: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp} <<AbstractTransportationSpace-section,AbstractTransportationSpace>> +
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}class +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} WaterwayClassValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}function +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} WaterwayFunctionValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}usage +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} WaterwayUsageValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|
|==== 

[[WaterwayClassValue-section]]
==== *Class WaterwayClassValue*
Subclass of <<-section,>>

include::../requirements/Transportation/REQ_Transportation_WaterwayClassValue.adoc[]

|====
|*Class WaterwayClassValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|
|*Associations*
|*Attributes*
|
|==== 

[[WaterwayFunctionValue-section]]
==== *Class WaterwayFunctionValue*
Subclass of <<-section,>>

include::../requirements/Transportation/REQ_Transportation_WaterwayFunctionValue.adoc[]

|====
|*Class WaterwayFunctionValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|
|*Associations*
|*Attributes*
|
|==== 

[[WaterwayUsageValue-section]]
==== *Class WaterwayUsageValue*
Subclass of <<-section,>>

include::../requirements/Transportation/REQ_Transportation_WaterwayUsageValue.adoc[]

|====
|*Class WaterwayUsageValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<-section,>> +
StereoType:{nbsp}{nbsp} «CodeList»
|
|*Associations*
|*Attributes*
|
|==== 

[[GranularityValue-section]]
==== *Class GranularityValue*
Subclass of <<-section,>>

include::../requirements/Transportation/REQ_Transportation_GranularityValue.adoc[]

|====
|*Class GranularityValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<-section,>> +
StereoType:{nbsp}{nbsp} 
|
|*Associations*
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}lane +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  + 

|Attribute Name: {nbsp}{nbsp}{nbsp}way +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  + 

|
|==== 

[[TrafficDirectionValue-section]]
==== *Class TrafficDirectionValue*
Subclass of <<-section,>>

include::../requirements/Transportation/REQ_Transportation_TrafficDirectionValue.adoc[]

|====
|*Class TrafficDirectionValue*
|Definition:{nbsp}{nbsp}{nbsp}{nbsp}  +
Subtype Of: {nbsp}{nbsp}<<-section,>> +
StereoType:{nbsp}{nbsp} 
|
|*Associations*
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}forwards +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  + 

|Attribute Name: {nbsp}{nbsp}{nbsp}backwards +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  + 

|Attribute Name: {nbsp}{nbsp}{nbsp}both +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  + 

|
|==== 
  



