[[Transportation-package]]
==== *Package*

[cols="1a"]
|===
|{set:cellbgcolor:#FFFFFF} *Package Transportation*
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Description: ! The Transportation module supports representation of the transportation infrastructure. Transportation features include roads, tracks, waterways, railways, and squares. Transportation features may be represented as a network and/or as a collection of spaces or surface elements embedded in a three-dimensional space. 
!{nbsp}{nbsp}{nbsp}{nbsp}Parent Package: ! CityGML
!{nbsp}{nbsp}{nbsp}{nbsp}Stereotype: ! «ApplicationSchema»
!===
|===

|===
|Editing instructions:
| 1) For all classes
| {nbsp}{nbsp}{nbsp}a) If a stereotype value is "<<←section,>>", change it to "none"
| {nbsp}{nbsp}{nbsp}b) If a subclass value is not provided, set it to "none"
| {nbsp}{nbsp}{nbsp}c) If a multiplicity value is not provided, set it to "1" 
| {nbsp}{nbsp}{nbsp}d) If the Role Name of a relation is not provided, delete the Role Name row
| {nbsp}{nbsp}{nbsp}e) If the stereotype of an attribute is not provided, set it to <<Property>>
| 2) For all classes with the "CodeList" stereotype 
| {nbsp}{nbsp}{nbsp}a) Copy the name and description into the table in the Code List section
| {nbsp}{nbsp}{nbsp}b) Delete the class
| 3) If there are no code lists, then delete the Code List section
| 4) Delete these instructions when done
|===

==== *Classes*

[[AbstractTransportationSpace-section]]
===== *Class AbstractTransportationSpace*

[cols="1a"]
|===
|*AbstractTransportationSpace* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! AbstractTransportationSpace is the abstract superclass of transportation objects such as Roads, Tracks, Railways, Waterways or Squares. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractUnoccupiedSpace-section,AbstractUnoccupiedSpace>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|{set:cellbgcolor:#FFFFFF} 
|<<TrafficSpace-section,TrafficSpace>> 
|
|{set:cellbgcolor:#FFFFFF} 
|<<Hole-section,Hole>> 
|
|{set:cellbgcolor:#FFFFFF} 
|<<AuxiliaryTrafficSpace-section,AuxiliaryTrafficSpace>> 
|
|{set:cellbgcolor:#FFFFFF} 
|<<Marking-section,Marking>> 
|
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
 
|{set:cellbgcolor:#FFFFFF} occupancy  |<<Occupancy-section,Occupancy>>  [0..*] |Provides information on the residency of persons, vehicles, or other moving features in the transportation space.
 
|{set:cellbgcolor:#FFFFFF} trafficDirection  |<<TrafficDirectionValue-section,TrafficDirectionValue>>  [0..1] |Indicates the direction of traffic flow relative to the corresponding linear geometry representation.
|===
[[AuxiliaryTrafficArea-section]]
===== *Class AuxiliaryTrafficArea*

[cols="1a"]
|===
|*AuxiliaryTrafficArea* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! An AuxiliaryTrafficArea is the ground surface of an AuxiliaryTrafficSpace. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractThematicSurface-section,AbstractThematicSurface>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
 
|{set:cellbgcolor:#FFFFFF} class  |<<AuxiliaryTrafficAreaClassValue-section,AuxiliaryTrafficAreaClassValue>>  [0..1] |Indicates the specific type of the AuxiliaryTrafficArea.
 
|{set:cellbgcolor:#FFFFFF} function  |<<AuxiliaryTrafficAreaFunctionValue-section,AuxiliaryTrafficAreaFunctionValue>>  [0..*] |Specifies the intended purposes of the AuxiliaryTrafficArea.
 
|{set:cellbgcolor:#FFFFFF} surfaceMaterial  |<<SurfaceMaterialValue-section,SurfaceMaterialValue>>  [0..1] |Specifies the type of pavement of the AuxiliaryTrafficArea.
 
|{set:cellbgcolor:#FFFFFF} usage  |<<AuxiliaryTrafficAreaUsageValue-section,AuxiliaryTrafficAreaUsageValue>>  [0..*] |Specifies the actual uses of the AuxiliaryTrafficArea.
|===
[[AuxiliaryTrafficAreaClassValue-section]]
===== *Class AuxiliaryTrafficAreaClassValue*

[cols="1a"]
|===
|*AuxiliaryTrafficAreaClassValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! AuxiliaryTrafficAreaClassValue is a code list used to further classify an AuxiliaryTrafficArea. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
|===
[[AuxiliaryTrafficAreaFunctionValue-section]]
===== *Class AuxiliaryTrafficAreaFunctionValue*

[cols="1a"]
|===
|*AuxiliaryTrafficAreaFunctionValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! AuxiliaryTrafficAreaFunctionValue is a code list that enumerates the different purposes of an AuxiliaryTrafficArea. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
|===
[[AuxiliaryTrafficAreaUsageValue-section]]
===== *Class AuxiliaryTrafficAreaUsageValue*

[cols="1a"]
|===
|*AuxiliaryTrafficAreaUsageValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! AuxiliaryTrafficAreaUsageValue is a code list that enumerates the different uses of an AuxiliaryTrafficArea. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
|===
[[AuxiliaryTrafficSpace-section]]
===== *Class AuxiliaryTrafficSpace*

[cols="1a"]
|===
|*AuxiliaryTrafficSpace* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! An AuxiliaryTrafficSpace is a space within the transportation space not intended for traffic purposes. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractUnoccupiedSpace-section,AbstractUnoccupiedSpace>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|{set:cellbgcolor:#FFFFFF} 
|<<AuxiliaryTrafficArea-section,AuxiliaryTrafficArea>> 
|
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
 
|{set:cellbgcolor:#FFFFFF} class  |<<AuxiliaryTrafficSpaceClassValue-section,AuxiliaryTrafficSpaceClassValue>>  [0..1] |Indicates the specific type of the AuxiliaryTrafficSpace.
 
|{set:cellbgcolor:#FFFFFF} function  |<<AuxiliaryTrafficSpaceFunctionValue-section,AuxiliaryTrafficSpaceFunctionValue>>  [0..*] |Specifies the intended purposes of the AuxiliaryTrafficSpace.
 
|{set:cellbgcolor:#FFFFFF} granularity  |<<GranularityValue-section,GranularityValue>>  |Defines whether auxiliary traffic spaces are represented by individual ways or by individual lanes, depending on the desired level of detail.
 
|{set:cellbgcolor:#FFFFFF} usage  |<<AuxiliaryTrafficSpaceUsageValue-section,AuxiliaryTrafficSpaceUsageValue>>  [0..*] |Specifies the actual uses of the AuxiliaryTrafficSpace.
|===
[[AuxiliaryTrafficSpaceClassValue-section]]
===== *Class AuxiliaryTrafficSpaceClassValue*

[cols="1a"]
|===
|*AuxiliaryTrafficSpaceClassValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! AuxiliaryTrafficSpaceClassValue is a code list used to further classify an AuxiliaryTrafficSpace. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
|===
[[AuxiliaryTrafficSpaceFunctionValue-section]]
===== *Class AuxiliaryTrafficSpaceFunctionValue*

[cols="1a"]
|===
|*AuxiliaryTrafficSpaceFunctionValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! AuxiliaryTrafficSpaceFunctionValue is a code list that enumerates the different purposes of an AuxiliaryTrafficSpace. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
|===
[[AuxiliaryTrafficSpaceUsageValue-section]]
===== *Class AuxiliaryTrafficSpaceUsageValue*

[cols="1a"]
|===
|*AuxiliaryTrafficSpaceUsageValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! AuxiliaryTrafficSpaceUsageValue is a code list that enumerates the different uses of an AuxiliaryTrafficSpace. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
|===
[[ClearanceSpace-section]]
===== *Class ClearanceSpace*

[cols="1a"]
|===
|*ClearanceSpace* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A ClearanceSpace represents the actual free space above a TrafficArea within which a mobile object can move without contacting an obstruction. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractUnoccupiedSpace-section,AbstractUnoccupiedSpace>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
 
|{set:cellbgcolor:#FFFFFF} class  |<<ClearanceSpaceClassValue-section,ClearanceSpaceClassValue>>  [0..*] |Indicates the specific type of the ClearanceSpace.
|===
[[ClearanceSpaceClassValue-section]]
===== *Class ClearanceSpaceClassValue*

[cols="1a"]
|===
|*ClearanceSpaceClassValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! ClearanceSpaceClassValue is a code list used to further classify a ClearanceSpace. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
|===
[[Hole-section]]
===== *Class Hole*

[cols="1a"]
|===
|*Hole* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A Hole is an opening in the surface of a Road, Track or Square such as road damages, manholes or drains. Holes can span multiple transportation objects. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractUnoccupiedSpace-section,AbstractUnoccupiedSpace>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|{set:cellbgcolor:#FFFFFF} 
|<<AbstractThematicSurface-section,AbstractThematicSurface>> 
|
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
 
|{set:cellbgcolor:#FFFFFF} class  |<<HoleClassValue-section,HoleClassValue>>  [0..1] |Indicates the specific type of the Hole.
|===
[[HoleClassValue-section]]
===== *Class HoleClassValue*

[cols="1a"]
|===
|*HoleClassValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! HoleClassValue is a code list used to further classify a Hole. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
|===
[[HoleSurface-section]]
===== *Class HoleSurface*

[cols="1a"]
|===
|*HoleSurface* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A HoleSurface is a representation of the ground surface of a hole. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractThematicSurface-section,AbstractThematicSurface>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
|===
[[Intersection-section]]
===== *Class Intersection*

[cols="1a"]
|===
|*Intersection* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! An Intersection is a transportation space that is a shared segment of multiple Road, Track, Railway, or Waterway objects (e.g. a crossing of two roads or a level crossing of a road and a railway). 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractTransportationSpace-section,AbstractTransportationSpace>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
 
|{set:cellbgcolor:#FFFFFF} class  |<<IntersectionClassValue-section,IntersectionClassValue>>  [0..1] |Indicates the specific type of the Intersection.
|===
[[IntersectionClassValue-section]]
===== *Class IntersectionClassValue*

[cols="1a"]
|===
|*IntersectionClassValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! IntersectionClassValue is a code list used to further classify an Intersection. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
|===
[[Marking-section]]
===== *Class Marking*

[cols="1a"]
|===
|*Marking* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A Marking is a visible pattern on a transportation area relevant to the structuring or restriction of traffic. Examples are road markings and markings related to railway or waterway traffic. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractThematicSurface-section,AbstractThematicSurface>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
 
|{set:cellbgcolor:#FFFFFF} class  |<<MarkingClassValue-section,MarkingClassValue>>  [0..1] |Indicates the specific type of the Marking.
|===
[[MarkingClassValue-section]]
===== *Class MarkingClassValue*

[cols="1a"]
|===
|*MarkingClassValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! MarkingClassValue is a code list used to further classify a Marking. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
|===
[[Railway-section]]
===== *Class Railway*

[cols="1a"]
|===
|*Railway* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A Railway is a transportation space used by wheeled vehicles on rails. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractTransportationSpace-section,AbstractTransportationSpace>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «TopLevelFeatureType»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|{set:cellbgcolor:#FFFFFF} 
|<<Section-section,Section>> 
|
|{set:cellbgcolor:#FFFFFF} 
|<<Intersection-section,Intersection>> 
|
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
 
|{set:cellbgcolor:#FFFFFF} class  |<<RailwayClassValue-section,RailwayClassValue>>  [0..1] |Indicates the specific type of the Railway.
 
|{set:cellbgcolor:#FFFFFF} function  |<<RailwayFunctionValue-section,RailwayFunctionValue>>  [0..*] |Specifies the intended purposes of the Railway.
 
|{set:cellbgcolor:#FFFFFF} usage  |<<RailwayUsageValue-section,RailwayUsageValue>>  [0..*] |Specifies the actual uses of the Railway.
|===
[[RailwayClassValue-section]]
===== *Class RailwayClassValue*

[cols="1a"]
|===
|*RailwayClassValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! RailwayClassValue is a code list used to further classify a Railway. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
|===
[[RailwayFunctionValue-section]]
===== *Class RailwayFunctionValue*

[cols="1a"]
|===
|*RailwayFunctionValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! RailwayFunctionValue is a code list that enumerates the different purposes of a Railway. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
|===
[[RailwayUsageValue-section]]
===== *Class RailwayUsageValue*

[cols="1a"]
|===
|*RailwayUsageValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! RailwayUsageValue is a code list that enumerates the different uses of a Railway. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
|===
[[Road-section]]
===== *Class Road*

[cols="1a"]
|===
|*Road* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A Road is a transportation space used by vehicles, bicycles and/or pedestrians. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractTransportationSpace-section,AbstractTransportationSpace>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «TopLevelFeatureType»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|{set:cellbgcolor:#FFFFFF} 
|<<Intersection-section,Intersection>> 
|
|{set:cellbgcolor:#FFFFFF} 
|<<Section-section,Section>> 
|
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
 
|{set:cellbgcolor:#FFFFFF} class  |<<RoadClassValue-section,RoadClassValue>>  [0..1] |Indicates the specific type of the Road.
 
|{set:cellbgcolor:#FFFFFF} function  |<<RoadFunctionValue-section,RoadFunctionValue>>  [0..*] |Specifies the intended purposes of the Road.
 
|{set:cellbgcolor:#FFFFFF} usage  |<<RoadUsageValue-section,RoadUsageValue>>  [0..*] |Specifies the actual uses of the Road.
|===
[[RoadClassValue-section]]
===== *Class RoadClassValue*

[cols="1a"]
|===
|*RoadClassValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! RoadClassValue is a code list used to further classify a Road. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
|===
[[RoadFunctionValue-section]]
===== *Class RoadFunctionValue*

[cols="1a"]
|===
|*RoadFunctionValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! RoadFunctionValue is a code list that enumerates the different purposes of a Road. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
|===
[[RoadUsageValue-section]]
===== *Class RoadUsageValue*

[cols="1a"]
|===
|*RoadUsageValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! RoadUsageValue is a code list that enumerates the different uses of a Road. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
|===
[[Section-section]]
===== *Class Section*

[cols="1a"]
|===
|*Section* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A Section is a transportation space that is a segment of a Road, Railway, Track, or Waterway. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractTransportationSpace-section,AbstractTransportationSpace>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
 
|{set:cellbgcolor:#FFFFFF} class  |<<SectionClassValue-section,SectionClassValue>>  [0..1] |Indicates the specific type of the Section.
|===
[[SectionClassValue-section]]
===== *Class SectionClassValue*

[cols="1a"]
|===
|*SectionClassValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! SectionClassValue is a code list used to further classify a Section. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
|===
[[Square-section]]
===== *Class Square*

[cols="1a"]
|===
|*Square* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A Square is a transportation space for unrestricted movement for vehicles, bicycles and/or pedestrians. This includes plazas as well as large sealed surfaces such as parking lots. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractTransportationSpace-section,AbstractTransportationSpace>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «TopLevelFeatureType»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
 
|{set:cellbgcolor:#FFFFFF} class  |<<SquareClassValue-section,SquareClassValue>>  [0..1] |Indicates the specific type of the Square.
 
|{set:cellbgcolor:#FFFFFF} function  |<<SquareFunctionValue-section,SquareFunctionValue>>  [0..*] |Specifies the intended purposes of the Square.
 
|{set:cellbgcolor:#FFFFFF} usage  |<<SquareUsageValue-section,SquareUsageValue>>  [0..*] |Specifies the actual uses of the Square.
|===
[[SquareClassValue-section]]
===== *Class SquareClassValue*

[cols="1a"]
|===
|*SquareClassValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! SquareClassValue is a code list used to further classify a Square. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
|===
[[SquareFunctionValue-section]]
===== *Class SquareFunctionValue*

[cols="1a"]
|===
|*SquareFunctionValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! SquareFunctionValue is a code list that enumerates the different purposes of a Square. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
|===
[[SquareUsageValue-section]]
===== *Class SquareUsageValue*

[cols="1a"]
|===
|*SquareUsageValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! SquareUsageValue is a code list that enumerates the different uses of a Square. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
|===
[[SurfaceMaterialValue-section]]
===== *Class SurfaceMaterialValue*

[cols="1a"]
|===
|*SurfaceMaterialValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! SurfaceMaterialValue is a code list that enumerates the different surface materials. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
|===
[[Track-section]]
===== *Class Track*

[cols="1a"]
|===
|*Track* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A Track is a small path mainly used by pedestrians. Tracks can be segmented into Sections and Intersections. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractTransportationSpace-section,AbstractTransportationSpace>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «TopLevelFeatureType»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|{set:cellbgcolor:#FFFFFF} 
|<<Section-section,Section>> 
|
|{set:cellbgcolor:#FFFFFF} 
|<<Intersection-section,Intersection>> 
|
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
 
|{set:cellbgcolor:#FFFFFF} class  |<<TrackClassValue-section,TrackClassValue>>  [0..1] |Indicates the specific type of the Track.
 
|{set:cellbgcolor:#FFFFFF} function  |<<TrackFunctionValue-section,TrackFunctionValue>>  [0..*] |Specifies the intended purposes of the Track.
 
|{set:cellbgcolor:#FFFFFF} usage  |<<TrackUsageValue-section,TrackUsageValue>>  [0..*] |Specifies the actual uses of the Track.
|===
[[TrackClassValue-section]]
===== *Class TrackClassValue*

[cols="1a"]
|===
|*TrackClassValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! TrackClassValue is a code list used to further classify a Track. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
|===
[[TrackFunctionValue-section]]
===== *Class TrackFunctionValue*

[cols="1a"]
|===
|*TrackFunctionValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! TrackFunctionValue is a code list that enumerates the different purposes of a Track. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
|===
[[TrackUsageValue-section]]
===== *Class TrackUsageValue*

[cols="1a"]
|===
|*TrackUsageValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! TrackUsageValue is a code list that enumerates the different uses of a Track. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
|===
[[TrafficArea-section]]
===== *Class TrafficArea*

[cols="1a"]
|===
|*TrafficArea* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A TrafficArea is the ground surface of a TrafficSpace. Traffic areas are the surfaces upon which traffic actually takes place. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractThematicSurface-section,AbstractThematicSurface>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
 
|{set:cellbgcolor:#FFFFFF} class  |<<TrafficAreaClassValue-section,TrafficAreaClassValue>>  [0..1] |Indicates the specific type of the TrafficArea.
 
|{set:cellbgcolor:#FFFFFF} function  |<<TrafficAreaFunctionValue-section,TrafficAreaFunctionValue>>  [0..*] |Specifies the intended purposes of the TrafficArea.
 
|{set:cellbgcolor:#FFFFFF} surfaceMaterial  |<<SurfaceMaterialValue-section,SurfaceMaterialValue>>  [0..1] |Specifies the type of pavement of the TrafficArea.
 
|{set:cellbgcolor:#FFFFFF} usage  |<<TrafficAreaUsageValue-section,TrafficAreaUsageValue>>  [0..*] |Specifies the actual uses of the TrafficArea.
|===
[[TrafficAreaClassValue-section]]
===== *Class TrafficAreaClassValue*

[cols="1a"]
|===
|*TrafficAreaClassValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! TrafficAreaClassValue is a code list used to further classify a TrafficArea. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
|===
[[TrafficAreaFunctionValue-section]]
===== *Class TrafficAreaFunctionValue*

[cols="1a"]
|===
|*TrafficAreaFunctionValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! TrafficAreaFunctionValue is a code list that enumerates the different purposes of a TrafficArea. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
|===
[[TrafficAreaUsageValue-section]]
===== *Class TrafficAreaUsageValue*

[cols="1a"]
|===
|*TrafficAreaUsageValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! TrafficAreaUsageValue is a code list that enumerates the different uses of a TrafficArea. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
|===
[[TrafficSpace-section]]
===== *Class TrafficSpace*

[cols="1a"]
|===
|*TrafficSpace* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A TrafficSpace is a space in which traffic takes place. Traffic includes the movement of entities such as trains, vehicles, pedestrians, ships, or other transportation types.  
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractUnoccupiedSpace-section,AbstractUnoccupiedSpace>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|{set:cellbgcolor:#FFFFFF} 
|<<ClearanceSpace-section,ClearanceSpace>> 
|
|{set:cellbgcolor:#FFFFFF} 
|<<TrafficSpace-section,TrafficSpace>> 
|
|{set:cellbgcolor:#FFFFFF} 
|<<TrafficArea-section,TrafficArea>> 
|
|{set:cellbgcolor:#FFFFFF} 
|<<TrafficSpace-section,TrafficSpace>> 
|
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
 
|{set:cellbgcolor:#FFFFFF} class  |<<TrafficSpaceClassValue-section,TrafficSpaceClassValue>>  [0..1] |Indicates the specific type of the TrafficSpace.
 
|{set:cellbgcolor:#FFFFFF} function  |<<TrafficSpaceFunctionValue-section,TrafficSpaceFunctionValue>>  [0..*] |Specifies the intended purposes of the TrafficSpace.
 
|{set:cellbgcolor:#FFFFFF} granularity  |<<GranularityValue-section,GranularityValue>>  |Defines whether traffic spaces are represented by individual ways or by individual lanes, depending on the desired level of detail.
 
|{set:cellbgcolor:#FFFFFF} occupancy  |<<Occupancy-section,Occupancy>>  [0..*] |Provides information on the residency of persons, vehicles, or other moving features in the TrafficSpace.
 
|{set:cellbgcolor:#FFFFFF} trafficDirection  |<<TrafficDirectionValue-section,TrafficDirectionValue>>  [0..1] |Indicates the direction of traffic flow relative to the corresponding linear geometry representation.
 
|{set:cellbgcolor:#FFFFFF} usage  |<<TrafficSpaceUsageValue-section,TrafficSpaceUsageValue>>  [0..*] |Specifies the actual uses of the TrafficSpace.
|===
[[TrafficSpaceClassValue-section]]
===== *Class TrafficSpaceClassValue*

[cols="1a"]
|===
|*TrafficSpaceClassValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! TrafficSpaceClassValue is a code list used to further classify a TrafficSpace. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
|===
[[TrafficSpaceFunctionValue-section]]
===== *Class TrafficSpaceFunctionValue*

[cols="1a"]
|===
|*TrafficSpaceFunctionValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! TrafficSpaceFunctionValue is a code list that enumerates the different purposes of a TrafficSpace. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
|===
[[TrafficSpaceUsageValue-section]]
===== *Class TrafficSpaceUsageValue*

[cols="1a"]
|===
|*TrafficSpaceUsageValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! TrafficSpaceUsageValue is a code list that enumerates the different uses of a TrafficSpace. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
|===
[[TransportationSpaceClassValue-section]]
===== *Class TransportationSpaceClassValue*

[cols="1a"]
|===
|*TransportationSpaceClassValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! TransportationSpaceClassValue is a code list used to further classify a TransportationSpace. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
|===
[[TransportationSpaceFunctionValue-section]]
===== *Class TransportationSpaceFunctionValue*

[cols="1a"]
|===
|*TransportationSpaceFunctionValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! TransportationSpaceFunctionValue is a code list that enumerates the different purposes of a TransportationSpace. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
|===
[[TransportationSpaceUsageValue-section]]
===== *Class TransportationSpaceUsageValue*

[cols="1a"]
|===
|*TransportationSpaceUsageValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! TransportationSpaceUsageValue is a code list that enumerates the different uses of a TransportationSpace. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
|===
[[Waterway-section]]
===== *Class Waterway*

[cols="1a"]
|===
|*Waterway* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A Waterway is a transportation space used for the movement of vessels upon or within a water body. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractTransportationSpace-section,AbstractTransportationSpace>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «TopLevelFeatureType»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|{set:cellbgcolor:#FFFFFF} 
|<<Section-section,Section>> 
|
|{set:cellbgcolor:#FFFFFF} 
|<<Intersection-section,Intersection>> 
|
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
 
|{set:cellbgcolor:#FFFFFF} class  |<<WaterwayClassValue-section,WaterwayClassValue>>  [0..1] |Indicates the specific type of the Waterway.
 
|{set:cellbgcolor:#FFFFFF} function  |<<WaterwayFunctionValue-section,WaterwayFunctionValue>>  [0..*] |Specifies the intended purposes of the Waterway.
 
|{set:cellbgcolor:#FFFFFF} usage  |<<WaterwayUsageValue-section,WaterwayUsageValue>>  [0..*] |Specifies the actual uses of the Waterway.
|===
[[WaterwayClassValue-section]]
===== *Class WaterwayClassValue*

[cols="1a"]
|===
|*WaterwayClassValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! WaterwayClassValue is a code list used to further classify a Waterway. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
|===
[[WaterwayFunctionValue-section]]
===== *Class WaterwayFunctionValue*

[cols="1a"]
|===
|*WaterwayFunctionValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! WaterwayFunctionValue is a code list that enumerates the different purposes of a Waterway. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
|===
[[WaterwayUsageValue-section]]
===== *Class WaterwayUsageValue*

[cols="1a"]
|===
|*WaterwayUsageValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! WaterwayUsageValue is a code list that enumerates the different uses of a Waterway. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
|===
[[GranularityValue-section]]
===== *Class GranularityValue*

[cols="1a"]
|===
|*GranularityValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! GranularityValue enumerates the different levels of granularity in which transportation objects are represented. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
 
|{set:cellbgcolor:#FFFFFF} lane  |<<-section,>>  |Indicates that the individual lanes of the transportation object are represented. 
 
|{set:cellbgcolor:#FFFFFF} way  |<<-section,>>  |Indicates that the individual (carriage)ways of the transportation object are represented.
|===
[[TrafficDirectionValue-section]]
===== *Class TrafficDirectionValue*

[cols="1a"]
|===
|*TrafficDirectionValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! TrafficDirectionValue enumerates the allowed directions of travel of a mobile object. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
 
|{set:cellbgcolor:#FFFFFF} forwards  |<<-section,>>  |Indicates that traffic flows in the direction of the corresponding linear geometry.
 
|{set:cellbgcolor:#FFFFFF} backwards  |<<-section,>>  |Indicates that traffic flows in the opposite direction of the corresponding linear geometry.
 
|{set:cellbgcolor:#FFFFFF} both  |<<-section,>>  |Indicates that traffic flows in both directions.
|===

==== *Code Lists*

[cols="1,4"]  
|===
^|*Code List* ^|*Definition*
| |
| |
|===
  



