[[Transportation-package]]
==== *Transportation Package*

|====
|*Package Transportation*
|Description:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}The Transportation module supports representation of the transportation infrastructure. Transportation features include roads, tracks, waterways, railways, and squares. Transportation features may be represented as a network and/or as a collection of spaces or surface elements embedded in a three-dimensional space. +
Stereotype:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}«ApplicationSchema» +
Parent Package: {nbsp}{nbsp}CityGML
|====

[[AbstractTransportationSpace-section]]
==== *Class AbstractTransportationSpace*

include::../requirements/Transportation/REQ_Transportation_AbstractTransportationSpace.adoc[]

|====
|*Class AbstractTransportationSpace* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} AbstractTransportationSpace is the abstract superclass of transportation objects such as Roads, Tracks, Railways, Waterways or Squares. +
Subclass Of: {nbsp}{nbsp} <<AbstractUnoccupiedSpace-section,AbstractUnoccupiedSpace>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «FeatureType»
|*Relations* 
|Relation Name: {nbsp}{nbsp} trafficSpace +
Cardinality:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  * +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} <<TrafficSpace-section,TrafficSpace>>  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Relates to the traffic spaces that are part of the transportation space. +
|Relation Name: {nbsp}{nbsp} hole +
Cardinality:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  * +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} <<Hole-section,Hole>>  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Relates to the holes that are part of the transportation space. +
|Relation Name: {nbsp}{nbsp} auxiliaryTrafficSpace +
Cardinality:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  * +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} <<AuxiliaryTrafficSpace-section,AuxiliaryTrafficSpace>>  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Relates to the auxiliary traffic spaces that are part of the transportation space. +
|Relation Name: {nbsp}{nbsp} marking +
Cardinality:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  * +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} <<Marking-section,Marking>>  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Relates to the markings that are part of the transportation space. +
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}occupancy +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Occupancy +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Provides information on the residency of persons, vehicles, or other moving features in the transportation space.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}trafficDirection +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TrafficDirectionValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Indicates the direction of traffic flow relative to the corresponding linear geometry representation.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|
|==== 

[[AuxiliaryTrafficArea-section]]
==== *Class AuxiliaryTrafficArea*

include::../requirements/Transportation/REQ_Transportation_AuxiliaryTrafficArea.adoc[]

|====
|*Class AuxiliaryTrafficArea* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} An AuxiliaryTrafficArea is the ground surface of an AuxiliaryTrafficSpace. +
Subclass Of: {nbsp}{nbsp} <<AbstractThematicSurface-section,AbstractThematicSurface>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «FeatureType»
|*Relations* 
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}class +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} AuxiliaryTrafficAreaClassValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Indicates the specific type of the AuxiliaryTrafficArea.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}function +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} AuxiliaryTrafficAreaFunctionValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Specifies the intended purposes of the AuxiliaryTrafficArea.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}surfaceMaterial +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} SurfaceMaterialValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Specifies the type of pavement of the AuxiliaryTrafficArea.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}usage +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} AuxiliaryTrafficAreaUsageValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Specifies the actual uses of the AuxiliaryTrafficArea.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|
|==== 

[[AuxiliaryTrafficAreaClassValue-section]]
==== *Class AuxiliaryTrafficAreaClassValue*

include::../requirements/Transportation/REQ_Transportation_AuxiliaryTrafficAreaClassValue.adoc[]

|====
|*Class AuxiliaryTrafficAreaClassValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} AuxiliaryTrafficAreaClassValue is a code list used to further classify an AuxiliaryTrafficArea. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[AuxiliaryTrafficAreaFunctionValue-section]]
==== *Class AuxiliaryTrafficAreaFunctionValue*

include::../requirements/Transportation/REQ_Transportation_AuxiliaryTrafficAreaFunctionValue.adoc[]

|====
|*Class AuxiliaryTrafficAreaFunctionValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} AuxiliaryTrafficAreaFunctionValue is a code list that enumerates the different purposes of an AuxiliaryTrafficArea. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[AuxiliaryTrafficAreaUsageValue-section]]
==== *Class AuxiliaryTrafficAreaUsageValue*

include::../requirements/Transportation/REQ_Transportation_AuxiliaryTrafficAreaUsageValue.adoc[]

|====
|*Class AuxiliaryTrafficAreaUsageValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} AuxiliaryTrafficAreaUsageValue is a code list that enumerates the different uses of an AuxiliaryTrafficArea. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[AuxiliaryTrafficSpace-section]]
==== *Class AuxiliaryTrafficSpace*

include::../requirements/Transportation/REQ_Transportation_AuxiliaryTrafficSpace.adoc[]

|====
|*Class AuxiliaryTrafficSpace* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} An AuxiliaryTrafficSpace is a space within the transportation space not intended for traffic purposes. +
Subclass Of: {nbsp}{nbsp} <<AbstractUnoccupiedSpace-section,AbstractUnoccupiedSpace>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «FeatureType»
|*Relations* 
|Relation Name: {nbsp}{nbsp} boundary +
Cardinality:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  * +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} <<AuxiliaryTrafficArea-section,AuxiliaryTrafficArea>>  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}class +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} AuxiliaryTrafficSpaceClassValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Indicates the specific type of the AuxiliaryTrafficSpace.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}function +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} AuxiliaryTrafficSpaceFunctionValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Specifies the intended purposes of the AuxiliaryTrafficSpace.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}granularity +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} GranularityValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Defines whether auxiliary traffic spaces are represented by individual ways or by individual lanes, depending on the desired level of detail.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}usage +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} AuxiliaryTrafficSpaceUsageValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Specifies the actual uses of the AuxiliaryTrafficSpace.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|
|==== 

[[AuxiliaryTrafficSpaceClassValue-section]]
==== *Class AuxiliaryTrafficSpaceClassValue*

include::../requirements/Transportation/REQ_Transportation_AuxiliaryTrafficSpaceClassValue.adoc[]

|====
|*Class AuxiliaryTrafficSpaceClassValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} AuxiliaryTrafficSpaceClassValue is a code list used to further classify an AuxiliaryTrafficSpace. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[AuxiliaryTrafficSpaceFunctionValue-section]]
==== *Class AuxiliaryTrafficSpaceFunctionValue*

include::../requirements/Transportation/REQ_Transportation_AuxiliaryTrafficSpaceFunctionValue.adoc[]

|====
|*Class AuxiliaryTrafficSpaceFunctionValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} AuxiliaryTrafficSpaceFunctionValue is a code list that enumerates the different purposes of an AuxiliaryTrafficSpace. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[AuxiliaryTrafficSpaceUsageValue-section]]
==== *Class AuxiliaryTrafficSpaceUsageValue*

include::../requirements/Transportation/REQ_Transportation_AuxiliaryTrafficSpaceUsageValue.adoc[]

|====
|*Class AuxiliaryTrafficSpaceUsageValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} AuxiliaryTrafficSpaceUsageValue is a code list that enumerates the different uses of an AuxiliaryTrafficSpace. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[ClearanceSpace-section]]
==== *Class ClearanceSpace*

include::../requirements/Transportation/REQ_Transportation_ClearanceSpace.adoc[]

|====
|*Class ClearanceSpace* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} A ClearanceSpace represents the actual free space above a TrafficArea within which a mobile object can move without contacting an obstruction. +
Subclass Of: {nbsp}{nbsp} <<AbstractUnoccupiedSpace-section,AbstractUnoccupiedSpace>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «FeatureType»
|*Relations* 
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}class +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} ClearanceSpaceClassValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Indicates the specific type of the ClearanceSpace.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|
|==== 

[[ClearanceSpaceClassValue-section]]
==== *Class ClearanceSpaceClassValue*

include::../requirements/Transportation/REQ_Transportation_ClearanceSpaceClassValue.adoc[]

|====
|*Class ClearanceSpaceClassValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} ClearanceSpaceClassValue is a code list used to further classify a ClearanceSpace. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[Hole-section]]
==== *Class Hole*

include::../requirements/Transportation/REQ_Transportation_Hole.adoc[]

|====
|*Class Hole* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} A Hole is an opening in the surface of a Road, Track or Square such as road damages, manholes or drains. Holes can span multiple transportation objects. +
Subclass Of: {nbsp}{nbsp} <<AbstractUnoccupiedSpace-section,AbstractUnoccupiedSpace>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «FeatureType»
|*Relations* 
|Relation Name: {nbsp}{nbsp} boundary +
Cardinality:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  * +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} <<AbstractThematicSurface-section,AbstractThematicSurface>>  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}class +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} HoleClassValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Indicates the specific type of the Hole.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|
|==== 

[[HoleClassValue-section]]
==== *Class HoleClassValue*

include::../requirements/Transportation/REQ_Transportation_HoleClassValue.adoc[]

|====
|*Class HoleClassValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} HoleClassValue is a code list used to further classify a Hole. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[HoleSurface-section]]
==== *Class HoleSurface*

include::../requirements/Transportation/REQ_Transportation_HoleSurface.adoc[]

|====
|*Class HoleSurface* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} A HoleSurface is a representation of the ground surface of a hole. +
Subclass Of: {nbsp}{nbsp} <<AbstractThematicSurface-section,AbstractThematicSurface>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «FeatureType»
|*Relations* 
|*Attributes*
|
|==== 

[[Intersection-section]]
==== *Class Intersection*

include::../requirements/Transportation/REQ_Transportation_Intersection.adoc[]

|====
|*Class Intersection* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} An Intersection is a transportation space that is a shared segment of multiple Road, Track, Railway, or Waterway objects (e.g. a crossing of two roads or a level crossing of a road and a railway). +
Subclass Of: {nbsp}{nbsp} <<AbstractTransportationSpace-section,AbstractTransportationSpace>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «FeatureType»
|*Relations* 
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}class +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} IntersectionClassValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Indicates the specific type of the Intersection.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|
|==== 

[[IntersectionClassValue-section]]
==== *Class IntersectionClassValue*

include::../requirements/Transportation/REQ_Transportation_IntersectionClassValue.adoc[]

|====
|*Class IntersectionClassValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} IntersectionClassValue is a code list used to further classify an Intersection. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[Marking-section]]
==== *Class Marking*

include::../requirements/Transportation/REQ_Transportation_Marking.adoc[]

|====
|*Class Marking* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} A Marking is a visible pattern on a transportation area relevant to the structuring or restriction of traffic. Examples are road markings and markings related to railway or waterway traffic. +
Subclass Of: {nbsp}{nbsp} <<AbstractThematicSurface-section,AbstractThematicSurface>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «FeatureType»
|*Relations* 
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}class +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} MarkingClassValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Indicates the specific type of the Marking.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|
|==== 

[[MarkingClassValue-section]]
==== *Class MarkingClassValue*

include::../requirements/Transportation/REQ_Transportation_MarkingClassValue.adoc[]

|====
|*Class MarkingClassValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} MarkingClassValue is a code list used to further classify a Marking. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[Railway-section]]
==== *Class Railway*

include::../requirements/Transportation/REQ_Transportation_Railway.adoc[]

|====
|*Class Railway* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} A Railway is a transportation space used by wheeled vehicles on rails. +
Subclass Of: {nbsp}{nbsp} <<AbstractTransportationSpace-section,AbstractTransportationSpace>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «TopLevelFeatureType»
|*Relations* 
|Relation Name: {nbsp}{nbsp} section +
Cardinality:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  * +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} <<Section-section,Section>>  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Relates to the sections that are part of the Railway. +
|Relation Name: {nbsp}{nbsp} intersection +
Cardinality:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  * +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} <<Intersection-section,Intersection>>  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Relates to the intersections that are part of the Railway. +
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}class +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} RailwayClassValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Indicates the specific type of the Railway.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}function +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} RailwayFunctionValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Specifies the intended purposes of the Railway.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}usage +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} RailwayUsageValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Specifies the actual uses of the Railway.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|
|==== 

[[RailwayClassValue-section]]
==== *Class RailwayClassValue*

include::../requirements/Transportation/REQ_Transportation_RailwayClassValue.adoc[]

|====
|*Class RailwayClassValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} RailwayClassValue is a code list used to further classify a Railway. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[RailwayFunctionValue-section]]
==== *Class RailwayFunctionValue*

include::../requirements/Transportation/REQ_Transportation_RailwayFunctionValue.adoc[]

|====
|*Class RailwayFunctionValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} RailwayFunctionValue is a code list that enumerates the different purposes of a Railway. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[RailwayUsageValue-section]]
==== *Class RailwayUsageValue*

include::../requirements/Transportation/REQ_Transportation_RailwayUsageValue.adoc[]

|====
|*Class RailwayUsageValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} RailwayUsageValue is a code list that enumerates the different uses of a Railway. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[Road-section]]
==== *Class Road*

include::../requirements/Transportation/REQ_Transportation_Road.adoc[]

|====
|*Class Road* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} A Road is a transportation space used by vehicles, bicycles and/or pedestrians. +
Subclass Of: {nbsp}{nbsp} <<AbstractTransportationSpace-section,AbstractTransportationSpace>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «TopLevelFeatureType»
|*Relations* 
|Relation Name: {nbsp}{nbsp} intersection +
Cardinality:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  * +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} <<Intersection-section,Intersection>>  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Relates to the intersections that are part of the Road. +
|Relation Name: {nbsp}{nbsp} section +
Cardinality:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  * +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} <<Section-section,Section>>  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Relates to the sections that are part of the Road. +
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}class +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} RoadClassValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Indicates the specific type of the Road.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}function +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} RoadFunctionValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Specifies the intended purposes of the Road.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}usage +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} RoadUsageValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Specifies the actual uses of the Road.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|
|==== 

[[RoadClassValue-section]]
==== *Class RoadClassValue*

include::../requirements/Transportation/REQ_Transportation_RoadClassValue.adoc[]

|====
|*Class RoadClassValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} RoadClassValue is a code list used to further classify a Road. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[RoadFunctionValue-section]]
==== *Class RoadFunctionValue*

include::../requirements/Transportation/REQ_Transportation_RoadFunctionValue.adoc[]

|====
|*Class RoadFunctionValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} RoadFunctionValue is a code list that enumerates the different purposes of a Road. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[RoadUsageValue-section]]
==== *Class RoadUsageValue*

include::../requirements/Transportation/REQ_Transportation_RoadUsageValue.adoc[]

|====
|*Class RoadUsageValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} RoadUsageValue is a code list that enumerates the different uses of a Road. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[Section-section]]
==== *Class Section*

include::../requirements/Transportation/REQ_Transportation_Section.adoc[]

|====
|*Class Section* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} A Section is a transportation space that is a segment of a Road, Railway, Track, or Waterway. +
Subclass Of: {nbsp}{nbsp} <<AbstractTransportationSpace-section,AbstractTransportationSpace>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «FeatureType»
|*Relations* 
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}class +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} SectionClassValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Indicates the specific type of the Section.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|
|==== 

[[SectionClassValue-section]]
==== *Class SectionClassValue*

include::../requirements/Transportation/REQ_Transportation_SectionClassValue.adoc[]

|====
|*Class SectionClassValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} SectionClassValue is a code list used to further classify a Section. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[Square-section]]
==== *Class Square*

include::../requirements/Transportation/REQ_Transportation_Square.adoc[]

|====
|*Class Square* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} A Square is a transportation space for unrestricted movement for vehicles, bicycles and/or pedestrians. This includes plazas as well as large sealed surfaces such as parking lots. +
Subclass Of: {nbsp}{nbsp} <<AbstractTransportationSpace-section,AbstractTransportationSpace>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «TopLevelFeatureType»
|*Relations* 
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}class +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} SquareClassValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Indicates the specific type of the Square.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}function +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} SquareFunctionValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Specifies the intended purposes of the Square.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}usage +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} SquareUsageValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Specifies the actual uses of the Square.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|
|==== 

[[SquareClassValue-section]]
==== *Class SquareClassValue*

include::../requirements/Transportation/REQ_Transportation_SquareClassValue.adoc[]

|====
|*Class SquareClassValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} SquareClassValue is a code list used to further classify a Square. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[SquareFunctionValue-section]]
==== *Class SquareFunctionValue*

include::../requirements/Transportation/REQ_Transportation_SquareFunctionValue.adoc[]

|====
|*Class SquareFunctionValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} SquareFunctionValue is a code list that enumerates the different purposes of a Square. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[SquareUsageValue-section]]
==== *Class SquareUsageValue*

include::../requirements/Transportation/REQ_Transportation_SquareUsageValue.adoc[]

|====
|*Class SquareUsageValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} SquareUsageValue is a code list that enumerates the different uses of a Square. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[SurfaceMaterialValue-section]]
==== *Class SurfaceMaterialValue*

include::../requirements/Transportation/REQ_Transportation_SurfaceMaterialValue.adoc[]

|====
|*Class SurfaceMaterialValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} SurfaceMaterialValue is a code list that enumerates the different surface materials. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[Track-section]]
==== *Class Track*

include::../requirements/Transportation/REQ_Transportation_Track.adoc[]

|====
|*Class Track* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} A Track is a small path mainly used by pedestrians. Tracks can be segmented into Sections and Intersections. +
Subclass Of: {nbsp}{nbsp} <<AbstractTransportationSpace-section,AbstractTransportationSpace>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «TopLevelFeatureType»
|*Relations* 
|Relation Name: {nbsp}{nbsp} section +
Cardinality:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  * +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} <<Section-section,Section>>  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Relates to the sections that are part of the Track. +
|Relation Name: {nbsp}{nbsp} intersection +
Cardinality:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  * +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} <<Intersection-section,Intersection>>  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Relates to the intersections that are part of the Track. +
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}class +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TrackClassValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Indicates the specific type of the Track.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}function +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TrackFunctionValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Specifies the intended purposes of the Track.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}usage +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TrackUsageValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Specifies the actual uses of the Track.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|
|==== 

[[TrackClassValue-section]]
==== *Class TrackClassValue*

include::../requirements/Transportation/REQ_Transportation_TrackClassValue.adoc[]

|====
|*Class TrackClassValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TrackClassValue is a code list used to further classify a Track. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[TrackFunctionValue-section]]
==== *Class TrackFunctionValue*

include::../requirements/Transportation/REQ_Transportation_TrackFunctionValue.adoc[]

|====
|*Class TrackFunctionValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TrackFunctionValue is a code list that enumerates the different purposes of a Track. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[TrackUsageValue-section]]
==== *Class TrackUsageValue*

include::../requirements/Transportation/REQ_Transportation_TrackUsageValue.adoc[]

|====
|*Class TrackUsageValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TrackUsageValue is a code list that enumerates the different uses of a Track. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[TrafficArea-section]]
==== *Class TrafficArea*

include::../requirements/Transportation/REQ_Transportation_TrafficArea.adoc[]

|====
|*Class TrafficArea* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} A TrafficArea is the ground surface of a TrafficSpace. Traffic areas are the surfaces upon which traffic actually takes place. +
Subclass Of: {nbsp}{nbsp} <<AbstractThematicSurface-section,AbstractThematicSurface>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «FeatureType»
|*Relations* 
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}class +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TrafficAreaClassValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Indicates the specific type of the TrafficArea.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}function +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TrafficAreaFunctionValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Specifies the intended purposes of the TrafficArea.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}surfaceMaterial +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} SurfaceMaterialValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Specifies the type of pavement of the TrafficArea.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}usage +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TrafficAreaUsageValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Specifies the actual uses of the TrafficArea.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|
|==== 

[[TrafficAreaClassValue-section]]
==== *Class TrafficAreaClassValue*

include::../requirements/Transportation/REQ_Transportation_TrafficAreaClassValue.adoc[]

|====
|*Class TrafficAreaClassValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TrafficAreaClassValue is a code list used to further classify a TrafficArea. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[TrafficAreaFunctionValue-section]]
==== *Class TrafficAreaFunctionValue*

include::../requirements/Transportation/REQ_Transportation_TrafficAreaFunctionValue.adoc[]

|====
|*Class TrafficAreaFunctionValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TrafficAreaFunctionValue is a code list that enumerates the different purposes of a TrafficArea. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[TrafficAreaUsageValue-section]]
==== *Class TrafficAreaUsageValue*

include::../requirements/Transportation/REQ_Transportation_TrafficAreaUsageValue.adoc[]

|====
|*Class TrafficAreaUsageValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TrafficAreaUsageValue is a code list that enumerates the different uses of a TrafficArea. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[TrafficSpace-section]]
==== *Class TrafficSpace*

include::../requirements/Transportation/REQ_Transportation_TrafficSpace.adoc[]

|====
|*Class TrafficSpace* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} A TrafficSpace is a space in which traffic takes place. Traffic includes the movement of entities such as trains, vehicles, pedestrians, ships, or other transportation types.  +
Subclass Of: {nbsp}{nbsp} <<AbstractUnoccupiedSpace-section,AbstractUnoccupiedSpace>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «FeatureType»
|*Relations* 
|Relation Name: {nbsp}{nbsp} clearanceSpace +
Cardinality:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  * +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} <<ClearanceSpace-section,ClearanceSpace>>  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Relates to the clearance spaces that are part of the TrafficSpace. +
|Relation Name: {nbsp}{nbsp} successor +
Cardinality:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  * +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} <<TrafficSpace-section,TrafficSpace>>  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Indicates the successor(s) of the TrafficSpace.  +
|Relation Name: {nbsp}{nbsp} boundary +
Cardinality:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  * +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} <<TrafficArea-section,TrafficArea>>  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
|Relation Name: {nbsp}{nbsp} predecessor +
Cardinality:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  * +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} <<TrafficSpace-section,TrafficSpace>>  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Indicates the predecessor(s) of the TrafficSpace.  +
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}class +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TrafficSpaceClassValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Indicates the specific type of the TrafficSpace.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}function +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TrafficSpaceFunctionValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Specifies the intended purposes of the TrafficSpace.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}granularity +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} GranularityValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Defines whether traffic spaces are represented by individual ways or by individual lanes, depending on the desired level of detail.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}occupancy +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Occupancy +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Provides information on the residency of persons, vehicles, or other moving features in the TrafficSpace.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}trafficDirection +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TrafficDirectionValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Indicates the direction of traffic flow relative to the corresponding linear geometry representation.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}usage +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TrafficSpaceUsageValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Specifies the actual uses of the TrafficSpace.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|
|==== 

[[TrafficSpaceClassValue-section]]
==== *Class TrafficSpaceClassValue*

include::../requirements/Transportation/REQ_Transportation_TrafficSpaceClassValue.adoc[]

|====
|*Class TrafficSpaceClassValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TrafficSpaceClassValue is a code list used to further classify a TrafficSpace. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[TrafficSpaceFunctionValue-section]]
==== *Class TrafficSpaceFunctionValue*

include::../requirements/Transportation/REQ_Transportation_TrafficSpaceFunctionValue.adoc[]

|====
|*Class TrafficSpaceFunctionValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TrafficSpaceFunctionValue is a code list that enumerates the different purposes of a TrafficSpace. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[TrafficSpaceUsageValue-section]]
==== *Class TrafficSpaceUsageValue*

include::../requirements/Transportation/REQ_Transportation_TrafficSpaceUsageValue.adoc[]

|====
|*Class TrafficSpaceUsageValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TrafficSpaceUsageValue is a code list that enumerates the different uses of a TrafficSpace. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[TransportationSpaceClassValue-section]]
==== *Class TransportationSpaceClassValue*

include::../requirements/Transportation/REQ_Transportation_TransportationSpaceClassValue.adoc[]

|====
|*Class TransportationSpaceClassValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TransportationSpaceClassValue is a code list used to further classify a TransportationSpace. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[TransportationSpaceFunctionValue-section]]
==== *Class TransportationSpaceFunctionValue*

include::../requirements/Transportation/REQ_Transportation_TransportationSpaceFunctionValue.adoc[]

|====
|*Class TransportationSpaceFunctionValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TransportationSpaceFunctionValue is a code list that enumerates the different purposes of a TransportationSpace. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[TransportationSpaceUsageValue-section]]
==== *Class TransportationSpaceUsageValue*

include::../requirements/Transportation/REQ_Transportation_TransportationSpaceUsageValue.adoc[]

|====
|*Class TransportationSpaceUsageValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TransportationSpaceUsageValue is a code list that enumerates the different uses of a TransportationSpace. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[Waterway-section]]
==== *Class Waterway*

include::../requirements/Transportation/REQ_Transportation_Waterway.adoc[]

|====
|*Class Waterway* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} A Waterway is a transportation space used for the movement of vessels upon or within a water body. +
Subclass Of: {nbsp}{nbsp} <<AbstractTransportationSpace-section,AbstractTransportationSpace>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «TopLevelFeatureType»
|*Relations* 
|Relation Name: {nbsp}{nbsp} section +
Cardinality:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  * +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} <<Section-section,Section>>  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Relates to the sections that are part of the Waterway. +
|Relation Name: {nbsp}{nbsp} intersection +
Cardinality:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  * +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} <<Intersection-section,Intersection>>  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Relates to the intersections that are part of the Waterway. +
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}class +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} WaterwayClassValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Indicates the specific type of the Waterway.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}function +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} WaterwayFunctionValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Specifies the intended purposes of the Waterway.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}usage +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} WaterwayUsageValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Specifies the actual uses of the Waterway.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|
|==== 

[[WaterwayClassValue-section]]
==== *Class WaterwayClassValue*

include::../requirements/Transportation/REQ_Transportation_WaterwayClassValue.adoc[]

|====
|*Class WaterwayClassValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} WaterwayClassValue is a code list used to further classify a Waterway. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[WaterwayFunctionValue-section]]
==== *Class WaterwayFunctionValue*

include::../requirements/Transportation/REQ_Transportation_WaterwayFunctionValue.adoc[]

|====
|*Class WaterwayFunctionValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} WaterwayFunctionValue is a code list that enumerates the different purposes of a Waterway. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[WaterwayUsageValue-section]]
==== *Class WaterwayUsageValue*

include::../requirements/Transportation/REQ_Transportation_WaterwayUsageValue.adoc[]

|====
|*Class WaterwayUsageValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} WaterwayUsageValue is a code list that enumerates the different uses of a Waterway. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[GranularityValue-section]]
==== *Class GranularityValue*

include::../requirements/Transportation/REQ_Transportation_GranularityValue.adoc[]

|====
|*Class GranularityValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} GranularityValue enumerates the different levels of granularity in which transportation objects are represented. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} 
|*Relations* 
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}lane +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Indicates that the individual lanes of the transportation object are represented.   +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  + 

|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}way +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Indicates that the individual (carriage)ways of the transportation object are represented.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  + 

|
|==== 

[[TrafficDirectionValue-section]]
==== *Class TrafficDirectionValue*

include::../requirements/Transportation/REQ_Transportation_TrafficDirectionValue.adoc[]

|====
|*Class TrafficDirectionValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TrafficDirectionValue enumerates the allowed directions of travel of a mobile object. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} 
|*Relations* 
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}forwards +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Indicates that traffic flows in the direction of the corresponding linear geometry.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  + 

|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}backwards +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Indicates that traffic flows in the opposite direction of the corresponding linear geometry.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  + 

|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}both +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Indicates that traffic flows in both directions.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  + 

|
|==== 
  


