[[Transportation-package-dd]]
==== *Transportation Package*

[cols="1,4",frame=none,grid=none]
|===
|{nbsp}{nbsp}{nbsp}{nbsp}Description: | The Transportation module supports representation of the transportation infrastructure. Transportation features include roads, tracks, waterways, railways, and squares. Transportation features may be represented as a network and/or as a collection of spaces or surface elements embedded in a three-dimensional space. 
|{nbsp}{nbsp}{nbsp}{nbsp}Parent Package: | CityGML
|{nbsp}{nbsp}{nbsp}{nbsp}Stereotype: | «ApplicationSchema»
|===

===== *Classes*

[[AbstractTransportationSpace-section]]
[cols="1a"]
|===
|*AbstractTransportationSpace* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! AbstractTransportationSpace is the abstract superclass of transportation objects such as Roads, Tracks, Railways, Waterways or Squares. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractUnoccupiedSpace-section,AbstractUnoccupiedSpace>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!{set:cellbgcolor:#FFFFFF} marking «Property» 
!<<Marking-section,Marking>>  
[*]
!Relates to the markings that are part of the transportation space.
!{set:cellbgcolor:#FFFFFF} trafficSpace «Property» 
!<<TrafficSpace-section,TrafficSpace>>  
[*]
!Relates to the traffic spaces that are part of the transportation space.
!{set:cellbgcolor:#FFFFFF} auxiliaryTrafficSpace «Property» 
!<<AuxiliaryTrafficSpace-section,AuxiliaryTrafficSpace>>  
[*]
!Relates to the auxiliary traffic spaces that are part of the transportation space.
!{set:cellbgcolor:#FFFFFF} hole «Property» 
!<<Hole-section,Hole>>  
[*]
!Relates to the holes that are part of the transportation space.
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} occupancy «Property»  !<<Occupancy-section,Occupancy>>  [0..*] !Provides information on the residency of persons, vehicles, or other moving features in the transportation space.
 
!{set:cellbgcolor:#FFFFFF} trafficDirection «Property»  !<<TrafficDirectionValue-section,TrafficDirectionValue>>  [0..1] !Indicates the direction of traffic flow relative to the corresponding linear geometry representation.
!===
|{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes and rolls have the stereotype «Property»
|=== 

[[AuxiliaryTrafficArea-section]]
[cols="1a"]
|===
|*AuxiliaryTrafficArea* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! An AuxiliaryTrafficArea is the ground surface of an AuxiliaryTrafficSpace. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractThematicSurface-section,AbstractThematicSurface>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} class «Property»  !<<AuxiliaryTrafficAreaClassValue-section,AuxiliaryTrafficAreaClassValue>>  [0..1] !Indicates the specific type of the AuxiliaryTrafficArea.
 
!{set:cellbgcolor:#FFFFFF} function «Property»  !<<AuxiliaryTrafficAreaFunctionValue-section,AuxiliaryTrafficAreaFunctionValue>>  [0..*] !Specifies the intended purposes of the AuxiliaryTrafficArea.
 
!{set:cellbgcolor:#FFFFFF} surfaceMaterial «Property»  !<<SurfaceMaterialValue-section,SurfaceMaterialValue>>  [0..1] !Specifies the type of pavement of the AuxiliaryTrafficArea.
 
!{set:cellbgcolor:#FFFFFF} usage «Property»  !<<AuxiliaryTrafficAreaUsageValue-section,AuxiliaryTrafficAreaUsageValue>>  [0..*] !Specifies the actual uses of the AuxiliaryTrafficArea.
!===
|{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes and rolls have the stereotype «Property»
|=== 

[[AuxiliaryTrafficSpace-section]]
[cols="1a"]
|===
|*AuxiliaryTrafficSpace* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! An AuxiliaryTrafficSpace is a space within the transportation space not intended for traffic purposes. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractUnoccupiedSpace-section,AbstractUnoccupiedSpace>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!{set:cellbgcolor:#FFFFFF} boundary «Property» 
!<<AuxiliaryTrafficArea-section,AuxiliaryTrafficArea>>  
[*]
!
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} class «Property»  !<<AuxiliaryTrafficSpaceClassValue-section,AuxiliaryTrafficSpaceClassValue>>  [0..1] !Indicates the specific type of the AuxiliaryTrafficSpace.
 
!{set:cellbgcolor:#FFFFFF} function «Property»  !<<AuxiliaryTrafficSpaceFunctionValue-section,AuxiliaryTrafficSpaceFunctionValue>>  [0..*] !Specifies the intended purposes of the AuxiliaryTrafficSpace.
 
!{set:cellbgcolor:#FFFFFF} granularity «Property»  !<<GranularityValue-section,GranularityValue>>  !Defines whether auxiliary traffic spaces are represented by individual ways or by individual lanes, depending on the desired level of detail.
 
!{set:cellbgcolor:#FFFFFF} usage «Property»  !<<AuxiliaryTrafficSpaceUsageValue-section,AuxiliaryTrafficSpaceUsageValue>>  [0..*] !Specifies the actual uses of the AuxiliaryTrafficSpace.
!===
|{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes and rolls have the stereotype «Property»
|=== 

[[ClearanceSpace-section]]
[cols="1a"]
|===
|*ClearanceSpace* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A ClearanceSpace represents the actual free space above a TrafficArea within which a mobile object can move without contacting an obstruction. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractUnoccupiedSpace-section,AbstractUnoccupiedSpace>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} class «Property»  !<<ClearanceSpaceClassValue-section,ClearanceSpaceClassValue>>  [0..*] !Indicates the specific type of the ClearanceSpace.
!===
|{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes and rolls have the stereotype «Property»
|=== 

[[Hole-section]]
[cols="1a"]
|===
|*Hole* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A Hole is an opening in the surface of a Road, Track or Square such as road damages, manholes or drains. Holes can span multiple transportation objects. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractUnoccupiedSpace-section,AbstractUnoccupiedSpace>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!{set:cellbgcolor:#FFFFFF} boundary «Property» 
!<<AbstractThematicSurface-section,AbstractThematicSurface>>  
[*]
!
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} class «Property»  !<<HoleClassValue-section,HoleClassValue>>  [0..1] !Indicates the specific type of the Hole.
!===
|{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes and rolls have the stereotype «Property»
|=== 

[[HoleSurface-section]]
[cols="1a"]
|===
|*HoleSurface* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A HoleSurface is a representation of the ground surface of a hole. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractThematicSurface-section,AbstractThematicSurface>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
!===
|{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes and rolls have the stereotype «Property»
|=== 

[[Intersection-section]]
[cols="1a"]
|===
|*Intersection* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! An Intersection is a transportation space that is a shared segment of multiple Road, Track, Railway, or Waterway objects (e.g. a crossing of two roads or a level crossing of a road and a railway). 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractTransportationSpace-section,AbstractTransportationSpace>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} class «Property»  !<<IntersectionClassValue-section,IntersectionClassValue>>  [0..1] !Indicates the specific type of the Intersection.
!===
|{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes and rolls have the stereotype «Property»
|=== 

[[Marking-section]]
[cols="1a"]
|===
|*Marking* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A Marking is a visible pattern on a transportation area relevant to the structuring or restriction of traffic. Examples are road markings and markings related to railway or waterway traffic. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractThematicSurface-section,AbstractThematicSurface>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} class «Property»  !<<MarkingClassValue-section,MarkingClassValue>>  [0..1] !Indicates the specific type of the Marking.
!===
|{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes and rolls have the stereotype «Property»
|=== 

[[Railway-section]]
[cols="1a"]
|===
|*Railway* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A Railway is a transportation space used by wheeled vehicles on rails. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractTransportationSpace-section,AbstractTransportationSpace>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «TopLevelFeatureType»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!{set:cellbgcolor:#FFFFFF} intersection «Property» 
!<<Intersection-section,Intersection>>  
[*]
!Relates to the intersections that are part of the Railway.
!{set:cellbgcolor:#FFFFFF} section «Property» 
!<<Section-section,Section>>  
[*]
!Relates to the sections that are part of the Railway.
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} class «Property»  !<<RailwayClassValue-section,RailwayClassValue>>  [0..1] !Indicates the specific type of the Railway.
 
!{set:cellbgcolor:#FFFFFF} function «Property»  !<<RailwayFunctionValue-section,RailwayFunctionValue>>  [0..*] !Specifies the intended purposes of the Railway.
 
!{set:cellbgcolor:#FFFFFF} usage «Property»  !<<RailwayUsageValue-section,RailwayUsageValue>>  [0..*] !Specifies the actual uses of the Railway.
!===
|{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes and rolls have the stereotype «Property»
|=== 

[[Road-section]]
[cols="1a"]
|===
|*Road* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A Road is a transportation space used by vehicles, bicycles and/or pedestrians. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractTransportationSpace-section,AbstractTransportationSpace>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «TopLevelFeatureType»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!{set:cellbgcolor:#FFFFFF} intersection «Property» 
!<<Intersection-section,Intersection>>  
[*]
!Relates to the intersections that are part of the Road.
!{set:cellbgcolor:#FFFFFF} section «Property» 
!<<Section-section,Section>>  
[*]
!Relates to the sections that are part of the Road.
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} class «Property»  !<<RoadClassValue-section,RoadClassValue>>  [0..1] !Indicates the specific type of the Road.
 
!{set:cellbgcolor:#FFFFFF} function «Property»  !<<RoadFunctionValue-section,RoadFunctionValue>>  [0..*] !Specifies the intended purposes of the Road.
 
!{set:cellbgcolor:#FFFFFF} usage «Property»  !<<RoadUsageValue-section,RoadUsageValue>>  [0..*] !Specifies the actual uses of the Road.
!===
|{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes and rolls have the stereotype «Property»
|=== 

[[Section-section]]
[cols="1a"]
|===
|*Section* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A Section is a transportation space that is a segment of a Road, Railway, Track, or Waterway. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractTransportationSpace-section,AbstractTransportationSpace>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} class «Property»  !<<SectionClassValue-section,SectionClassValue>>  [0..1] !Indicates the specific type of the Section.
!===
|{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes and rolls have the stereotype «Property»
|=== 

[[Square-section]]
[cols="1a"]
|===
|*Square* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A Square is a transportation space for unrestricted movement for vehicles, bicycles and/or pedestrians. This includes plazas as well as large sealed surfaces such as parking lots. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractTransportationSpace-section,AbstractTransportationSpace>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «TopLevelFeatureType»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} class «Property»  !<<SquareClassValue-section,SquareClassValue>>  [0..1] !Indicates the specific type of the Square.
 
!{set:cellbgcolor:#FFFFFF} function «Property»  !<<SquareFunctionValue-section,SquareFunctionValue>>  [0..*] !Specifies the intended purposes of the Square.
 
!{set:cellbgcolor:#FFFFFF} usage «Property»  !<<SquareUsageValue-section,SquareUsageValue>>  [0..*] !Specifies the actual uses of the Square.
!===
|{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes and rolls have the stereotype «Property»
|=== 

[[Track-section]]
[cols="1a"]
|===
|*Track* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A Track is a small path mainly used by pedestrians. Tracks can be segmented into Sections and Intersections. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractTransportationSpace-section,AbstractTransportationSpace>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «TopLevelFeatureType»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!{set:cellbgcolor:#FFFFFF} section «Property» 
!<<Section-section,Section>>  
[*]
!Relates to the sections that are part of the Track.
!{set:cellbgcolor:#FFFFFF} intersection «Property» 
!<<Intersection-section,Intersection>>  
[*]
!Relates to the intersections that are part of the Track.
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} class «Property»  !<<TrackClassValue-section,TrackClassValue>>  [0..1] !Indicates the specific type of the Track.
 
!{set:cellbgcolor:#FFFFFF} function «Property»  !<<TrackFunctionValue-section,TrackFunctionValue>>  [0..*] !Specifies the intended purposes of the Track.
 
!{set:cellbgcolor:#FFFFFF} usage «Property»  !<<TrackUsageValue-section,TrackUsageValue>>  [0..*] !Specifies the actual uses of the Track.
!===
|{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes and rolls have the stereotype «Property»
|=== 

[[TrafficArea-section]]
[cols="1a"]
|===
|*TrafficArea* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A TrafficArea is the ground surface of a TrafficSpace. Traffic areas are the surfaces upon which traffic actually takes place. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractThematicSurface-section,AbstractThematicSurface>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} class «Property»  !<<TrafficAreaClassValue-section,TrafficAreaClassValue>>  [0..1] !Indicates the specific type of the TrafficArea.
 
!{set:cellbgcolor:#FFFFFF} function «Property»  !<<TrafficAreaFunctionValue-section,TrafficAreaFunctionValue>>  [0..*] !Specifies the intended purposes of the TrafficArea.
 
!{set:cellbgcolor:#FFFFFF} surfaceMaterial «Property»  !<<SurfaceMaterialValue-section,SurfaceMaterialValue>>  [0..1] !Specifies the type of pavement of the TrafficArea.
 
!{set:cellbgcolor:#FFFFFF} usage «Property»  !<<TrafficAreaUsageValue-section,TrafficAreaUsageValue>>  [0..*] !Specifies the actual uses of the TrafficArea.
!===
|{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes and rolls have the stereotype «Property»
|=== 

[[TrafficSpace-section]]
[cols="1a"]
|===
|*TrafficSpace* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A TrafficSpace is a space in which traffic takes place. Traffic includes the movement of entities such as trains, vehicles, pedestrians, ships, or other transportation types.  
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractUnoccupiedSpace-section,AbstractUnoccupiedSpace>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!{set:cellbgcolor:#FFFFFF} successor «Property» 
!<<TrafficSpace-section,TrafficSpace>>  
[*]
!Indicates the successor(s) of the TrafficSpace. 
!{set:cellbgcolor:#FFFFFF} clearanceSpace «Property» 
!<<ClearanceSpace-section,ClearanceSpace>>  
[*]
!Relates to the clearance spaces that are part of the TrafficSpace.
!{set:cellbgcolor:#FFFFFF} predecessor «Property» 
!<<TrafficSpace-section,TrafficSpace>>  
[*]
!Indicates the predecessor(s) of the TrafficSpace. 
!{set:cellbgcolor:#FFFFFF} boundary «Property» 
!<<TrafficArea-section,TrafficArea>>  
[*]
!
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} class «Property»  !<<TrafficSpaceClassValue-section,TrafficSpaceClassValue>>  [0..1] !Indicates the specific type of the TrafficSpace.
 
!{set:cellbgcolor:#FFFFFF} function «Property»  !<<TrafficSpaceFunctionValue-section,TrafficSpaceFunctionValue>>  [0..*] !Specifies the intended purposes of the TrafficSpace.
 
!{set:cellbgcolor:#FFFFFF} granularity «Property»  !<<GranularityValue-section,GranularityValue>>  !Defines whether traffic spaces are represented by individual ways or by individual lanes, depending on the desired level of detail.
 
!{set:cellbgcolor:#FFFFFF} occupancy «Property»  !<<Occupancy-section,Occupancy>>  [0..*] !Provides information on the residency of persons, vehicles, or other moving features in the TrafficSpace.
 
!{set:cellbgcolor:#FFFFFF} trafficDirection «Property»  !<<TrafficDirectionValue-section,TrafficDirectionValue>>  [0..1] !Indicates the direction of traffic flow relative to the corresponding linear geometry representation.
 
!{set:cellbgcolor:#FFFFFF} usage «Property»  !<<TrafficSpaceUsageValue-section,TrafficSpaceUsageValue>>  [0..*] !Specifies the actual uses of the TrafficSpace.
!===
|{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes and rolls have the stereotype «Property»
|=== 

[[Waterway-section]]
[cols="1a"]
|===
|*Waterway* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A Waterway is a transportation space used for the movement of vessels upon or within a water body. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractTransportationSpace-section,AbstractTransportationSpace>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «TopLevelFeatureType»
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!{set:cellbgcolor:#FFFFFF} intersection «Property» 
!<<Intersection-section,Intersection>>  
[*]
!Relates to the intersections that are part of the Waterway.
!{set:cellbgcolor:#FFFFFF} section «Property» 
!<<Section-section,Section>>  
[*]
!Relates to the sections that are part of the Waterway.
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} class «Property»  !<<WaterwayClassValue-section,WaterwayClassValue>>  [0..1] !Indicates the specific type of the Waterway.
 
!{set:cellbgcolor:#FFFFFF} function «Property»  !<<WaterwayFunctionValue-section,WaterwayFunctionValue>>  [0..*] !Specifies the intended purposes of the Waterway.
 
!{set:cellbgcolor:#FFFFFF} usage «Property»  !<<WaterwayUsageValue-section,WaterwayUsageValue>>  [0..*] !Specifies the actual uses of the Waterway.
!===
|{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes and rolls have the stereotype «Property»
|===   

===== *Data Types*

none

===== *Basic Types*

none

===== *Unions*

none

===== *Code Lists*

[[AuxiliaryTrafficAreaClassValue-section]]
[cols="1a"]
|===
|*AuxiliaryTrafficAreaClassValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! AuxiliaryTrafficAreaClassValue is a code list used to further classify an AuxiliaryTrafficArea. 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[AuxiliaryTrafficAreaFunctionValue-section]]
[cols="1a"]
|===
|*AuxiliaryTrafficAreaFunctionValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! AuxiliaryTrafficAreaFunctionValue is a code list that enumerates the different purposes of an AuxiliaryTrafficArea. 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[AuxiliaryTrafficAreaUsageValue-section]]
[cols="1a"]
|===
|*AuxiliaryTrafficAreaUsageValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! AuxiliaryTrafficAreaUsageValue is a code list that enumerates the different uses of an AuxiliaryTrafficArea. 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[AuxiliaryTrafficSpaceClassValue-section]]
[cols="1a"]
|===
|*AuxiliaryTrafficSpaceClassValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! AuxiliaryTrafficSpaceClassValue is a code list used to further classify an AuxiliaryTrafficSpace. 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[AuxiliaryTrafficSpaceFunctionValue-section]]
[cols="1a"]
|===
|*AuxiliaryTrafficSpaceFunctionValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! AuxiliaryTrafficSpaceFunctionValue is a code list that enumerates the different purposes of an AuxiliaryTrafficSpace. 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[AuxiliaryTrafficSpaceUsageValue-section]]
[cols="1a"]
|===
|*AuxiliaryTrafficSpaceUsageValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! AuxiliaryTrafficSpaceUsageValue is a code list that enumerates the different uses of an AuxiliaryTrafficSpace. 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[ClearanceSpaceClassValue-section]]
[cols="1a"]
|===
|*ClearanceSpaceClassValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! ClearanceSpaceClassValue is a code list used to further classify a ClearanceSpace. 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[HoleClassValue-section]]
[cols="1a"]
|===
|*HoleClassValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! HoleClassValue is a code list used to further classify a Hole. 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[IntersectionClassValue-section]]
[cols="1a"]
|===
|*IntersectionClassValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! IntersectionClassValue is a code list used to further classify an Intersection. 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[MarkingClassValue-section]]
[cols="1a"]
|===
|*MarkingClassValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! MarkingClassValue is a code list used to further classify a Marking. 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[RailwayClassValue-section]]
[cols="1a"]
|===
|*RailwayClassValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! RailwayClassValue is a code list used to further classify a Railway. 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[RailwayFunctionValue-section]]
[cols="1a"]
|===
|*RailwayFunctionValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! RailwayFunctionValue is a code list that enumerates the different purposes of a Railway. 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[RailwayUsageValue-section]]
[cols="1a"]
|===
|*RailwayUsageValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! RailwayUsageValue is a code list that enumerates the different uses of a Railway. 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[RoadClassValue-section]]
[cols="1a"]
|===
|*RoadClassValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! RoadClassValue is a code list used to further classify a Road. 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[RoadFunctionValue-section]]
[cols="1a"]
|===
|*RoadFunctionValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! RoadFunctionValue is a code list that enumerates the different purposes of a Road. 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[RoadUsageValue-section]]
[cols="1a"]
|===
|*RoadUsageValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! RoadUsageValue is a code list that enumerates the different uses of a Road. 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[SectionClassValue-section]]
[cols="1a"]
|===
|*SectionClassValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! SectionClassValue is a code list used to further classify a Section. 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[SquareClassValue-section]]
[cols="1a"]
|===
|*SquareClassValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! SquareClassValue is a code list used to further classify a Square. 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[SquareFunctionValue-section]]
[cols="1a"]
|===
|*SquareFunctionValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! SquareFunctionValue is a code list that enumerates the different purposes of a Square. 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[SquareUsageValue-section]]
[cols="1a"]
|===
|*SquareUsageValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! SquareUsageValue is a code list that enumerates the different uses of a Square. 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[SurfaceMaterialValue-section]]
[cols="1a"]
|===
|*SurfaceMaterialValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! SurfaceMaterialValue is a code list that enumerates the different surface materials. 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[TrackClassValue-section]]
[cols="1a"]
|===
|*TrackClassValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! TrackClassValue is a code list used to further classify a Track. 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[TrackFunctionValue-section]]
[cols="1a"]
|===
|*TrackFunctionValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! TrackFunctionValue is a code list that enumerates the different purposes of a Track. 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[TrackUsageValue-section]]
[cols="1a"]
|===
|*TrackUsageValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! TrackUsageValue is a code list that enumerates the different uses of a Track. 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[TrafficAreaClassValue-section]]
[cols="1a"]
|===
|*TrafficAreaClassValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! TrafficAreaClassValue is a code list used to further classify a TrafficArea. 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[TrafficAreaFunctionValue-section]]
[cols="1a"]
|===
|*TrafficAreaFunctionValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! TrafficAreaFunctionValue is a code list that enumerates the different purposes of a TrafficArea. 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[TrafficAreaUsageValue-section]]
[cols="1a"]
|===
|*TrafficAreaUsageValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! TrafficAreaUsageValue is a code list that enumerates the different uses of a TrafficArea. 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[TrafficSpaceClassValue-section]]
[cols="1a"]
|===
|*TrafficSpaceClassValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! TrafficSpaceClassValue is a code list used to further classify a TrafficSpace. 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[TrafficSpaceFunctionValue-section]]
[cols="1a"]
|===
|*TrafficSpaceFunctionValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! TrafficSpaceFunctionValue is a code list that enumerates the different purposes of a TrafficSpace. 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[TrafficSpaceUsageValue-section]]
[cols="1a"]
|===
|*TrafficSpaceUsageValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! TrafficSpaceUsageValue is a code list that enumerates the different uses of a TrafficSpace. 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[TransportationSpaceClassValue-section]]
[cols="1a"]
|===
|*TransportationSpaceClassValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! TransportationSpaceClassValue is a code list used to further classify a TransportationSpace. 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[TransportationSpaceFunctionValue-section]]
[cols="1a"]
|===
|*TransportationSpaceFunctionValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! TransportationSpaceFunctionValue is a code list that enumerates the different purposes of a TransportationSpace. 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[TransportationSpaceUsageValue-section]]
[cols="1a"]
|===
|*TransportationSpaceUsageValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! TransportationSpaceUsageValue is a code list that enumerates the different uses of a TransportationSpace. 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[WaterwayClassValue-section]]
[cols="1a"]
|===
|*WaterwayClassValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! WaterwayClassValue is a code list used to further classify a Waterway. 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[WaterwayFunctionValue-section]]
[cols="1a"]
|===
|*WaterwayFunctionValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! WaterwayFunctionValue is a code list that enumerates the different purposes of a Waterway. 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|=== 

[[WaterwayUsageValue-section]]
[cols="1a"]
|===
|*WaterwayUsageValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! WaterwayUsageValue is a code list that enumerates the different uses of a Waterway. 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|===   

===== *Enumerations*

[[GranularityValue-section]]
[cols="1a"]
|===
|*GranularityValue*
[cols="1,4",frame=none,grid=none]
!===
!Definition: ! GranularityValue enumerates the different levels of granularity in which transportation objects are represented. 
!StereoType: !  <<enumeration>>
!===
|[cols="1,4",frame=none,grid=none,options="header"]
!===
^!{set:cellbgcolor:#DDDDDD} *Literal Values* !*Definitions*
 
^!{set:cellbgcolor:#FFFFFF} lane  !Indicates that the individual lanes of the transportation object are represented. 
 
^!{set:cellbgcolor:#FFFFFF} way  !Indicates that the individual (carriage)ways of the transportation object are represented.
!===
|=== 

[[TrafficDirectionValue-section]]
[cols="1a"]
|===
|*TrafficDirectionValue*
[cols="1,4",frame=none,grid=none]
!===
!Definition: ! TrafficDirectionValue enumerates the allowed directions of travel of a mobile object. 
!StereoType: !  <<enumeration>>
!===
|[cols="1,4",frame=none,grid=none,options="header"]
!===
^!{set:cellbgcolor:#DDDDDD} *Literal Values* !*Definitions*
 
^!{set:cellbgcolor:#FFFFFF} forwards  !Indicates that traffic flows in the direction of the corresponding linear geometry.
 
^!{set:cellbgcolor:#FFFFFF} backwards  !Indicates that traffic flows in the opposite direction of the corresponding linear geometry.
 
^!{set:cellbgcolor:#FFFFFF} both  !Indicates that traffic flows in both directions.
!===
|===   
