[[Tunnel-package]]
==== *Tunnel Package*

|====
|*Package Tunnel*
|Description:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}The Tunnel module supports representation of thematic and spatial aspects of tunnels, tunnel parts, tunnel installations, and interior tunnel structures. +
Stereotype:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}«ApplicationSchema» +
Parent Package: {nbsp}{nbsp}CityGML
|====

[[AbstractTunnel-section]]
==== *Class AbstractTunnel*

include::../requirements/Tunnel/REQ_Tunnel_AbstractTunnel.adoc[]

|====
|*Class AbstractTunnel* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} AbstractTunnel is an abstract superclass representing the common attributes and associations of the classes Tunnel and TunnelPart. +
Subclass Of: {nbsp}{nbsp} <<AbstractConstruction-section,AbstractConstruction>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «FeatureType»
|*Relations* 
|Relation Name: {nbsp}{nbsp} tunnelFurniture +
Cardinality:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  * +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} <<TunnelFurniture-section,TunnelFurniture>>  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Relates the furniture objects to the Tunnel or TunnelPart. +
|Relation Name: {nbsp}{nbsp} tunnelInstallation +
Cardinality:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  * +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} <<TunnelInstallation-section,TunnelInstallation>>  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Relates the installation objects to the Tunnel or TunnelPart. +
|Relation Name: {nbsp}{nbsp} tunnelConstructiveElement +
Cardinality:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  * +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} <<TunnelConstructiveElement-section,TunnelConstructiveElement>>  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Relates the constructive elements to the Tunnel or TunnelPart. +
|Relation Name: {nbsp}{nbsp} hollowSpace +
Cardinality:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  * +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} <<HollowSpace-section,HollowSpace>>  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Relates the hollow spaces to the Tunnel or TunnelPart. +
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}class +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TunnelClassValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Indicates the specific type of the Tunnel or TunnelPart.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}function +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TunnelFunctionValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Specifies the intended purposes of the Tunnel or TunnelPart.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}usage +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TunnelUsageValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Specifies the actual uses of the Tunnel or TunnelPart.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|
|==== 

[[HollowSpace-section]]
==== *Class HollowSpace*

include::../requirements/Tunnel/REQ_Tunnel_HollowSpace.adoc[]

|====
|*Class HollowSpace* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} A HollowSpace is a space within a Tunnel or TunnelPart intended for certain functions (e.g. transport or passage ways, service rooms, emergency shelters). A HollowSpace is bounded physically and/or virtually (e.g. by ClosureSurfaces or GenericSurfaces). +
Subclass Of: {nbsp}{nbsp} <<AbstractUnoccupiedSpace-section,AbstractUnoccupiedSpace>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «FeatureType»
|*Relations* 
|Relation Name: {nbsp}{nbsp} boundary +
Cardinality:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  * +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} <<AbstractThematicSurface-section,AbstractThematicSurface>>  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  +
|Relation Name: {nbsp}{nbsp} tunnelFurniture +
Cardinality:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  * +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} <<TunnelFurniture-section,TunnelFurniture>>  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Relates to the furniture objects. +
|Relation Name: {nbsp}{nbsp} tunnelInstallation +
Cardinality:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  * +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} <<TunnelInstallation-section,TunnelInstallation>>  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Relates to the installation objects. +
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}class +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} HollowSpaceClassValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Indicates the specific type of the HollowSpace.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}function +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} HollowSpaceFunctionValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Specifies the intended purposes of the HollowSpace.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}usage +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} HollowSpaceUsageValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Specifies the actual uses of the HollowSpace.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|
|==== 

[[HollowSpaceClassValue-section]]
==== *Class HollowSpaceClassValue*

include::../requirements/Tunnel/REQ_Tunnel_HollowSpaceClassValue.adoc[]

|====
|*Class HollowSpaceClassValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} HollowSpaceClassValue is a code list used to further classify a HollowSpace. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[HollowSpaceFunctionValue-section]]
==== *Class HollowSpaceFunctionValue*

include::../requirements/Tunnel/REQ_Tunnel_HollowSpaceFunctionValue.adoc[]

|====
|*Class HollowSpaceFunctionValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} HollowSpaceFunctionValue is a code list that enumerates the different purposes of a HollowSpace. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[HollowSpaceUsageValue-section]]
==== *Class HollowSpaceUsageValue*

include::../requirements/Tunnel/REQ_Tunnel_HollowSpaceUsageValue.adoc[]

|====
|*Class HollowSpaceUsageValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} HollowSpaceUsageValue is a code list that enumerates the different uses of a HollowSpace. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[Tunnel-section]]
==== *Class Tunnel*

include::../requirements/Tunnel/REQ_Tunnel_Tunnel.adoc[]

|====
|*Class Tunnel* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} A Tunnel represents a horizontal or sloping enclosed passage way of a certain length, mainly underground or underwater. [cf. ISO 6707-1] +
Subclass Of: {nbsp}{nbsp} <<AbstractTunnel-section,AbstractTunnel>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «TopLevelFeatureType»
|*Relations* 
|Relation Name: {nbsp}{nbsp} tunnelPart +
Cardinality:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  * +
Target Class: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} <<TunnelPart-section,TunnelPart>>  +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Relates the Tunnel to the tunnel parts. +
|*Attributes*
|
|==== 

[[TunnelClassValue-section]]
==== *Class TunnelClassValue*

include::../requirements/Tunnel/REQ_Tunnel_TunnelClassValue.adoc[]

|====
|*Class TunnelClassValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TunnelClassValue is a code list used to further classify a Tunnel. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[TunnelConstructiveElement-section]]
==== *Class TunnelConstructiveElement*

include::../requirements/Tunnel/REQ_Tunnel_TunnelConstructiveElement.adoc[]

|====
|*Class TunnelConstructiveElement* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  A TunnelConstructiveElement is an element of a Tunnel which is essential from a structural point of view. Examples are walls, slabs, beams. +
Subclass Of: {nbsp}{nbsp} <<AbstractConstructiveElement-section,AbstractConstructiveElement>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «FeatureType»
|*Relations* 
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}class +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TunnelConstructiveElementClassValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Indicates the specific type of the TunnelConstructiveElement.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}function +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TunnelConstructiveElementFunctionValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Specifies the intended purposes of the TunnelConstructiveElement.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}usage +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TunnelConstructiveElementUsageValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Specifies the actual uses of the TunnelConstructiveElement.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|
|==== 

[[TunnelConstructiveElementClassValue-section]]
==== *Class TunnelConstructiveElementClassValue*

include::../requirements/Tunnel/REQ_Tunnel_TunnelConstructiveElementClassValue.adoc[]

|====
|*Class TunnelConstructiveElementClassValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TunnelConstructiveElementClassValue is a code list used to further classify a TunnelConstructiveElement. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[TunnelConstructiveElementFunctionValue-section]]
==== *Class TunnelConstructiveElementFunctionValue*

include::../requirements/Tunnel/REQ_Tunnel_TunnelConstructiveElementFunctionValue.adoc[]

|====
|*Class TunnelConstructiveElementFunctionValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TunnelConstructiveElementFunctionValue is a code list that enumerates the different purposes of a TunnelConstructiveElement. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[TunnelConstructiveElementUsageValue-section]]
==== *Class TunnelConstructiveElementUsageValue*

include::../requirements/Tunnel/REQ_Tunnel_TunnelConstructiveElementUsageValue.adoc[]

|====
|*Class TunnelConstructiveElementUsageValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TunnelConstructiveElementUsageValue is a code list that enumerates the different uses of a TunnelConstructiveElement. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[TunnelFunctionValue-section]]
==== *Class TunnelFunctionValue*

include::../requirements/Tunnel/REQ_Tunnel_TunnelFunctionValue.adoc[]

|====
|*Class TunnelFunctionValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TunnelFunctionValue is a code list that enumerates the different purposes of a Tunnel. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[TunnelFurniture-section]]
==== *Class TunnelFurniture*

include::../requirements/Tunnel/REQ_Tunnel_TunnelFurniture.adoc[]

|====
|*Class TunnelFurniture* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} A TunnelFurniture is an equipment for occupant use, usually not fixed to the tunnel. [cf. ISO 6707-1] +
Subclass Of: {nbsp}{nbsp} <<AbstractFurniture-section,AbstractFurniture>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «FeatureType»
|*Relations* 
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}class +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TunnelFurnitureClassValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Indicates the specific type of the TunnelFurniture.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}function +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TunnelFurnitureFunctionValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Specifies the intended purposes of the TunnelFurniture.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}usage +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TunnelFurnitureUsageValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Specifies the actual uses of the TunnelFurniture.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|
|==== 

[[TunnelFurnitureClassValue-section]]
==== *Class TunnelFurnitureClassValue*

include::../requirements/Tunnel/REQ_Tunnel_TunnelFurnitureClassValue.adoc[]

|====
|*Class TunnelFurnitureClassValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TunnelFurnitureClassValue is a code list used to further classify a TunnelFurniture. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[TunnelFurnitureFunctionValue-section]]
==== *Class TunnelFurnitureFunctionValue*

include::../requirements/Tunnel/REQ_Tunnel_TunnelFurnitureFunctionValue.adoc[]

|====
|*Class TunnelFurnitureFunctionValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TunnelFurnitureFunctionValue is a code list that enumerates the different purposes of a TunnelFurniture. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[TunnelFurnitureUsageValue-section]]
==== *Class TunnelFurnitureUsageValue*

include::../requirements/Tunnel/REQ_Tunnel_TunnelFurnitureUsageValue.adoc[]

|====
|*Class TunnelFurnitureUsageValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TunnelFurnitureUsageValue is a code list that enumerates the different uses of a TunnelFurniture. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[TunnelInstallation-section]]
==== *Class TunnelInstallation*

include::../requirements/Tunnel/REQ_Tunnel_TunnelInstallation.adoc[]

|====
|*Class TunnelInstallation* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} A TunnelInstallation is a permanent part of a Tunnel (inside and/or outside) which does not have the significance of a TunnelPart. In contrast to TunnelConstructiveElement, a TunnelInstallation is not essential from a structural point of view. Examples are stairs, antennas or railings. +
Subclass Of: {nbsp}{nbsp} <<AbstractInstallation-section,AbstractInstallation>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «FeatureType»
|*Relations* 
|*Attributes*
|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}class +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TunnelInstallationClassValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Indicates the specific type of the TunnelInstallation.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..1] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}function +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TunnelInstallationFunctionValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Specifies the intended purposes of the TunnelInstallation.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|Attribute Name: {nbsp}{nbsp}{nbsp}{nbsp}usage +
Value Type: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TunnelInstallationUsageValue +
Definition: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} Specifies the actual uses of the TunnelInstallation.  +
Multiplicity: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}  [0..*] +
Stereotype: {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} «Property» + 

|
|==== 

[[TunnelInstallationClassValue-section]]
==== *Class TunnelInstallationClassValue*

include::../requirements/Tunnel/REQ_Tunnel_TunnelInstallationClassValue.adoc[]

|====
|*Class TunnelInstallationClassValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TunnelInstallationClassValue is a code list used to further classify a TunnelInstallation. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[TunnelInstallationFunctionValue-section]]
==== *Class TunnelInstallationFunctionValue*

include::../requirements/Tunnel/REQ_Tunnel_TunnelInstallationFunctionValue.adoc[]

|====
|*Class TunnelInstallationFunctionValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TunnelInstallationFunctionValue is a code list that enumerates the different purposes of a TunnelInstallation. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[TunnelInstallationUsageValue-section]]
==== *Class TunnelInstallationUsageValue*

include::../requirements/Tunnel/REQ_Tunnel_TunnelInstallationUsageValue.adoc[]

|====
|*Class TunnelInstallationUsageValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TunnelInstallationUsageValue is a code list that enumerates the different uses of a TunnelInstallation. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 

[[TunnelPart-section]]
==== *Class TunnelPart*

include::../requirements/Tunnel/REQ_Tunnel_TunnelPart.adoc[]

|====
|*Class TunnelPart* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} A TunnelPart is a physical or functional subdivision of a Tunnel. It would be considered a Tunnel, if it were not part of a collection of other TunnelParts. +
Subclass Of: {nbsp}{nbsp} <<AbstractTunnel-section,AbstractTunnel>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «FeatureType»
|*Relations* 
|*Attributes*
|
|==== 

[[TunnelUsageValue-section]]
==== *Class TunnelUsageValue*

include::../requirements/Tunnel/REQ_Tunnel_TunnelUsageValue.adoc[]

|====
|*Class TunnelUsageValue* +
Definition:{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} TunnelUsageValue is a code list that enumerates the different uses of a Tunnel. +
Subclass Of: {nbsp}{nbsp} <<-section,>> +
StereoType:{nbsp}{nbsp}{nbsp}{nbsp} «CodeList»
|*Relations* 
|*Attributes*
|
|==== 
  



