[[Tunnel-package-dd]]
==== *Package*

[cols="1a"]
|===
|{set:cellbgcolor:#FFFFFF} *Package Tunnel*
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Description: ! The Tunnel module supports representation of thematic and spatial aspects of tunnels, tunnel parts, tunnel installations, and interior tunnel structures. 
!{nbsp}{nbsp}{nbsp}{nbsp}Parent Package: ! CityGML
!{nbsp}{nbsp}{nbsp}{nbsp}Stereotype: ! «ApplicationSchema»
!===
|===

|===
|Editing instructions:
| 1) Delete all tables for CodeLists 
| 2) If a subclass value is "<<←section,>>", change it to "none"
| 3) If a multiplicity value is not provided, set it to "1" 
| 4) If there are no entries in the role subtable, delete that subtable
| 5) If there are no entries in the attrubute subtable, delete that subtable
| 6) Delete these instructions when done
|===

==== *Classes*

[[AbstractTunnel-section]]
===== *Class AbstractTunnel*

[cols="1a"]
|===
|*AbstractTunnel* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! AbstractTunnel is an abstract superclass representing the common attributes and associations of the classes Tunnel and TunnelPart. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractConstruction-section,AbstractConstruction>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!{set:cellbgcolor:#FFFFFF} tunnelFurniture 
!<<TunnelFurniture-section,TunnelFurniture>> 
 [*]
!
!{set:cellbgcolor:#FFFFFF} tunnelInstallation 
!<<TunnelInstallation-section,TunnelInstallation>> 
 [*]
!
!{set:cellbgcolor:#FFFFFF} tunnelConstructiveElement 
!<<TunnelConstructiveElement-section,TunnelConstructiveElement>> 
 [*]
!
!{set:cellbgcolor:#FFFFFF} hollowSpace 
!<<HollowSpace-section,HollowSpace>> 
 [*]
!
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} class  !<<TunnelClassValue-section,TunnelClassValue>>  [0..1] !Indicates the specific type of the Tunnel or TunnelPart.
 
!{set:cellbgcolor:#FFFFFF} function  !<<TunnelFunctionValue-section,TunnelFunctionValue>>  [0..*] !Specifies the intended purposes of the Tunnel or TunnelPart.
 
!{set:cellbgcolor:#FFFFFF} usage  !<<TunnelUsageValue-section,TunnelUsageValue>>  [0..*] !Specifies the actual uses of the Tunnel or TunnelPart.
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[HollowSpace-section]]
===== *Class HollowSpace*

[cols="1a"]
|===
|*HollowSpace* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A HollowSpace is a space within a Tunnel or TunnelPart intended for certain functions (e.g. transport or passage ways, service rooms, emergency shelters). A HollowSpace is bounded physically and/or virtually (e.g. by ClosureSurfaces or GenericSurfaces). 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractUnoccupiedSpace-section,AbstractUnoccupiedSpace>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!{set:cellbgcolor:#FFFFFF} boundary 
!<<AbstractThematicSurface-section,AbstractThematicSurface>> 
 [*]
!
!{set:cellbgcolor:#FFFFFF} tunnelFurniture 
!<<TunnelFurniture-section,TunnelFurniture>> 
 [*]
!
!{set:cellbgcolor:#FFFFFF} tunnelInstallation 
!<<TunnelInstallation-section,TunnelInstallation>> 
 [*]
!
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} class  !<<HollowSpaceClassValue-section,HollowSpaceClassValue>>  [0..1] !Indicates the specific type of the HollowSpace.
 
!{set:cellbgcolor:#FFFFFF} function  !<<HollowSpaceFunctionValue-section,HollowSpaceFunctionValue>>  [0..*] !Specifies the intended purposes of the HollowSpace.
 
!{set:cellbgcolor:#FFFFFF} usage  !<<HollowSpaceUsageValue-section,HollowSpaceUsageValue>>  [0..*] !Specifies the actual uses of the HollowSpace.
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[HollowSpaceClassValue-section]]
===== *Class HollowSpaceClassValue*

[cols="1a"]
|===
|*HollowSpaceClassValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! HollowSpaceClassValue is a code list used to further classify a HollowSpace. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[HollowSpaceFunctionValue-section]]
===== *Class HollowSpaceFunctionValue*

[cols="1a"]
|===
|*HollowSpaceFunctionValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! HollowSpaceFunctionValue is a code list that enumerates the different purposes of a HollowSpace. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[HollowSpaceUsageValue-section]]
===== *Class HollowSpaceUsageValue*

[cols="1a"]
|===
|*HollowSpaceUsageValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! HollowSpaceUsageValue is a code list that enumerates the different uses of a HollowSpace. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[Tunnel-section]]
===== *Class Tunnel*

[cols="1a"]
|===
|*Tunnel* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A Tunnel represents a horizontal or sloping enclosed passage way of a certain length, mainly underground or underwater. [cf. ISO 6707-1] 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractTunnel-section,AbstractTunnel>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «TopLevelFeatureType»
!===
[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!{set:cellbgcolor:#FFFFFF} tunnelPart 
!<<TunnelPart-section,TunnelPart>> 
 [*]
!
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[TunnelClassValue-section]]
===== *Class TunnelClassValue*

[cols="1a"]
|===
|*TunnelClassValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! TunnelClassValue is a code list used to further classify a Tunnel. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[TunnelConstructiveElement-section]]
===== *Class TunnelConstructiveElement*

[cols="1a"]
|===
|*TunnelConstructiveElement* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: !  A TunnelConstructiveElement is an element of a Tunnel which is essential from a structural point of view. Examples are walls, slabs, beams. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractConstructiveElement-section,AbstractConstructiveElement>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} class  !<<TunnelConstructiveElementClassValue-section,TunnelConstructiveElementClassValue>>  [0..1] !Indicates the specific type of the TunnelConstructiveElement.
 
!{set:cellbgcolor:#FFFFFF} function  !<<TunnelConstructiveElementFunctionValue-section,TunnelConstructiveElementFunctionValue>>  [0..*] !Specifies the intended purposes of the TunnelConstructiveElement.
 
!{set:cellbgcolor:#FFFFFF} usage  !<<TunnelConstructiveElementUsageValue-section,TunnelConstructiveElementUsageValue>>  [0..*] !Specifies the actual uses of the TunnelConstructiveElement.
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[TunnelConstructiveElementClassValue-section]]
===== *Class TunnelConstructiveElementClassValue*

[cols="1a"]
|===
|*TunnelConstructiveElementClassValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! TunnelConstructiveElementClassValue is a code list used to further classify a TunnelConstructiveElement. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[TunnelConstructiveElementFunctionValue-section]]
===== *Class TunnelConstructiveElementFunctionValue*

[cols="1a"]
|===
|*TunnelConstructiveElementFunctionValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! TunnelConstructiveElementFunctionValue is a code list that enumerates the different purposes of a TunnelConstructiveElement. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[TunnelConstructiveElementUsageValue-section]]
===== *Class TunnelConstructiveElementUsageValue*

[cols="1a"]
|===
|*TunnelConstructiveElementUsageValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! TunnelConstructiveElementUsageValue is a code list that enumerates the different uses of a TunnelConstructiveElement. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[TunnelFunctionValue-section]]
===== *Class TunnelFunctionValue*

[cols="1a"]
|===
|*TunnelFunctionValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! TunnelFunctionValue is a code list that enumerates the different purposes of a Tunnel. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[TunnelFurniture-section]]
===== *Class TunnelFurniture*

[cols="1a"]
|===
|*TunnelFurniture* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A TunnelFurniture is an equipment for occupant use, usually not fixed to the tunnel. [cf. ISO 6707-1] 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractFurniture-section,AbstractFurniture>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} class  !<<TunnelFurnitureClassValue-section,TunnelFurnitureClassValue>>  [0..1] !Indicates the specific type of the TunnelFurniture.
 
!{set:cellbgcolor:#FFFFFF} function  !<<TunnelFurnitureFunctionValue-section,TunnelFurnitureFunctionValue>>  [0..*] !Specifies the intended purposes of the TunnelFurniture.
 
!{set:cellbgcolor:#FFFFFF} usage  !<<TunnelFurnitureUsageValue-section,TunnelFurnitureUsageValue>>  [0..*] !Specifies the actual uses of the TunnelFurniture.
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[TunnelFurnitureClassValue-section]]
===== *Class TunnelFurnitureClassValue*

[cols="1a"]
|===
|*TunnelFurnitureClassValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! TunnelFurnitureClassValue is a code list used to further classify a TunnelFurniture. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[TunnelFurnitureFunctionValue-section]]
===== *Class TunnelFurnitureFunctionValue*

[cols="1a"]
|===
|*TunnelFurnitureFunctionValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! TunnelFurnitureFunctionValue is a code list that enumerates the different purposes of a TunnelFurniture. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[TunnelFurnitureUsageValue-section]]
===== *Class TunnelFurnitureUsageValue*

[cols="1a"]
|===
|*TunnelFurnitureUsageValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! TunnelFurnitureUsageValue is a code list that enumerates the different uses of a TunnelFurniture. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[TunnelInstallation-section]]
===== *Class TunnelInstallation*

[cols="1a"]
|===
|*TunnelInstallation* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A TunnelInstallation is a permanent part of a Tunnel (inside and/or outside) which does not have the significance of a TunnelPart. In contrast to TunnelConstructiveElement, a TunnelInstallation is not essential from a structural point of view. Examples are stairs, antennas or railings. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractInstallation-section,AbstractInstallation>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} class  !<<TunnelInstallationClassValue-section,TunnelInstallationClassValue>>  [0..1] !Indicates the specific type of the TunnelInstallation.
 
!{set:cellbgcolor:#FFFFFF} function  !<<TunnelInstallationFunctionValue-section,TunnelInstallationFunctionValue>>  [0..*] !Specifies the intended purposes of the TunnelInstallation.
 
!{set:cellbgcolor:#FFFFFF} usage  !<<TunnelInstallationUsageValue-section,TunnelInstallationUsageValue>>  [0..*] !Specifies the actual uses of the TunnelInstallation.
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[TunnelInstallationClassValue-section]]
===== *Class TunnelInstallationClassValue*

[cols="1a"]
|===
|*TunnelInstallationClassValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! TunnelInstallationClassValue is a code list used to further classify a TunnelInstallation. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[TunnelInstallationFunctionValue-section]]
===== *Class TunnelInstallationFunctionValue*

[cols="1a"]
|===
|*TunnelInstallationFunctionValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! TunnelInstallationFunctionValue is a code list that enumerates the different purposes of a TunnelInstallation. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[TunnelInstallationUsageValue-section]]
===== *Class TunnelInstallationUsageValue*

[cols="1a"]
|===
|*TunnelInstallationUsageValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! TunnelInstallationUsageValue is a code list that enumerates the different uses of a TunnelInstallation. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[TunnelPart-section]]
===== *Class TunnelPart*

[cols="1a"]
|===
|*TunnelPart* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A TunnelPart is a physical or functional subdivision of a Tunnel. It would be considered a Tunnel, if it were not part of a collection of other TunnelParts. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractTunnel-section,AbstractTunnel>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 

[[TunnelUsageValue-section]]
===== *Class TunnelUsageValue*

[cols="1a"]
|===
|*TunnelUsageValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! TunnelUsageValue is a code list that enumerates the different uses of a Tunnel. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class and multiplicity*  !*Definition*
!===
|[cols="15,20,60",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type and multiplicity* !*Definition*
3+!{set:cellbgcolor:#FFFFFF} Note: Unless otherwise specified, all attributes have the stereotype «Property»
!===
|=== 
  


