[[WaterBody-package]]
==== *Package*

[cols="1a"]
|===
|{set:cellbgcolor:#FFFFFF} *Package WaterBody*
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Description: ! The WaterBody module supports representation of the thematic aspects and 3D geometry of rivers, canals, lakes, and basins. It does, however, not inherit any hydrological or other dynamic aspects of fluid flow. 
!{nbsp}{nbsp}{nbsp}{nbsp}Parent Package: ! CityGML
!{nbsp}{nbsp}{nbsp}{nbsp}Stereotype: ! «ApplicationSchema»
!===
|===

|===
|Editing instructions:
| 1) For all classes
| {nbsp}{nbsp}{nbsp}a) If a stereotype value is "<<←section,>>", change it to "none"
| {nbsp}{nbsp}{nbsp}b) If a subclass value is not provided, set it to "none"
| {nbsp}{nbsp}{nbsp}c) If a multiplicity value is not provided, set it to "1" 
| {nbsp}{nbsp}{nbsp}d) If the Role Name of a relation is not provided, delete the Role Name row
| {nbsp}{nbsp}{nbsp}e) If the stereotype of an attribute is not provided, set it to <<Property>>
| 2) For all classes with the "CodeList" stereotype 
| {nbsp}{nbsp}{nbsp}a) Copy the name and description into the table in the Code List section
| {nbsp}{nbsp}{nbsp}b) Delete the class
| 3) If there are no code lists, then delete the Code List section
| 4) Delete these instructions when done
|===

==== *Classes*

[[AbstractWaterBoundarySurface-section]]
===== *Class AbstractWaterBoundarySurface*

[cols="1a"]
|===
|*AbstractWaterBoundarySurface* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! AbstractWaterBoundarySurface is the abstract superclass for all kinds of thematic surfaces bounding a water body. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractThematicSurface-section,AbstractThematicSurface>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
|===
[[WaterBody-section]]
===== *Class WaterBody*

[cols="1a"]
|===
|*WaterBody* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A WaterBody represents significant and permanent or semi-permanent accumulations of surface water, usually covering a part of the Earth. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractOccupiedSpace-section,AbstractOccupiedSpace>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «TopLevelFeatureType»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|{set:cellbgcolor:#FFFFFF} 
|<<AbstractWaterBoundarySurface-section,AbstractWaterBoundarySurface>> 
|
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
 
|{set:cellbgcolor:#FFFFFF} class  |<<WaterBodyClassValue-section,WaterBodyClassValue>>  [0..1] |Indicates the specific type of the WaterBody.
 
|{set:cellbgcolor:#FFFFFF} function  |<<WaterBodyFunctionValue-section,WaterBodyFunctionValue>>  [0..*] |Specifies the intended purposes of the WaterBody.
 
|{set:cellbgcolor:#FFFFFF} usage  |<<WaterBodyUsageValue-section,WaterBodyUsageValue>>  [0..*] |Specifies the actual uses of the WaterBody.
|===
[[WaterBodyClassValue-section]]
===== *Class WaterBodyClassValue*

[cols="1a"]
|===
|*WaterBodyClassValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! WaterBodyClassValue is a code list used to further classify a WaterBody. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
|===
[[WaterBodyFunctionValue-section]]
===== *Class WaterBodyFunctionValue*

[cols="1a"]
|===
|*WaterBodyFunctionValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! WaterBodyFunctionValue is a code list that enumerates the different purposes of a WaterBody. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
|===
[[WaterBodyUsageValue-section]]
===== *Class WaterBodyUsageValue*

[cols="1a"]
|===
|*WaterBodyUsageValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! WaterBodyUsageValue is a code list that enumerates the different uses of a WaterBody. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
|===
[[WaterGroundSurface-section]]
===== *Class WaterGroundSurface*

[cols="1a"]
|===
|*WaterGroundSurface* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A WaterGroundSurface represents the exterior boundary surface of the submerged bottom of a water body. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractWaterBoundarySurface-section,AbstractWaterBoundarySurface>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
|===
[[WaterLevelValue-section]]
===== *Class WaterLevelValue*

[cols="1a"]
|===
|*WaterLevelValue* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! WaterLevelValue is a code list that enumerates the different levels of a water surface. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<-section,>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «CodeList»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
|===
[[WaterSurface-section]]
===== *Class WaterSurface*

[cols="1a"]
|===
|*WaterSurface* 
|[cols="1,4",frame=none,grid=none]
!===
!{nbsp}{nbsp}{nbsp}{nbsp}Definition: ! A WaterSurface represents the upper exterior interface between a water body and the atmosphere. 
!{nbsp}{nbsp}{nbsp}{nbsp}Subclass Of: ! <<AbstractWaterBoundarySurface-section,AbstractWaterBoundarySurface>> 
!{nbsp}{nbsp}{nbsp}{nbsp}StereoType: !  «FeatureType»
!===
|===

*Relations* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,25,60"]
|===
|{set:cellbgcolor:#DDDDDD} *Role name* |*Target class and multiplicity* |*Definition*
|===

*Attributes* +
Unless otherwise specified, all attributes have the stereotype «Property».

[cols="15,30,55"]
|===
|{set:cellbgcolor:#DDDDDD} *Attribute* |*Value type and multiplicity* |*Definition*
 
|{set:cellbgcolor:#FFFFFF} waterLevel  |<<WaterLevelValue-section,WaterLevelValue>>  [0..1] |Specifies the level of the WaterSurface.
|===

==== *Code Lists*

[cols="1,4"]  
|===
^|*Code List* ^|*Definition*
| |
| |
|===
  



