[ug_terms-and-definitions_section]
== Terms and Definitions
This document uses the terms defined in Sub-clause 5.3 of [OGC 06-121r8], which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this Best Practice.

For the purposes of this document, the following additional terms and definitions apply.

*2D data* +
geometry of features is represented in a two-dimensional space +
NOTE In other words, the geometry of 2D data is given using (X,Y) coordinates. +
{blank}[INSPIRE D2.8.III.2, definition 1]

*2.5D data* +
geometry of features is represented in a three-dimensional space with the constraint that, for each (X,Y) position, there is only one Z +
{blank}[INSPIRE D2.8.III.2, definition 2]

*3D data* +
Geometry of features is represented in a three-dimensional space. +
NOTE In other words, the geometry of 2D data is given using (X,Y,Z) coordinates without any constraints. +
{blank}[INSPIRE D2.8.III.2, definition 3]

*conceptual model* +
model that defines concepts of a universe of discourse +
{blank}[ISO 19101-1:2014, 4.1.5]

*conceptual schema* +
formal description of a conceptual model +
{blank}[ISO 19101-1:2014, 4.1.6]

*conformance test class* +
set of conformance test modules that must be applied to receive a single certificate of conformance +
{blank}[OGC 08-131r3, definition 4.4]

*feature* +
abstraction of real world phenomena +
{blank}[ISO 19101-1:2014, definition 4.1.11]

*feature attribute* +
characteristic of a feature +
{blank}[ISO 19101-1:2014, definition 4.1.12]

*feature type* +
class of features having common characteristics +
{blank}[ISO 19156:2011, definition 4.7]

*level of detail* +
quantity of information that portrays the real world
NOTE The concept comprises data capturing rules of spatial object types, the accuracy and the types of geometries, and other aspects of a data specification. In particular, it is related to the notions of scale and resolution. +
{blank}[INSPIRE Glossary]

*life-cycle information* +
set of properties of a spatial object that describe the temporal characteristics of a version of a spatial object or the changes between versions +
{blank}[INSPIRE Glossary]

*measurement* +
set of operations having the object of determining the value of a quantity +
{blank}[ISO 19101-2:2018, definition 3.21] / [VIM:1993, 2.1]

*model* +
abstraction of some aspects of reality +
{blank}[ISO 19109:2015, definition 4.15]

*observation* +
act of measuring or otherwise determining the value of a property +
{blank}[ISO 19156:2011, definition 4.11]

*observation procedure* +
method, algorithm or instrument, or system of these, which may be used in making an observation +
{blank}[ISO 19156:2011, 4.12]

*observation result* +
estimate of the value of a property determined through a known observation procedure +
{blank}[ISO 19156:2011, 4.14]

*property* +
facet or attribute of an object referenced by a name. +
{blank}[ISO 19143:2010, definition 4.21]

*requirements class* +
aggregate of all requirement modules that must all be satisfied to satisfy a conformance test class +
{blank}[OGC 08-131r3, definition 4.19]

*schema* +
formal description of a model +
{blank}[ISO 19101-1:2014, definition 4.1.34]

*sensor* +
type of observation procedure that provides the estimated value of an observed property at its output +
{blank}[OGC 08-094r1, definition 4.5]

*timeseries* +
sequence of data values which are ordered in time +
{blank}[OGC 15-043r3]

*universe of discourse* +
view of the real or hypothetical world that includes everything of interest +
{blank}[ISO 19101-1:2014, definition 4.1.38]

*version* +
Particular variation of a spatial object +
{blank}[INSPIRE Glossary]


=== Abbreviated Terms

The following abbreviated terms are used in this document:

The list of acronyms needs to be reviewed once all sections have been updated.

    2D       Two Dimensional

    3D       Three Dimensional

    AEC          Architecture, Engineering, Construction

    ALKIS       German National Standard for Cadastral Information

    ATKIS       German National Standard for Topographic and Cartographic Information

    B-Rep       Boundary Representation

    bSI       buildingSMART International

    CAD       Computer Aided Design

    COLLADA   Collaborative Design Activity

    CSG       Constructive Solid Geometry

    DTM       Digital Terrain Model

    DXF       Drawing Exchange Format

    EuroSDR       European Spatial Data Research Organisation

    ESRI       Environmental Systems Research Institute

    FM       Facility Management

    GDF       Geographic Data Files

    GDI-DE       Spatial Data Infrastructure Germany (Geodateninfrastruktur Deutschland)

    GDI       NRW Geodata Infrastructure North-Rhine Westphalia

    GML       Geography Markup Language

    IAI       International Alliance for Interoperability (now buildingSMART International (bSI))

    IETF       Internet Engineering Task Force

    IFC       Industry Foundation Classes

    ISO       International Organization for Standardisation

    LOD       Level of Detail

    NBIMS       National Building Information Model Standard

    OASIS       Organisation for the Advancement of Structured Information Standards

    OGC       Open Geospatial Consortium

    OSCRE       Open Standards Consortium for Real Estate

    SIG 3D       Special Interest Group 3D of the GDI-DE

    TC211       ISO Technical Committee 211

    TIC       Terrain Intersection Curve

    TIN       Triangulated Irregular Network

    UML       Unified Modeling Language

    URI       Uniform Resource Identifier

    VRML       Virtual Reality Modeling Language

    W3C       World Wide Web Consortium

    W3DS       OGC Web 3D Service

    WFS       OGC Web Feature Service

    X3D       Open Standards XML-enabled 3D file format of the Web 3D Consortium

    XML       Extensible Markup Language

    xAL       OASIS extensible Address Language

