[[ug_references_section]]
== References
The following normative documents contain provisions that, through reference in this text, constitute provisions of OGC 20-010. For dated references, subsequent amendments to, or revisions of, any of these publications do not apply. However, parties to agreements based on this part of OGC 12-019 are encouraged to investigate the possibility of applying the most recent editions of the normative documents indicated below. For undated references, the latest edition of the normative document referred to applies.

*   IETF: RFC 2045 & 2046, Multipurpose Internet Mail Extensions (MIME). (November 1996),

*   IETF: RFC 3986, Uniform Resource Identifier (URI): Generic Syntax. (January 2005)

*   ISO: ISO 8601:2004, Data elements and interchange formats – Information interchange – Representation of dates and times

*   ISO: ISO 19103:2015, Geographic Information – Conceptual Schema Language

*   ISO: ISO 19107:2003, Geographic Information – Spatial Schema

*   ISO: ISO 19111:2019, Geographic information – Referencing by coordinates

*   ISO: ISO/IEC 19505-2:2012,
Information technology -- Object Management Group Unified ModelingLanguage (OMG UML) -- Part 2: Superstructure

*   ISO/IEC 19507:2012, Information technology -- Object Management Group Object Constraint Language (OCL)

*   OASIS: Customer Information Quality Specifications - extensible Address Language (xAL), Version v3.0

*   OGC: The OpenGIS® Abstract Specification Topic 5: Features, OGC document 08-126

*   OGC: The OpenGIS™ Abstract Specification Topic 8: Relationships Between Features, OGC document 99-108r2

*   OGC: The OpenGIS™ Abstract Specification Topic 10: Feature Collections, OGC document 99-110