[[ug_codelists_section]]
=== Code Lists

|===
^|*Contributors*
|TBD
|===

NOTE: Section 5.7.1 duplicates the information in this section. Consider merging the content of these two sections. 

NOTE: The following text needs to be reviewed and updated.

CityGML feature types often include attributes whose values can be enumerated in a list of discrete values. An example is the attribute roof type of a building, whose attribute values typically are saddle back roof, hip roof, semi-hip roof, flat roof, pent roof, or tent roof. If such an attribute is typed as string, misspellings or different names for the same notion obstruct interoperability.

If the list of values is fixed, the allowed attribute values are specified in and enforced by the CityGML schema using an enumeration as attribute type. Attributes of an enumerated type may only take values from the prede-fined list. Examples for such attributes are relativeToTerrain and relativeToWater of the abstract base class core:_CityObject (CityGML Core module, cf. chapter 10.1) as well as wrapMode of the abstract class app:_Texture (Appearance module, cf. chapter 9.4).

In case a fixed enumeration of possible attribute values is not suitable, the attribute type is specified as gml:CodeType and the allowed attribute values can be provided in a code list which is specified outside the CityGML schema. Examples for such attributes are class, function, and usage which are available for almost all CityGML feature types. A code list contains coded attribute values which hinder misspellings and ensure that the same code is used for the same notion or concept. If a code list is provided for an attribute of type gml:CodeType, then any conformant attribute shall only take values from the given code list. This allows appli-cations to validate the attribute values and thus facilitates semantic and syntactic interoperability. The optional codeSpace attribute declared for gml:CodeType is used to associate an attribute with a code list. If a codeSpace is present, then its value shall be a persistent URI identifying the code list. If no codeSpace is given, then the attribute value can only be interpreted as a simple text token and validation requires additional knowledge.

The governance of code lists is decoupled from the governance of the CityGML schema and specification. Accordingly, code lists can be specified by any organisation or information community according to their infor-mation needs. There shall be one authority per codeSpace and hence per code list who is in charge of the con-tents and the maintenance of the code list. As a result, the code list values are managed outside the CityGML schema. Thus, in contrast to a fixed enumeration enforced by the CityGML schema, changes to a code list do not require a revision of the CityGML schema and specification.

The contents of code lists may substantially vary for different countries (e.g., due to national law or regulations) and for different information communities. For this reason, this International standard does not specify norma-tive code lists for any of the attributes of type gml:CodeType. However, Annex C provides non-normative code lists for selected attributes which are proposed and maintained by the SIG 3D. These code lists can be directly referenced in CityGML instance documents and serve as an example for the definition of code lists. The code lists given in Annex C comprise the non-normative code lists which are included in the previous version 1.0 of this International standard in order to ensure backwards compatibility.

It is recommended that code lists are implemented as simple dictionaries following the GML 3.1.1 Simple Dictionary Profile (cf. Whiteside 2005). An example for a code list implemented as simple dictionary is given below. It shows an excerpt of the code list proposed by the SIG 3D for the attribute roofType of the class _AbstractBuilding (Building module, cf. chapter 10.3).

NOTE: Issue - should we use GML in the examples?

[source,XML]
----
<gml:Dictionary xmlns:gml="http://www.opengis.net/gml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.opengis.net/gml http://schemas.opengis.net/gml/3.1.1/profiles/SimpleDictionary/1.0.0/gmlSimpleDictionaryProfile.xsd" gml:id="roofType"> 
  <gml:name>roofType</gml:name> 
  <gml:dictionaryEntry> 
    <gml:Definition gml:id="id357"> 
      <gml:description>flat roof</gml:description>
      <gml:name>1000</gml:name> 
    </gml:Definition> 
  </gml:dictionaryEntry> 
  <gml:dictionaryEntry> 
    <gml:Definition gml:id="id358"> 
      <gml:description>monopitch roof</gml:description>
      <gml:name>1010</gml:name> 
    </gml:Definition>
  </gml:dictionaryEntry> 
  … 
</gml:Dictionary>
----
[[listing-2]]
.Example of a code list implemented as simple dictionary following the GML 3.1.1 Simple Dictionary Profile.

In the simple dictionary concept, the code list itself is represented by a gml:Dictionary element. The allowed attribute values are listed as gml:Definition entries contained in the gml:Dictionary. For each definition entry, the coded attribute value is specified by the gml:name subelement. Any attribute referencing this code list in a CityGML instance document may only take values which are specified by a gml:name element of one of the definition entries. If the attribute value is not specified by one of the definition entries, then the attribute value is invalid. The gml:description subelement of a definition entry provides an additional textual description for the coded attribute value. This description can be used, for example, as human readable substitute for the coded attribute value.

The following excerpt of a CityGML instance document illustrates the usage of the code list mechanism. The document contains a bldg:Building object whose roofType value is taken from the code list shown in Listing 2. The codeSpace attribute of the roofType element identifies the code list through the globally unique URL http://www.sig3d.org/codelists/standard/building/2.0/_AbstractBuilding_roofType.xml which is managed and maintained by the SIG 3D. According to this code list, the coded attribute value 1000 denotes a flat roof for this building.

[source,XML]
----
<bldg:Building> 
  <bldg:roofType
      codeSpace="http://www.sig3d.org/codelists/standard/building/2.0/_AbstractBuilding_roofType.xml">1000</bldg:roofType> 
  … 
</bldg:Building>
----

